// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/authored/cognito-userpools.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/authored/cognito-userpools.json";

const GROUP_COGNITO_USERPOOLS: Group = Group {
    name: "cognito-userpools",
    file: SCENARIO_FILE,
};

/// The authored cognito-userpools groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosAuthoredCognitoUserpools {
    client: aws_sdk_cognitoidentityprovider::Client,
}

impl ScenariosAuthoredCognitoUserpools {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_cognitoidentityprovider::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_cognitoidentityprovider::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosAuthoredCognitoUserpools {
    fn name(&self) -> &'static str {
        "scenarios/authored-cognito-userpools"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:CreateUserPool".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "CreateUserPool", test_cognito_userpools_create_user_pool(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:DescribeUserPool".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "DescribeUserPool", test_cognito_userpools_describe_user_pool(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:ListUserPools".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "ListUserPools", test_cognito_userpools_list_user_pools(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:CreateUserPoolClient".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "CreateUserPoolClient", test_cognito_userpools_create_user_pool_client(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:ListUserPoolClients".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "ListUserPoolClients", test_cognito_userpools_list_user_pool_clients(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:AdminCreateUser".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "AdminCreateUser", test_cognito_userpools_admin_create_user(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:ListUsers".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "ListUsers", test_cognito_userpools_list_users(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:AdminDeleteUser".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "AdminDeleteUser", test_cognito_userpools_admin_delete_user(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "cognito-userpools:DeleteUserPool".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS
                            .run_test(&ctx, "DeleteUserPool", test_cognito_userpools_delete_user_pool(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "cognito-userpools".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS.run_setup(&ctx, setup_cognito_userpools(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "cognito-userpools".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_COGNITO_USERPOOLS.run_teardown(&ctx, teardown_cognito_userpools(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_cognito_userpools(_client: &aws_sdk_cognitoidentityprovider::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_cognito_userpools(client: &aws_sdk_cognitoidentityprovider::Client) -> Vec<Call> {
    vec![
        Call {
            op: "AdminDeleteUser",
            params: scenario::map(vec![
                ("UserPoolId", scenario::context("pool.id")),
                ("Username", scenario::name("user")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .admin_delete_user()
                            .user_pool_id(b.string("UserPoolId")?)
                            .username(b.string("Username")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteUserPoolClient",
            params: scenario::map(vec![
                ("ClientId", scenario::context("client.id")),
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user_pool_client()
                            .client_id(b.string("ClientId")?)
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteUserPool",
            params: scenario::map(vec![
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user_pool()
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_cognito_userpools_create_user_pool(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "CreateUserPool",
            params: scenario::map(vec![("PoolName", scenario::name("pool"))]),
            export: vec![
                ("pool.id", "$.UserPool.Id"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_user_pool()
                            .pool_name(b.string("PoolName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.UserPool.Id"),
                scenario::equals("$.UserPool.Name", scenario::name("pool")),
            ]),
        ],
    }
}

fn test_cognito_userpools_describe_user_pool(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "DescribeUserPool",
            params: scenario::map(vec![
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .describe_user_pool()
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.UserPool.Id", scenario::context("pool.id")),
                scenario::equals("$.UserPool.Name", scenario::name("pool")),
            ]),
        ],
    }
}

fn test_cognito_userpools_list_user_pools(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "ListUserPools",
            params: scenario::lit(::serde_json::json!({"MaxResults": 60})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_user_pools()
                            .max_results(60)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.UserPools",
                vec![
                    scenario::where_entry("$.Id", scenario::context("pool.id")),
                ],
            ),
        ],
    }
}

fn test_cognito_userpools_create_user_pool_client(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "CreateUserPoolClient",
            params: scenario::map(vec![
                ("ClientName", scenario::name("client")),
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: vec![
                ("client.id", "$.UserPoolClient.ClientId"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_user_pool_client()
                            .client_name(b.string("ClientName")?)
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.UserPoolClient.ClientId"),
            ]),
        ],
    }
}

fn test_cognito_userpools_list_user_pool_clients(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "ListUserPoolClients",
            params: scenario::map(vec![
                ("MaxResults", scenario::lit(::serde_json::json!(60))),
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_user_pool_clients()
                            .max_results(60)
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.UserPoolClients",
                vec![
                    scenario::where_entry("$.ClientId", scenario::context("client.id")),
                ],
            ),
        ],
    }
}

fn test_cognito_userpools_admin_create_user(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "AdminCreateUser",
            params: scenario::map(vec![
                ("TemporaryPassword", scenario::lit(::serde_json::json!("Passw0rd!#"))),
                ("UserPoolId", scenario::context("pool.id")),
                ("Username", scenario::name("user")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .admin_create_user()
                            .temporary_password("Passw0rd!#")
                            .user_pool_id(b.string("UserPoolId")?)
                            .username(b.string("Username")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.User.Username", scenario::name("user")),
            ]),
        ],
    }
}

fn test_cognito_userpools_list_users(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "ListUsers",
            params: scenario::map(vec![
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_users()
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Users",
                vec![
                    scenario::where_entry("$.Username", scenario::name("user")),
                ],
            ),
        ],
    }
}

fn test_cognito_userpools_admin_delete_user(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "AdminDeleteUser",
            params: scenario::map(vec![
                ("UserPoolId", scenario::context("pool.id")),
                ("Username", scenario::name("user")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .admin_delete_user()
                            .user_pool_id(b.string("UserPoolId")?)
                            .username(b.string("Username")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::absent_from_list(
                    Some(Call {
                        op: "ListUsers",
                        params: scenario::map(vec![
                            ("UserPoolId", scenario::context("pool.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_users()
                                        .user_pool_id(b.string("UserPoolId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Users",
                    vec![
                        scenario::where_entry("$.Username", scenario::name("user")),
                    ],
                ),
            ),
        ],
    }
}

fn test_cognito_userpools_delete_user_pool(client: &aws_sdk_cognitoidentityprovider::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteUserPool",
            params: scenario::map(vec![
                ("UserPoolId", scenario::context("pool.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user_pool()
                            .user_pool_id(b.string("UserPoolId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::absent_by_error(
                    Call {
                        op: "DescribeUserPool",
                        params: scenario::map(vec![
                            ("UserPoolId", scenario::context("pool.id")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .describe_user_pool()
                                        .user_pool_id(b.string("UserPoolId")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    scenario::error("ResourceNotFoundException", "ResourceNotFoundException"),
                ),
            ),
            scenario::eventually(10, 500,
                scenario::absent_from_list(
                    Some(Call {
                        op: "ListUserPools",
                        params: scenario::lit(::serde_json::json!({"MaxResults": 60})),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |_b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_user_pools()
                                        .max_results(60)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.UserPools",
                    vec![
                        scenario::where_entry("$.Id", scenario::context("pool.id")),
                    ],
                ),
            ),
        ],
    }
}
