// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/authored/ecr-registry.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/authored/ecr-registry.json";

const GROUP_ECR_REGISTRY: Group = Group {
    name: "ecr-registry",
    file: SCENARIO_FILE,
};

/// The authored ecr-registry groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosAuthoredEcrRegistry {
    client: aws_sdk_ecr::Client,
}

impl ScenariosAuthoredEcrRegistry {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_ecr::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_ecr::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosAuthoredEcrRegistry {
    fn name(&self) -> &'static str {
        "scenarios/authored-ecr-registry"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "ecr-registry:GetAuthorizationToken".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_ECR_REGISTRY
                            .run_test(&ctx, "GetAuthorizationToken", test_ecr_registry_get_authorization_token(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "ecr-registry:DescribeRegistry".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_ECR_REGISTRY
                            .run_test(&ctx, "DescribeRegistry", test_ecr_registry_describe_registry(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "ecr-registry".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_ECR_REGISTRY.run_setup(&ctx, setup_ecr_registry(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "ecr-registry".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_ECR_REGISTRY.run_teardown(&ctx, teardown_ecr_registry(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_ecr_registry(_client: &aws_sdk_ecr::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_ecr_registry(_client: &aws_sdk_ecr::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn test_ecr_registry_get_authorization_token(client: &aws_sdk_ecr::Client) -> Test {
    Test {
        call: Call {
            op: "GetAuthorizationToken",
            params: scenario::lit(::serde_json::json!({})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_authorization_token()
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::matches("$.authorizationData[0].authorizationToken", "^QVdTO[g-v](?:[A-Za-z0-9+/]=|[A-Za-z0-9+/]{2}(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?)$"),
                scenario::non_empty("$.authorizationData[0].expiresAt"),
                scenario::matches("$.authorizationData[0].proxyEndpoint", "^http"),
            ]),
        ],
    }
}

fn test_ecr_registry_describe_registry(client: &aws_sdk_ecr::Client) -> Test {
    Test {
        call: Call {
            op: "DescribeRegistry",
            params: scenario::lit(::serde_json::json!({})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .describe_registry()
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.registryId"),
                scenario::non_empty("$.replicationConfiguration"),
                scenario::is_list("$.replicationConfiguration.rules"),
            ]),
        ],
    }
}
