// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/authored/appconfig-applications.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/authored/appconfig-applications.json";

const GROUP_APPCONFIG_APPLICATIONS_SHADOW: Group = Group {
    name: "appconfig-applications-shadow",
    file: SCENARIO_FILE,
};

/// The authored appconfig-applications groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosAuthoredAppconfigApplications {
    client: aws_sdk_appconfig::Client,
}

impl ScenariosAuthoredAppconfigApplications {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_appconfig::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_appconfig::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosAuthoredAppconfigApplications {
    fn name(&self) -> &'static str {
        "scenarios/authored-appconfig-applications"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:CreateApplication".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "CreateApplication", test_appconfig_applications_shadow_create_application(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:GetApplication".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "GetApplication", test_appconfig_applications_shadow_get_application(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:ListApplications".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "ListApplications", test_appconfig_applications_shadow_list_applications(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:UpdateApplication".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "UpdateApplication", test_appconfig_applications_shadow_update_application(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:DeleteApplication".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "DeleteApplication", test_appconfig_applications_shadow_delete_application(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:GetApplicationNotFound".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "GetApplicationNotFound", test_appconfig_applications_shadow_get_application_not_found(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "appconfig-applications-shadow:ListApplicationsInvalidToken".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW
                            .run_test(&ctx, "ListApplicationsInvalidToken", test_appconfig_applications_shadow_list_applications_invalid_token(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "appconfig-applications-shadow".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW.run_setup(&ctx, setup_appconfig_applications_shadow(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "appconfig-applications-shadow".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_APPCONFIG_APPLICATIONS_SHADOW.run_teardown(&ctx, teardown_appconfig_applications_shadow(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_appconfig_applications_shadow(_client: &aws_sdk_appconfig::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_appconfig_applications_shadow(client: &aws_sdk_appconfig::Client) -> Vec<Call> {
    vec![
        Call {
            op: "DeleteApplication",
            params: scenario::map(vec![
                ("ApplicationId", scenario::context("app.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_application()
                            .application_id(b.string("ApplicationId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_appconfig_applications_shadow_create_application(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "CreateApplication",
            params: scenario::map(vec![
                ("Description", scenario::lit(::serde_json::json!("compat applications group"))),
                ("Name", scenario::name("app")),
            ]),
            export: vec![
                ("app.id", "$.Id"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_application()
                            .description("compat applications group")
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.Id"),
                scenario::equals("$.Name", scenario::name("app")),
            ]),
            scenario::readback(
                Call {
                    op: "GetApplication",
                    params: scenario::map(vec![
                        ("ApplicationId", scenario::context("app.id")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .get_application()
                                    .application_id(b.string("ApplicationId")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                },
                vec![
                    scenario::equals("$.Description", scenario::lit(::serde_json::json!("compat applications group"))),
                    scenario::equals("$.Name", scenario::name("app")),
                ],
            ),
        ],
    }
}

fn test_appconfig_applications_shadow_get_application(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "GetApplication",
            params: scenario::map(vec![
                ("ApplicationId", scenario::context("app.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_application()
                            .application_id(b.string("ApplicationId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.Id", scenario::context("app.id")),
                scenario::equals("$.Name", scenario::name("app")),
            ]),
        ],
    }
}

fn test_appconfig_applications_shadow_list_applications(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "ListApplications",
            params: scenario::lit(::serde_json::json!({})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_applications()
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Items",
                vec![
                    scenario::where_entry("$.Id", scenario::context("app.id")),
                    scenario::where_entry("$.Name", scenario::name("app")),
                ],
            ),
        ],
    }
}

fn test_appconfig_applications_shadow_update_application(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "UpdateApplication",
            params: scenario::map(vec![
                ("ApplicationId", scenario::context("app.id")),
                ("Description", scenario::lit(::serde_json::json!("updated by compat"))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .update_application()
                            .application_id(b.string("ApplicationId")?)
                            .description("updated by compat")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.Description", scenario::lit(::serde_json::json!("updated by compat"))),
            ]),
            scenario::readback(
                Call {
                    op: "GetApplication",
                    params: scenario::map(vec![
                        ("ApplicationId", scenario::context("app.id")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .get_application()
                                    .application_id(b.string("ApplicationId")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                },
                vec![
                    scenario::equals("$.Description", scenario::lit(::serde_json::json!("updated by compat"))),
                    scenario::equals("$.Name", scenario::name("app")),
                ],
            ),
        ],
    }
}

fn test_appconfig_applications_shadow_delete_application(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteApplication",
            params: scenario::map(vec![
                ("ApplicationId", scenario::context("app.id")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_application()
                            .application_id(b.string("ApplicationId")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::absent_by_error(
                Call {
                    op: "GetApplication",
                    params: scenario::map(vec![
                        ("ApplicationId", scenario::context("app.id")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .get_application()
                                    .application_id(b.string("ApplicationId")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                },
                scenario::error("ResourceNotFoundException", "ResourceNotFoundException"),
            ),
            scenario::absent_from_list(
                Some(Call {
                    op: "ListApplications",
                    params: scenario::lit(::serde_json::json!({})),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |_b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_applications()
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                }),
                "$.Items",
                vec![
                    scenario::where_entry("$.Id", scenario::context("app.id")),
                ],
            ),
        ],
    }
}

fn test_appconfig_applications_shadow_get_application_not_found(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "GetApplication",
            params: scenario::lit(::serde_json::json!({"ApplicationId": "zzzzzzz"})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_application()
                            .application_id("zzzzzzz")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::error_code(scenario::error("ResourceNotFoundException", "ResourceNotFoundException")),
        ],
    }
}

fn test_appconfig_applications_shadow_list_applications_invalid_token(client: &aws_sdk_appconfig::Client) -> Test {
    Test {
        call: Call {
            op: "ListApplications",
            params: scenario::lit(::serde_json::json!({"MaxResults": 1, "NextToken": "compat-not-a-real-token"})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_applications()
                            .max_results(1)
                            .next_token("compat-not-a-real-token")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::error_code(scenario::error("BadRequestException", "BadRequestException")),
        ],
    }
}
