// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/authored/eventbridge-buses.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/authored/eventbridge-buses.json";

const GROUP_EVENTBRIDGE_BUSES: Group = Group {
    name: "eventbridge-buses",
    file: SCENARIO_FILE,
};

/// The authored eventbridge-buses groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosAuthoredEventbridgeBuses {
    client: aws_sdk_eventbridge::Client,
}

impl ScenariosAuthoredEventbridgeBuses {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_eventbridge::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_eventbridge::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosAuthoredEventbridgeBuses {
    fn name(&self) -> &'static str {
        "scenarios/authored-eventbridge-buses"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "eventbridge-buses:CreateEventBus".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES
                            .run_test(&ctx, "CreateEventBus", test_eventbridge_buses_create_event_bus(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "eventbridge-buses:DescribeEventBus".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES
                            .run_test(&ctx, "DescribeEventBus", test_eventbridge_buses_describe_event_bus(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "eventbridge-buses:ListEventBuses".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES
                            .run_test(&ctx, "ListEventBuses", test_eventbridge_buses_list_event_buses(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "eventbridge-buses:TagEventBus".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES
                            .run_test(&ctx, "TagEventBus", test_eventbridge_buses_tag_event_bus(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "eventbridge-buses:ListEventBridgeTagsForResource".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES
                            .run_test(&ctx, "ListEventBridgeTagsForResource", test_eventbridge_buses_list_event_bridge_tags_for_resource(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "eventbridge-buses:DeleteEventBus".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES
                            .run_test(&ctx, "DeleteEventBus", test_eventbridge_buses_delete_event_bus(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "eventbridge-buses".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES.run_setup(&ctx, setup_eventbridge_buses(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "eventbridge-buses".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_EVENTBRIDGE_BUSES.run_teardown(&ctx, teardown_eventbridge_buses(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_eventbridge_buses(_client: &aws_sdk_eventbridge::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_eventbridge_buses(client: &aws_sdk_eventbridge::Client) -> Vec<Call> {
    vec![
        Call {
            op: "DeleteEventBus",
            params: scenario::map(vec![("Name", scenario::name("bus"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_event_bus()
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_eventbridge_buses_create_event_bus(client: &aws_sdk_eventbridge::Client) -> Test {
    Test {
        call: Call {
            op: "CreateEventBus",
            params: scenario::map(vec![("Name", scenario::name("bus"))]),
            export: vec![
                ("bus.arn", "$.EventBusArn"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_event_bus()
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.EventBusArn"),
            ]),
        ],
    }
}

fn test_eventbridge_buses_describe_event_bus(client: &aws_sdk_eventbridge::Client) -> Test {
    Test {
        call: Call {
            op: "DescribeEventBus",
            params: scenario::map(vec![("Name", scenario::name("bus"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .describe_event_bus()
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.Arn", scenario::context("bus.arn")),
                scenario::equals("$.Name", scenario::name("bus")),
            ]),
        ],
    }
}

fn test_eventbridge_buses_list_event_buses(client: &aws_sdk_eventbridge::Client) -> Test {
    Test {
        call: Call {
            op: "ListEventBuses",
            params: scenario::map(vec![("NamePrefix", scenario::name("bus"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_event_buses()
                            .name_prefix(b.string("NamePrefix")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.EventBuses",
                vec![
                    scenario::where_entry("$.Name", scenario::name("bus")),
                ],
            ),
        ],
    }
}

fn test_eventbridge_buses_tag_event_bus(client: &aws_sdk_eventbridge::Client) -> Test {
    Test {
        call: Call {
            op: "TagResource",
            params: scenario::map(vec![
                ("ResourceARN", scenario::context("bus.arn")),
                ("Tags", scenario::lit(::serde_json::json!([{"Key": "env", "Value": "compat"}]))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .tag_resource()
                            .resource_arn(b.string("ResourceARN")?)
                            .tags(
                                aws_sdk_eventbridge::types::Tag::builder()
                                    .key("env")
                                    .value("compat")
                                    .build()
                                    .map_err(|err| scenario::build_error("Tags[0]", err))?
                            )
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                Some(Call {
                    op: "ListTagsForResource",
                    params: scenario::map(vec![
                        ("ResourceARN", scenario::context("bus.arn")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_tags_for_resource()
                                    .resource_arn(b.string("ResourceARN")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                }),
                "$.Tags",
                vec![
                    scenario::where_entry("$.Key", scenario::lit(::serde_json::json!("env"))),
                    scenario::where_entry("$.Value", scenario::lit(::serde_json::json!("compat"))),
                ],
            ),
        ],
    }
}

fn test_eventbridge_buses_list_event_bridge_tags_for_resource(client: &aws_sdk_eventbridge::Client) -> Test {
    Test {
        call: Call {
            op: "ListTagsForResource",
            params: scenario::map(vec![
                ("ResourceARN", scenario::context("bus.arn")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_tags_for_resource()
                            .resource_arn(b.string("ResourceARN")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Tags",
                vec![
                    scenario::where_entry("$.Key", scenario::lit(::serde_json::json!("env"))),
                    scenario::where_entry("$.Value", scenario::lit(::serde_json::json!("compat"))),
                ],
            ),
        ],
    }
}

fn test_eventbridge_buses_delete_event_bus(client: &aws_sdk_eventbridge::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteEventBus",
            params: scenario::map(vec![("Name", scenario::name("bus"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_event_bus()
                            .name(b.string("Name")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::absent_from_list(
                Some(Call {
                    op: "ListEventBuses",
                    params: scenario::map(vec![
                        ("NamePrefix", scenario::name("bus")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_event_buses()
                                    .name_prefix(b.string("NamePrefix")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                }),
                "$.EventBuses",
                vec![
                    scenario::where_entry("$.Name", scenario::name("bus")),
                ],
            ),
        ],
    }
}
