// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/authored/sqs-queues.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/authored/sqs-queues.json";

const GROUP_SQS_QUEUES: Group = Group {
    name: "sqs-queues",
    file: SCENARIO_FILE,
};

/// The authored sqs-queues groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosAuthoredSqsQueues {
    client: aws_sdk_sqs::Client,
}

impl ScenariosAuthoredSqsQueues {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_sqs::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_sqs::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosAuthoredSqsQueues {
    fn name(&self) -> &'static str {
        "scenarios/authored-sqs-queues"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:CreateQueue".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "CreateQueue", test_sqs_queues_create_queue(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:GetQueueUrl".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "GetQueueUrl", test_sqs_queues_get_queue_url(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:ListQueues".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "ListQueues", test_sqs_queues_list_queues(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:SetQueueAttributes".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "SetQueueAttributes", test_sqs_queues_set_queue_attributes(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:GetQueueAttributes".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "GetQueueAttributes", test_sqs_queues_get_queue_attributes(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:TagQueue".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "TagQueue", test_sqs_queues_tag_queue(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:UntagQueue".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "UntagQueue", test_sqs_queues_untag_queue(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "sqs-queues:DeleteQueue".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES
                            .run_test(&ctx, "DeleteQueue", test_sqs_queues_delete_queue(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "sqs-queues".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES.run_setup(&ctx, setup_sqs_queues(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "sqs-queues".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_SQS_QUEUES.run_teardown(&ctx, teardown_sqs_queues(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_sqs_queues(client: &aws_sdk_sqs::Client) -> Vec<Call> {
    vec![
        Call {
            op: "CreateQueue",
            params: scenario::map(vec![("QueueName", scenario::name("q"))]),
            export: vec![
                ("queue.url", "$.QueueUrl"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_queue()
                            .queue_name(b.string("QueueName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn teardown_sqs_queues(client: &aws_sdk_sqs::Client) -> Vec<Call> {
    vec![
        Call {
            op: "DeleteQueue",
            params: scenario::map(vec![
                ("QueueUrl", scenario::context("queue.createdUrl")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_queue()
                            .queue_url(b.string("QueueUrl")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteQueue",
            params: scenario::map(vec![
                ("QueueUrl", scenario::context("queue.url")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_queue()
                            .queue_url(b.string("QueueUrl")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_sqs_queues_create_queue(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "CreateQueue",
            params: scenario::map(vec![("QueueName", scenario::name("created"))]),
            export: vec![
                ("queue.createdUrl", "$.QueueUrl"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_queue()
                            .queue_name(b.string("QueueName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.QueueUrl"),
            ]),
            scenario::list_contains(
                Some(Call {
                    op: "ListQueues",
                    params: scenario::map(vec![
                        ("QueueNamePrefix", scenario::name("created")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_queues()
                                    .queue_name_prefix(b.string("QueueNamePrefix")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                }),
                "$.QueueUrls",
                vec![
                    scenario::where_entry("$", scenario::context("queue.createdUrl")),
                ],
            ),
        ],
    }
}

fn test_sqs_queues_get_queue_url(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "GetQueueUrl",
            params: scenario::map(vec![("QueueName", scenario::name("q"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_queue_url()
                            .queue_name(b.string("QueueName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.QueueUrl", scenario::context("queue.url")),
            ]),
        ],
    }
}

fn test_sqs_queues_list_queues(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "ListQueues",
            params: scenario::map(vec![("QueueNamePrefix", scenario::name("q"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_queues()
                            .queue_name_prefix(b.string("QueueNamePrefix")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.QueueUrls",
                vec![
                    scenario::where_entry("$", scenario::context("queue.url")),
                ],
            ),
        ],
    }
}

fn test_sqs_queues_set_queue_attributes(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "SetQueueAttributes",
            params: scenario::map(vec![
                ("Attributes", scenario::lit(::serde_json::json!({"VisibilityTimeout": "60"}))),
                ("QueueUrl", scenario::context("queue.url")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .set_queue_attributes()
                            .attributes(aws_sdk_sqs::types::QueueAttributeName::from("VisibilityTimeout"), "60")
                            .queue_url(b.string("QueueUrl")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::readback(
                Call {
                    op: "GetQueueAttributes",
                    params: scenario::map(vec![
                        ("AttributeNames", scenario::lit(::serde_json::json!(["VisibilityTimeout"]))),
                        ("QueueUrl", scenario::context("queue.url")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .get_queue_attributes()
                                    .attribute_names(aws_sdk_sqs::types::QueueAttributeName::from("VisibilityTimeout"))
                                    .queue_url(b.string("QueueUrl")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                },
                vec![
                    scenario::equals("$.Attributes.VisibilityTimeout", scenario::lit(::serde_json::json!("60"))),
                ],
            ),
        ],
    }
}

fn test_sqs_queues_get_queue_attributes(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "GetQueueAttributes",
            params: scenario::map(vec![
                ("AttributeNames", scenario::lit(::serde_json::json!(["All"]))),
                ("QueueUrl", scenario::context("queue.url")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_queue_attributes()
                            .attribute_names(aws_sdk_sqs::types::QueueAttributeName::from("All"))
                            .queue_url(b.string("QueueUrl")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.Attributes.ApproximateNumberOfMessages"),
                scenario::non_empty("$.Attributes.QueueArn"),
                scenario::equals("$.Attributes.VisibilityTimeout", scenario::lit(::serde_json::json!("60"))),
            ]),
        ],
    }
}

fn test_sqs_queues_tag_queue(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "TagQueue",
            params: scenario::map(vec![
                ("QueueUrl", scenario::context("queue.url")),
                ("Tags", scenario::lit(::serde_json::json!({"env": "test", "project": "overcast"}))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .tag_queue()
                            .queue_url(b.string("QueueUrl")?)
                            .tags("env", "test")
                            .tags("project", "overcast")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::readback(
                Call {
                    op: "ListQueueTags",
                    params: scenario::map(vec![
                        ("QueueUrl", scenario::context("queue.url")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_queue_tags()
                                    .queue_url(b.string("QueueUrl")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                },
                vec![
                    scenario::equals("$.Tags.env", scenario::lit(::serde_json::json!("test"))),
                    scenario::equals("$.Tags.project", scenario::lit(::serde_json::json!("overcast"))),
                ],
            ),
        ],
    }
}

fn test_sqs_queues_untag_queue(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "UntagQueue",
            params: scenario::map(vec![
                ("QueueUrl", scenario::context("queue.url")),
                ("TagKeys", scenario::lit(::serde_json::json!(["env"]))),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .untag_queue()
                            .queue_url(b.string("QueueUrl")?)
                            .tag_keys("env")
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::readback(
                Call {
                    op: "ListQueueTags",
                    params: scenario::map(vec![
                        ("QueueUrl", scenario::context("queue.url")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_queue_tags()
                                    .queue_url(b.string("QueueUrl")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                },
                vec![
                    scenario::missing("$.Tags.env"),
                    scenario::equals("$.Tags.project", scenario::lit(::serde_json::json!("overcast"))),
                ],
            ),
        ],
    }
}

fn test_sqs_queues_delete_queue(client: &aws_sdk_sqs::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteQueue",
            params: scenario::map(vec![
                ("QueueUrl", scenario::context("queue.createdUrl")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_queue()
                            .queue_url(b.string("QueueUrl")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::absent_from_list(
                Some(Call {
                    op: "ListQueues",
                    params: scenario::map(vec![
                        ("QueueNamePrefix", scenario::name("created")),
                    ]),
                    export: Vec::new(),
                    invoke: {
                        let client = client.clone();
                        scenario::invoker(move |b| {
                            let client = client.clone();
                            Box::pin(async move {
                                let capture = scenario::Capture::new();
                                let request = client
                                    .list_queues()
                                    .queue_name_prefix(b.string("QueueNamePrefix")?)
                                    .customize()
                                    .interceptor(capture.clone());
                                Ok(scenario::observe(request.send().await, &capture))
                            })
                        })
                    },
                }),
                "$.QueueUrls",
                vec![
                    scenario::where_entry("$", scenario::context("queue.createdUrl")),
                ],
            ),
        ],
    }
}
