// Code generated by cmd/compatgen; DO NOT EDIT.
//
// Generated from compat/model/authored/iam-users.json by cmd/compatgen.
// The semantics live in crate::scenario; this file is the data and the typed
// SDK calls.

use std::collections::HashMap;
use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;
use crate::harness::{TestContext, TestFn};
use crate::scenario::{self, Call, Group, Test};

/// The scenario file every group in this file was generated from.
const SCENARIO_FILE: &str = "compat/model/authored/iam-users.json";

const GROUP_IAM_USERS_SHADOW: Group = Group {
    name: "iam-users-shadow",
    file: SCENARIO_FILE,
};

/// The authored iam-users groups.
///
/// The client is built once, from the config the suite's hand-written groups
/// share, and cloned into every test — a generated group builds its own rather
/// than adding an accessor to AwsClients for every service the generator learns
/// to cover; nothing else about the client differs.
pub struct ScenariosAuthoredIamUsers {
    client: aws_sdk_iam::Client,
}

impl ScenariosAuthoredIamUsers {
    pub fn new(clients: &Arc<AwsClients>) -> Self {
        let config = aws_sdk_iam::config::Builder::from(clients.config())
            .endpoint_url(clients.endpoint())
            .build();
        Self {
            client: aws_sdk_iam::Client::from_conf(config),
        }
    }
}

impl ServiceGroup for ScenariosAuthoredIamUsers {
    fn name(&self) -> &'static str {
        "scenarios/authored-iam-users"
    }

    fn impls(&self) -> HashMap<String, TestFn> {
        let mut impls: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:CreateUser".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "CreateUser", test_iam_users_shadow_create_user(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:GetUser".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "GetUser", test_iam_users_shadow_get_user(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:ListUsers".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "ListUsers", test_iam_users_shadow_list_users(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:CreateAccessKey".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "CreateAccessKey", test_iam_users_shadow_create_access_key(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:DeleteAccessKey".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "DeleteAccessKey", test_iam_users_shadow_delete_access_key(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:PutUserPolicy".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "PutUserPolicy", test_iam_users_shadow_put_user_policy(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:GetUserPolicy".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "GetUserPolicy", test_iam_users_shadow_get_user_policy(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:DeleteUserPolicy".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "DeleteUserPolicy", test_iam_users_shadow_delete_user_policy(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:UpdateUser".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "UpdateUser", test_iam_users_shadow_update_user(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:ListAccessKeys".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "ListAccessKeys", test_iam_users_shadow_list_access_keys(&client))
                            .await
                    })
                }),
            );
        }
        {
            let client = self.client.clone();
            impls.insert(
                "iam-users-shadow:DeleteUser".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW
                            .run_test(&ctx, "DeleteUser", test_iam_users_shadow_delete_user(&client))
                            .await
                    })
                }),
            );
        }
        impls
    }

    fn setups(&self) -> HashMap<String, TestFn> {
        let mut setups: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            setups.insert(
                "iam-users-shadow".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW.run_setup(&ctx, setup_iam_users_shadow(&client)).await
                    })
                }),
            );
        }
        setups
    }

    fn teardowns(&self) -> HashMap<String, TestFn> {
        let mut teardowns: HashMap<String, TestFn> = HashMap::new();
        {
            let client = self.client.clone();
            teardowns.insert(
                "iam-users-shadow".to_string(),
                Arc::new(move |ctx: TestContext| {
                    let client = client.clone();
                    Box::pin(async move {
                        GROUP_IAM_USERS_SHADOW.run_teardown(&ctx, teardown_iam_users_shadow(&client)).await
                    })
                }),
            );
        }
        teardowns
    }
}

fn setup_iam_users_shadow(_client: &aws_sdk_iam::Client) -> Vec<Call> {
    // An empty phase is a no-op, not a missing one.
    Vec::new()
}

fn teardown_iam_users_shadow(client: &aws_sdk_iam::Client) -> Vec<Call> {
    vec![
        Call {
            op: "UpdateUser",
            params: scenario::map(vec![
                ("NewUserName", scenario::name("user")),
                ("UserName", scenario::name("user-upd")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .update_user()
                            .new_user_name(b.string("NewUserName")?)
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteUserPolicy",
            params: scenario::map(vec![
                ("PolicyName", scenario::lit(::serde_json::json!("inline-policy"))),
                ("UserName", scenario::name("user")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user_policy()
                            .policy_name("inline-policy")
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteAccessKey",
            params: scenario::map(vec![
                ("AccessKeyId", scenario::context("key.id")),
                ("UserName", scenario::name("user")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_access_key()
                            .access_key_id(b.string("AccessKeyId")?)
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        Call {
            op: "DeleteUser",
            params: scenario::map(vec![("UserName", scenario::name("user"))]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user()
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
    ]
}

fn test_iam_users_shadow_create_user(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "CreateUser",
            params: scenario::map(vec![("UserName", scenario::name("user"))]),
            export: vec![
                ("user.id", "$.User.UserId"),
                ("user.name", "$.User.UserName"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_user()
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.User.Arn"),
                scenario::non_empty("$.User.UserId"),
                scenario::equals("$.User.UserName", scenario::name("user")),
            ]),
            scenario::eventually(10, 500,
                scenario::list_contains(
                    Some(Call {
                        op: "ListUsers",
                        params: scenario::lit(::serde_json::json!({"MaxItems": 1000})),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |_b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_users()
                                        .max_items(1000)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Users",
                    vec![
                        scenario::where_entry("$.UserName", scenario::name("user")),
                    ],
                ),
            ),
        ],
    }
}

fn test_iam_users_shadow_get_user(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "GetUser",
            params: scenario::map(vec![
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_user()
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals("$.User.UserId", scenario::context("user.id")),
                scenario::equals("$.User.UserName", scenario::context("user.name")),
            ]),
        ],
    }
}

fn test_iam_users_shadow_list_users(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "ListUsers",
            params: scenario::lit(::serde_json::json!({"MaxItems": 1000})),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |_b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_users()
                            .max_items(1000)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::list_contains(
                None,
                "$.Users",
                vec![
                    scenario::where_entry("$.UserId", scenario::context("user.id")),
                    scenario::where_entry("$.UserName", scenario::context("user.name")),
                ],
            ),
        ],
    }
}

fn test_iam_users_shadow_create_access_key(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "CreateAccessKey",
            params: scenario::map(vec![
                ("UserName", scenario::context("user.name")),
            ]),
            export: vec![
                ("key.id", "$.AccessKey.AccessKeyId"),
            ],
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .create_access_key()
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::non_empty("$.AccessKey.AccessKeyId"),
                scenario::non_empty("$.AccessKey.SecretAccessKey"),
                scenario::equals("$.AccessKey.Status", scenario::lit(::serde_json::json!("Active"))),
                scenario::equals("$.AccessKey.UserName", scenario::context("user.name")),
            ]),
            scenario::eventually(10, 500,
                scenario::list_contains(
                    Some(Call {
                        op: "ListAccessKeys",
                        params: scenario::map(vec![
                            ("UserName", scenario::context("user.name")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_access_keys()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.AccessKeyMetadata",
                    vec![
                        scenario::where_entry("$.AccessKeyId", scenario::context("key.id")),
                        scenario::where_entry("$.Status", scenario::lit(::serde_json::json!("Active"))),
                    ],
                ),
            ),
        ],
    }
}

fn test_iam_users_shadow_delete_access_key(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteAccessKey",
            params: scenario::map(vec![
                ("AccessKeyId", scenario::context("key.id")),
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_access_key()
                            .access_key_id(b.string("AccessKeyId")?)
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::absent_from_list(
                    Some(Call {
                        op: "ListAccessKeys",
                        params: scenario::map(vec![
                            ("UserName", scenario::context("user.name")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_access_keys()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.AccessKeyMetadata",
                    vec![
                        scenario::where_entry("$.AccessKeyId", scenario::context("key.id")),
                    ],
                ),
            ),
        ],
    }
}

fn test_iam_users_shadow_put_user_policy(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "PutUserPolicy",
            params: scenario::map(vec![
                ("PolicyDocument", scenario::lit(::serde_json::json!("{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"s3:GetObject\",\"Resource\":\"*\"}]}"))),
                ("PolicyName", scenario::lit(::serde_json::json!("inline-policy"))),
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .put_user_policy()
                            .policy_document("{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"s3:GetObject\",\"Resource\":\"*\"}]}")
                            .policy_name("inline-policy")
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::list_contains(
                    Some(Call {
                        op: "ListUserPolicies",
                        params: scenario::map(vec![
                            ("UserName", scenario::context("user.name")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_user_policies()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.PolicyNames",
                    vec![
                        scenario::where_entry("$", scenario::lit(::serde_json::json!("inline-policy"))),
                    ],
                ),
            ),
        ],
    }
}

fn test_iam_users_shadow_get_user_policy(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "GetUserPolicy",
            params: scenario::map(vec![
                ("PolicyName", scenario::lit(::serde_json::json!("inline-policy"))),
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .get_user_policy()
                            .policy_name("inline-policy")
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::equals_json("$.PolicyDocument", "{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Resource\":\"*\"}],\"Version\":\"2012-10-17\"}"),
                scenario::equals("$.PolicyName", scenario::lit(::serde_json::json!("inline-policy"))),
                scenario::equals("$.UserName", scenario::context("user.name")),
            ]),
        ],
    }
}

fn test_iam_users_shadow_delete_user_policy(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteUserPolicy",
            params: scenario::map(vec![
                ("PolicyName", scenario::lit(::serde_json::json!("inline-policy"))),
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user_policy()
                            .policy_name("inline-policy")
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::absent_from_list(
                    Some(Call {
                        op: "ListUserPolicies",
                        params: scenario::map(vec![
                            ("UserName", scenario::context("user.name")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_user_policies()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.PolicyNames",
                    vec![
                        scenario::where_entry("$", scenario::lit(::serde_json::json!("inline-policy"))),
                    ],
                ),
            ),
            scenario::eventually(10, 500,
                scenario::absent_by_error(
                    Call {
                        op: "GetUserPolicy",
                        params: scenario::map(vec![
                            ("PolicyName", scenario::lit(::serde_json::json!("inline-policy"))),
                            ("UserName", scenario::context("user.name")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_user_policy()
                                        .policy_name("inline-policy")
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    scenario::error("NoSuchEntityException", "NoSuchEntity"),
                ),
            ),
        ],
    }
}

fn test_iam_users_shadow_update_user(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "UpdateUser",
            params: scenario::map(vec![
                ("NewPath", scenario::lit(::serde_json::json!("/newpath/"))),
                ("NewUserName", scenario::name("user-upd")),
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .update_user()
                            .new_path("/newpath/")
                            .new_user_name(b.string("NewUserName")?)
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::readback(
                    Call {
                        op: "GetUser",
                        params: scenario::map(vec![
                            ("UserName", scenario::name("user-upd")),
                        ]),
                        export: vec![
                            ("user.name", "$.User.UserName"),
                        ],
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_user()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    vec![
                        scenario::equals("$.User.Path", scenario::lit(::serde_json::json!("/newpath/"))),
                        scenario::equals("$.User.UserId", scenario::context("user.id")),
                        scenario::equals("$.User.UserName", scenario::name("user-upd")),
                    ],
                ),
            ),
            scenario::eventually(10, 500,
                scenario::absent_by_error(
                    Call {
                        op: "GetUser",
                        params: scenario::map(vec![
                            ("UserName", scenario::name("user")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_user()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    scenario::error("NoSuchEntityException", "NoSuchEntity"),
                ),
            ),
        ],
    }
}

fn test_iam_users_shadow_list_access_keys(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "ListAccessKeys",
            params: scenario::map(vec![
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .list_access_keys()
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::response_field(vec![
                scenario::is_list("$.AccessKeyMetadata"),
            ]),
            scenario::absent_from_list(
                None,
                "$.AccessKeyMetadata",
                vec![
                    scenario::where_entry("$.AccessKeyId", scenario::context("key.id")),
                ],
            ),
        ],
    }
}

fn test_iam_users_shadow_delete_user(client: &aws_sdk_iam::Client) -> Test {
    Test {
        call: Call {
            op: "DeleteUser",
            params: scenario::map(vec![
                ("UserName", scenario::context("user.name")),
            ]),
            export: Vec::new(),
            invoke: {
                let client = client.clone();
                scenario::invoker(move |b| {
                    let client = client.clone();
                    Box::pin(async move {
                        let capture = scenario::Capture::new();
                        let request = client
                            .delete_user()
                            .user_name(b.string("UserName")?)
                            .customize()
                            .interceptor(capture.clone());
                        Ok(scenario::observe(request.send().await, &capture))
                    })
                })
            },
        },
        assert: vec![
            scenario::eventually(10, 500,
                scenario::absent_from_list(
                    Some(Call {
                        op: "ListUsers",
                        params: scenario::lit(::serde_json::json!({"MaxItems": 1000})),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |_b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .list_users()
                                        .max_items(1000)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    }),
                    "$.Users",
                    vec![
                        scenario::where_entry("$.UserId", scenario::context("user.id")),
                    ],
                ),
            ),
            scenario::eventually(10, 500,
                scenario::absent_by_error(
                    Call {
                        op: "GetUser",
                        params: scenario::map(vec![
                            ("UserName", scenario::context("user.name")),
                        ]),
                        export: Vec::new(),
                        invoke: {
                            let client = client.clone();
                            scenario::invoker(move |b| {
                                let client = client.clone();
                                Box::pin(async move {
                                    let capture = scenario::Capture::new();
                                    let request = client
                                        .get_user()
                                        .user_name(b.string("UserName")?)
                                        .customize()
                                        .interceptor(capture.clone());
                                    Ok(scenario::observe(request.send().await, &capture))
                                })
                            })
                        },
                    },
                    scenario::error("NoSuchEntityException", "NoSuchEntity"),
                ),
            ),
        ],
    }
}
