// Code generated by cmd/compatgen; DO NOT EDIT.
//
// The generated service groups, which main merges with the hand-written ones.
// The list is empty until cmd/compatgen's scenarioBackends table names rust-sdk.

use std::sync::Arc;

use crate::clients::AwsClients;
use crate::groups::ServiceGroup;

#[path = "scenarios_authored_eventbridge_rules_gen.rs"]
mod scenarios_authored_eventbridge_rules_gen;

#[path = "scenarios_authored_sqs_queues_gen.rs"]
mod scenarios_authored_sqs_queues_gen;

#[path = "scenarios_batch_gen.rs"]
mod scenarios_batch_gen;

#[path = "scenarios_elastic_load_balancing_gen.rs"]
mod scenarios_elastic_load_balancing_gen;

#[path = "scenarios_iam_gen.rs"]
mod scenarios_iam_gen;

#[path = "scenarios_kms_gen.rs"]
mod scenarios_kms_gen;

#[path = "scenarios_organizations_gen.rs"]
mod scenarios_organizations_gen;

#[path = "scenarios_secretsmanager_gen.rs"]
mod scenarios_secretsmanager_gen;

#[path = "scenarios_servicediscovery_gen.rs"]
mod scenarios_servicediscovery_gen;

#[path = "scenarios_sns_gen.rs"]
mod scenarios_sns_gen;

#[path = "scenarios_sqs_gen.rs"]
mod scenarios_sqs_gen;

pub fn scenario_groups(clients: &Arc<AwsClients>) -> Vec<Box<dyn ServiceGroup>> {
    vec![
        Box::new(scenarios_authored_eventbridge_rules_gen::ScenariosAuthoredEventbridgeRules::new(clients)),
        Box::new(scenarios_authored_sqs_queues_gen::ScenariosAuthoredSqsQueues::new(clients)),
        Box::new(scenarios_batch_gen::ScenariosBatch::new(clients)),
        Box::new(scenarios_elastic_load_balancing_gen::ScenariosElasticLoadBalancing::new(clients)),
        Box::new(scenarios_iam_gen::ScenariosIam::new(clients)),
        Box::new(scenarios_kms_gen::ScenariosKms::new(clients)),
        Box::new(scenarios_organizations_gen::ScenariosOrganizations::new(clients)),
        Box::new(scenarios_secretsmanager_gen::ScenariosSecretsmanager::new(clients)),
        Box::new(scenarios_servicediscovery_gen::ScenariosServicediscovery::new(clients)),
        Box::new(scenarios_sns_gen::ScenariosSns::new(clients)),
        Box::new(scenarios_sqs_gen::ScenariosSqs::new(clients)),
    ]
}
