//go:build dev

package ecr

import "github.com/overcast-sh/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		capabilities.Capability{Service: "ecr", Operation: "CreateRepository", Category: "General", Status: capabilities.StatusPartial, Notes: "Returns ARN, URI, createdAt, imageTagMutability, imageScanningConfiguration, and encryptionConfiguration; repositoryUri and push readiness depend on a reachable Docker daemon — without one, repositoryUri falls back to Overcast's own API port and the response carries the emulation-limitation header (`docker push` there answers 405)"},
		capabilities.Capability{Service: "ecr", Operation: "DescribeRepositories", Category: "General", Status: capabilities.StatusPartial, Notes: "Lists all repos or filters by name; repositoryUri is re-minted from the currently running registry on every read, so it reflects the same Docker-availability fallback as CreateRepository"},
		capabilities.Capability{Service: "ecr", Operation: "DeleteRepository", Category: "General", Status: capabilities.StatusPartial, Notes: "Deletes the repository and all its image records; a repository still holding images raises RepositoryNotEmptyException unless `force` is set. The not-empty check and the echoed repositoryUri both depend on the registry: an unreachable registry falls back to the store's own image records rather than refusing the delete"},
		capabilities.Capability{Service: "ecr", Operation: "GetAuthorizationToken", Category: "Auth", Status: capabilities.StatusPartial, Notes: "Returns `base64(\"AWS:<password>\")` and the registry proxy endpoint; token expiry is 12 hours. Without a reachable Docker daemon no registry ever starts, so proxyEndpoint falls back to Overcast's own API port and the token authenticates nothing there — `docker login` succeeds but a subsequent push/pull answers 405"},
		capabilities.Capability{Service: "ecr", Operation: "DescribeRegistry", Category: "General", Status: capabilities.StatusSupported, Notes: "Returns registry metadata with empty replication rules"},
		capabilities.Capability{Service: "ecr", Operation: "ListImages", Category: "Images", Status: capabilities.StatusPartial, Notes: "Returns image IDs (tag + digest); reconciles local registry tags into the store when Docker is available. Deliberately does not fail when the registry is transiently unreachable, unlike DescribeImages/BatchGetImage — it answers with whatever the store currently holds rather than ServerException, since an empty or stale list names no specific image to be wrong about"},
		capabilities.Capability{Service: "ecr", Operation: "DescribeImages", Category: "Images", Status: capabilities.StatusSupported, Notes: "Returns image detail objects (digest, tags, media type); an imageIds entry that resolves to nothing raises ImageNotFoundException; reconciles local registry manifests when Docker is available"},
		capabilities.Capability{Service: "ecr", Operation: "PutImage", Category: "Images", Status: capabilities.StatusSupported, Notes: "Stores an image manifest; generates a digest if none supplied"},
		capabilities.Capability{Service: "ecr", Operation: "BatchGetImage", Category: "Images", Status: capabilities.StatusSupported, Notes: "Fetches manifests by tag or digest; reconciles local registry manifests when Docker is available, and an unreachable registry answers ServerException rather than reporting an image falsely missing, mirroring DescribeImages"},
		capabilities.Capability{Service: "ecr", Operation: "DescribeImageScanFindings", Category: "Images", Status: capabilities.StatusInert, Notes: "Always reports imageScanStatus UNSUPPORTED_IMAGE with empty findings/enhancedFindings; no scan engine is emulated, regardless of scanOnPush or any registry/repository scanning configuration"},
		capabilities.Capability{Service: "ecr", Operation: "BatchDeleteImage", Category: "Images", Status: capabilities.StatusPartial, Notes: "Deletes images by tag or digest from the store; when Docker backs the repository, the registry itself is never asked to delete anything, so an image it still serves reappears on the next reconciling read (ListImages/DescribeImages/BatchGetImage) — unlike real ECR, where the deletion is durable"},
		capabilities.Capability{Service: "ecr", Operation: "PutImageTagMutability", Category: "General", Status: capabilities.StatusSupported, Notes: "Stores MUTABLE/IMMUTABLE and DescribeRepositories echoes it; not enforced against a repeat PutImage of the same tag"},
		capabilities.Capability{Service: "ecr", Operation: "PutImageScanningConfiguration", Category: "Images", Status: capabilities.StatusInert, Notes: "Stores scanOnPush and DescribeRepositories echoes it; no scan engine is emulated, so enabling it never makes DescribeImageScanFindings report anything but scanner-unavailable"},
		capabilities.Capability{Service: "ecr", Operation: "StartImageScan", Category: "Images", Status: capabilities.StatusUnsupported, Notes: "Not implemented, returns 501; no scan engine is emulated (see DescribeImageScanFindings)"},
		capabilities.Capability{Service: "ecr", Operation: "GetRegistryScanningConfiguration", Category: "Images", Status: capabilities.StatusUnsupported, Notes: "Not implemented, returns 501; registry-wide scanning configuration is not stored"},
		capabilities.Capability{Service: "ecr", Operation: "PutRegistryScanningConfiguration", Category: "Images", Status: capabilities.StatusUnsupported, Notes: "Not implemented, returns 501; registry-wide scanning configuration is not stored"},
		capabilities.Capability{Service: "ecr", Operation: "SetRepositoryPolicy", Category: "Policy", Status: capabilities.StatusSupported, Notes: "Stores arbitrary IAM policy text"},
		capabilities.Capability{Service: "ecr", Operation: "GetRepositoryPolicy", Category: "Policy", Status: capabilities.StatusSupported, Notes: "Retrieves stored policy; returns 400 if none set"},
		capabilities.Capability{Service: "ecr", Operation: "DeleteRepositoryPolicy", Category: "Policy", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ecr", Operation: "PutLifecyclePolicy", Category: "Policy", Status: capabilities.StatusSupported, Notes: "Stores lifecycle policy text for the repository"},
		capabilities.Capability{Service: "ecr", Operation: "GetLifecyclePolicy", Category: "Policy", Status: capabilities.StatusSupported, Notes: "Retrieves stored lifecycle policy; returns 400 if none set"},
		capabilities.Capability{Service: "ecr", Operation: "DeleteLifecyclePolicy", Category: "Policy", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "ecr", Operation: "TagResource", Category: "Tags", Status: capabilities.StatusSupported, Notes: "Adds/merges tags onto a repository ARN"},
		capabilities.Capability{Service: "ecr", Operation: "UntagResource", Category: "Tags", Status: capabilities.StatusSupported, Notes: "Removes tag keys from a repository ARN"},
		capabilities.Capability{Service: "ecr", Operation: "ListTagsForResource", Category: "Tags", Status: capabilities.StatusSupported},
	)
}
