//go:build dev

package apigateway

import "github.com/overcast-sh/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		// REST API v1 — API management
		capabilities.Capability{Service: "apigateway", Operation: "CreateRestApi", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Creates API with root `/` resource; default EDGE endpoint type"},
		capabilities.Capability{Service: "apigateway", Operation: "GetRestApi", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetRestApis", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Pagination not yet implemented"},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteRestApi", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Cascade deletes resources, stages, and deployments"},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateRestApi", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Patch `/name`, `/description`, `/policy`, `/disableExecuteApiEndpoint`"},
		capabilities.Capability{Service: "apigateway", Operation: "CreateResource", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Computes full path from parent chain"},
		capabilities.Capability{Service: "apigateway", Operation: "GetResource", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetResources", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Pagination not yet implemented"},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteResource", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateResource", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Patch `/pathPart`"},
		capabilities.Capability{Service: "apigateway", Operation: "PutMethod", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetMethod", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteMethod", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateMethod", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Patch `/authorizationType`, `/authorizerId`, `/apiKeyRequired`"},
		capabilities.Capability{Service: "apigateway", Operation: "PutIntegration", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "AWS_PROXY/MOCK/HTTP_PROXY/HTTP/AWS types; uri, httpMethod"},
		capabilities.Capability{Service: "apigateway", Operation: "GetIntegration", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteIntegration", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateIntegration", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "Patch integrationType, integrationUri, payloadFormatVersion"},
		capabilities.Capability{Service: "apigateway", Operation: "PutMethodResponse", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetMethodResponse", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteMethodResponse", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "PutIntegrationResponse", Category: "REST API v1 management",
			Status: capabilities.StatusSupported, Notes: "responseTemplates, selectionPattern"},
		capabilities.Capability{Service: "apigateway", Operation: "GetIntegrationResponse", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteIntegrationResponse", Category: "REST API v1 management",
			Status: capabilities.StatusSupported},

		// REST API v1 — Stages & Deployments
		capabilities.Capability{Service: "apigateway", Operation: "CreateDeployment", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetDeployments", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateStage", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported, Notes: "Links to a deployment"},
		capabilities.Capability{Service: "apigateway", Operation: "GetStage", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetStages", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateStage", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported, Notes: "Patch `/description`, `/deploymentId`, and per-key `/variables/{name}` (replace/add/remove); MethodSettings, TracingEnabled, AccessLogSetting, CacheClusterEnabled/Size, ClientCertificateId, DocumentationVersion not implemented"},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteStage", Category: "REST API v1 stages",
			Status: capabilities.StatusSupported},

		// REST API v1 — Other
		capabilities.Capability{Service: "apigateway", Operation: "CreateModel", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "id, name, contentType, schema, description"},
		capabilities.Capability{Service: "apigateway", Operation: "GetModel", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetModels", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteModel", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateAuthorizer", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "JWT and REQUEST types; config stored"},
		capabilities.Capability{Service: "apigateway", Operation: "GetAuthorizer", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetAuthorizers", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteAuthorizer", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateRequestValidator", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "validateRequestBody, validateRequestParams"},
		capabilities.Capability{Service: "apigateway", Operation: "GetRequestValidators", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteRequestValidator", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateApiKey", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "auto-generated key value"},
		capabilities.Capability{Service: "apigateway", Operation: "GetApiKey", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetApiKeys", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteApiKey", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateUsagePlan", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "throttle (token bucket) and quota measured per API key; rejection needs OVERCAST_ENFORCE_APIGATEWAY_THROTTLE"},
		capabilities.Capability{Service: "apigateway", Operation: "GetUsagePlan", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetUsagePlans", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteUsagePlan", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateUsagePlanKey", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetUsagePlanKeys", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteUsagePlanKey", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetUsage", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "daily `[used, remaining]` log per API key; counts are in-memory and reset on restart"},
		capabilities.Capability{Service: "apigateway", Operation: "CreateDomainName", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "Inert metadata; no routing effect"},
		capabilities.Capability{Service: "apigateway", Operation: "GetDomainNames", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteDomainName", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateBasePathMapping", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "Stored under the domain name"},
		capabilities.Capability{Service: "apigateway", Operation: "GetBasePathMappings", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateVpcLink", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "Status immediately AVAILABLE; no VPC connectivity enforced"},
		capabilities.Capability{Service: "apigateway", Operation: "GetVpcLinks", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteVpcLink", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "TagResource", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "PUT /tags/{arn} — merges tags; ARN may contain slashes"},
		capabilities.Capability{Service: "apigateway", Operation: "UntagResource", Category: "REST API v1 other",
			Status: capabilities.StatusSupported, Notes: "DELETE /tags/{arn}?tagKeys=k1,k2"},
		capabilities.Capability{Service: "apigateway", Operation: "GetTags", Category: "REST API v1 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetAccount", Category: "REST API v1 other",
			Status: capabilities.StatusUnsupported},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateAccount", Category: "REST API v1 other",
			Status: capabilities.StatusUnsupported},

		// HTTP API v2 — API management
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2Api", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, Notes: "HTTP and WEBSOCKET protocol types; default route selection"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Api", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Apis", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, Notes: "Pagination not yet implemented"},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateV2Api", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2Api", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, Notes: "Cascade deletes routes, integrations, stages, deployments"},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2Route", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Route", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Routes", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2Route", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateV2Route", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, Notes: "Patch routeKey, target, authorizationType"},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2Integration", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, Notes: "AWS_PROXY / HTTP_PROXY types; payloadFormatVersion 1.0/2.0", DisplayName: "CreateIntegration"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Integration", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Integrations", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2Integration", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, DisplayName: "DeleteIntegration"},
		capabilities.Capability{Service: "apigateway", Operation: "UpdateV2Integration", Category: "HTTP API v2 management",
			Status: capabilities.StatusSupported, Notes: "Patch integrationType, integrationUri, payloadFormatVersion", DisplayName: "UpdateIntegration"},

		// HTTP API v2 — Stages & Deployments
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2Deployment", Category: "HTTP API v2 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Deployments", Category: "HTTP API v2 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2Stage", Category: "HTTP API v2 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Stage", Category: "HTTP API v2 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Stages", Category: "HTTP API v2 stages",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2Stage", Category: "HTTP API v2 stages",
			Status: capabilities.StatusSupported},

		// HTTP API v2 — Other
		capabilities.Capability{Service: "apigateway", Operation: "UpdateV2Stage", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "Patch description, autoDeploy, deploymentId, stageVariables"},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2Authorizer", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "JWT and REQUEST types; config stored"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Authorizer", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Authorizers", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2Authorizer", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2DomainName", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "Inert metadata; no routing effect"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2DomainNames", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2DomainName", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2VpcLink", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "Status immediately AVAILABLE; no VPC connectivity enforced"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2VpcLinks", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "DeleteV2VpcLink", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "CreateV2ApiMapping", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "Stored under the domain name"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2ApiMappings", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "TagV2Resource", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "POST /v2/tags/{arn} — merges tags; ARN may contain slashes"},
		capabilities.Capability{Service: "apigateway", Operation: "UntagV2Resource", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported, Notes: "DELETE /v2/tags/{arn}?tagKeys=k1,k2"},
		capabilities.Capability{Service: "apigateway", Operation: "GetV2Tags", Category: "HTTP API v2 other",
			Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "apigateway", Operation: "ExecuteRestAPI", Category: "REST API v1 execution",
			EmulatorOnly: true,
			Status:       capabilities.StatusSupported, Notes: "Lambda proxy/non-proxy, HTTP_PROXY, HTTP, and MOCK integrations; stage variable substitution; base64 Lambda responses decoded before write; records AWS/ApiGateway CloudWatch metrics Count, 4XXError, 5XXError, Latency, and IntegrationLatency once per dispatched request under all three AWS-documented REST dimension combinations — ApiName, ApiName+Stage, and ApiName+Stage+Method+Resource (#1307) — an unresolvable restApiId records nothing, since there is no ApiName to dimension a series with"},
		capabilities.Capability{Service: "apigateway", Operation: "ExecuteV2API", Category: "HTTP API v2 other",
			EmulatorOnly: true,
			Status:       capabilities.StatusSupported, Notes: "AWS_PROXY and HTTP_PROXY integration types; records the same Count/4xx/5xx/Latency/IntegrationLatency metrics (HTTP APIs use AWS's lowercase 4xx/5xx metric names, not REST's 4XXError/5XXError) under all three AWS-documented HTTP dimension combinations — ApiId, ApiId+Stage, and ApiId+Stage+HttpMethod+RouteKey"},
	)
}
