//go:build dev

package main

import (
	"slices"
	"sort"

	compatmodel "github.com/overcast-sh/overcast/compat/model"
)

// The generated registry sibling, compat/suites/registry.generated.json.
//
// A group is written to the registry only when at least one suite has a
// scenario backend: `suites` is mechanically derived from backend
// availability, the schema requires at least one, and a group no suite can
// execute would be parity debt for everyone. scenarioBackends is that
// availability table. It is empty until the G2 interpreters land, so the
// registry stays `groups: []` and G0's "an empty file behaves as today" gate
// keeps holding — while the scenario files and gaps.json are fully generated
// regardless. TestRegistryIsEmptyExactlyWhileNoBackendExists pins the tie.

// scenarioBackends lists the suites that can execute scenario IR, sorted.
// Add a suite here in the PR that lands its interpreter or source emitter.
var scenarioBackends = []string{"cli", "dotnet-sdk", "go-sdk", "java-sdk", "node-js-sdk", "python-sdk", "rust-sdk"}

// The suites the typed source emitters write for. Each is named rather than
// spelled inline because two things key on it: whether that backend's emitted
// files are produced at all, and which groups the emitter could not express.
const (
	goSDKSuite     = "go-sdk"     // emit_go.go
	javaSDKSuite   = "java-sdk"   // emit_java.go
	dotnetSDKSuite = "dotnet-sdk" // emit_dotnet.go
	rustSDKSuite   = "rust-sdk"   // emit_rust.go
)

// hasBackend reports whether a suite can execute scenario IR.
func hasBackend(suite string) bool { return slices.Contains(scenarioBackends, suite) }

const (
	generatedRegistryVersion = 1
	generatedStateCandidate  = "candidate"
	generatedStateGated      = "gated"
	registryPath             = "compat/suites/registry.generated.json"
	// handRegistryPath is the hand-written half. The generator reads it for
	// one purpose: an authored scenario ports one of its groups, and the group
	// and test names have to match. See authored.go.
	handRegistryPath = "compat/suites/registry.json"
	promotionsPath   = "compat/model/promotions.json"
	scenarioDir      = "compat/model/scenarios"
	gapsPath         = "compat/model/gaps.json"
	recipesDir       = "compat/model/recipes"
	valuesPath       = "compat/model/values.json"
	modelDir         = "compat/model"
	shapesDir        = "models/aws/shapes"
)

const registryComment = "Generated by cmd/compatgen — do not hand-edit; `make generate-compat-model` rewrites this file wholly from compat/model/scenarios/. Every loader concatenates it with registry.json, which stays the reviewable hand-written half. A group appears here only while at least one suite has a scenario backend (the scenarioBackends table in cmd/compatgen/registry.go), because `suites` is derived from backend availability and must not be empty; until then the file stays empty and must leave every gate, report and dashboard behaving exactly as before it existed. See docs/plans/compat-coverage-modelgen.md § 3.6."

type generatedRegistry struct {
	Schema  string `json:"$schema"`
	Version int    `json:"version"`
	Comment string `json:"comment"`
	// Ported indexes the hand-written groups an authored scenario resolves —
	// see portedGroup. Omitted while there are none, so a checkout with no
	// ported group produces exactly the file it produced before the field
	// existed.
	Ported []portedGroup    `json:"ported,omitempty"`
	Groups []generatedGroup `json:"groups"`
}

// portedGroup is the derived half of a ported group: a hand-written registry
// group whose tests an authored scenario resolves (§3.11 step 3, #1903).
//
// The group's own entry stays in compat/suites/registry.json, where the names
// every gate file keys on already live, and says only *that* it is ported, by
// carrying `scenario`. What a human cannot state — which suites can actually
// execute it — is derived here from exactly the two facts a generated group's
// `suites` comes from: the scenarioBackends table, and which emitters refused
// the group.
//
// It is an index rather than a `suites` list written back into registry.json
// because this generator does not edit the hand-written registry. Doing so
// would put a machine in charge of the file review assumes a human owns, and
// make every backend landing a diff in it; leaving the list to be
// hand-maintained instead would be a human maintaining generator output, stale
// the first time an emitter refused a member.
type portedGroup struct {
	Group    string   `json:"group"`
	Scenario string   `json:"scenario"`
	Suites   []string `json:"suites"`
}

type generatedGroup struct {
	Service   string `json:"service"`
	Name      string `json:"name"`
	Generated bool   `json:"generated"`
	Scenario  string `json:"scenario"`
	State     string `json:"state"`
	// Parallel mirrors the scenario group's own flag, so a loader decides how
	// to schedule a group from the registry it already read rather than by
	// opening the scenario file first. Only a probe group carries it.
	Parallel bool `json:"parallel,omitempty"`
	// ShadowOf names the hand-written group this one is a shadow of: an
	// authored scenario running beside the native implementation it will
	// replace, so one nightly can compare the two per (suite, test) before the
	// natives are deleted. It is derived from the group name (`<group>-shadow`)
	// and never hand-written. A shadow group stays a candidate for as long as
	// it exists — `cmd/compat --promote-generated` skips it — because the
	// evidence it is collecting is agreement with the native group, which is a
	// different question from agreement with itself. See
	// docs/plans/compat-coverage-modelgen.md §3.11 and authored.go.
	ShadowOf string          `json:"shadowOf,omitempty"`
	Suites   []string        `json:"suites"`
	Tests    []generatedTest `json:"tests"`
}

type generatedTest struct {
	Name    string   `json:"name"`
	Op      string   `json:"op,omitempty"`
	Depends []string `json:"depends,omitempty"`
}

// scenarioPath is where a service's scenario file lives, repository-relative
// with '/' separators — the form the registry records and the interpreters
// open.
func scenarioPath(service string) string { return scenarioDir + "/" + service + ".json" }

// unableSuites names, per group, the suites whose backend exists but cannot
// execute that group. Each source emitter reports its own — a group whose input
// members it has no expression for in that language. Such a group is scoped to
// the suites that can run it, so a backend is never listed as able to execute
// something it will not compile; a group no suite can run is left out of the
// registry entirely, as one with no backends at all already is.
type unableSuites map[string]map[string]bool

func (u unableSuites) suitesFor(backends []string, group string) []string {
	unable := u[group]
	if len(unable) == 0 {
		return backends
	}
	out := make([]string, 0, len(backends))
	for _, suite := range backends {
		if !unable[suite] {
			out = append(out, suite)
		}
	}
	return out
}

// buildRegistry projects scenarios onto the registry, honouring the backend
// rule above. Groups are sorted by name across services so the file does not
// depend on the order recipes were read in.
//
// Every group is a candidate unless the soak ledger says otherwise: `state` is
// the one field here that is not derived from the scenario, and
// compat/model/promotions.json is where it comes from. See promotions.go for
// why the state is an input rather than something a second tool edits into this
// file.
func buildRegistry(units []*generation, backends []string, promotions *compatmodel.Promotions, unable unableSuites) generatedRegistry {
	reg := generatedRegistry{
		Schema:  "./registry.generated.schema.json",
		Version: generatedRegistryVersion,
		Comment: registryComment,
		Groups:  []generatedGroup{},
	}
	if len(backends) == 0 {
		return reg
	}
	suites := append([]string(nil), backends...)
	sort.Strings(suites)
	for _, gen := range units {
		s := gen.scenario
		for _, g := range s.Groups {
			groupSuites := unable.suitesFor(suites, g.Name)
			native, shadow := nativeGroupOf(g.Name)
			// A live authored group is a *ported* group: the hand-written
			// registry already declares it, so writing a group entry here
			// would collide with that entry rather than replace it — the two
			// files are concatenated, and every gate file keys on the name.
			// Only the derived scoping belongs here.
			//
			// Its `suites` is emitted even when empty, unlike a generated
			// group's, which is dropped instead. The two cases are not alike:
			// a generated group no backend can run is a group nobody asked
			// for, and leaving it out costs nothing; a ported group no backend
			// can run is a hand-written group whose implementations are about
			// to be deleted, and silently omitting it would scope it to every
			// uniform suite. The schema's minItems then fails the run, which
			// is the loud answer that case needs.
			if gen.isAuthored() && !shadow {
				reg.Ported = append(reg.Ported, portedGroup{
					Group:    native,
					Scenario: gen.file,
					Suites:   groupSuites,
				})
				continue
			}
			if len(groupSuites) == 0 {
				continue
			}
			entry := generatedGroup{
				Service:   s.Service,
				Name:      g.Name,
				Generated: true,
				Scenario:  gen.file,
				State:     promotionStateOf(promotions, g.Name),
				Parallel:  g.Parallel,
				Suites:    groupSuites,
			}
			if shadow {
				entry.ShadowOf = native
				// A shadow gates nothing, ever. Promotion is the soak that
				// asks "does this group agree with itself"; a shadow is
				// running a different soak, and it is deleted the moment that
				// one concludes, so gating it would mean gating on a group
				// with a scheduled end date.
				entry.State = generatedStateCandidate
			}
			for _, t := range g.Tests {
				rt := generatedTest{Name: t.Name, Depends: t.Depends}
				if t.Op != t.Name {
					rt.Op = t.Op
				}
				entry.Tests = append(entry.Tests, rt)
			}
			reg.Groups = append(reg.Groups, entry)
		}
	}
	sort.Slice(reg.Groups, func(i, j int) bool { return reg.Groups[i].Name < reg.Groups[j].Name })
	sort.Slice(reg.Ported, func(i, j int) bool { return reg.Ported[i].Group < reg.Ported[j].Group })
	return reg
}
