// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.IdentityManagement;
using Amazon.IdentityManagement.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The authored iam-users groups.</summary>
/// <remarks>
/// Generated from compat/model/authored/iam-users.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosAuthoredIamUsers : IServiceGroup
{
    private static readonly ScenarioGroup GroupIamUsers = new("iam-users", "compat/model/authored/iam-users.json");

    private readonly Lazy<AmazonIdentityManagementServiceClient> _client;

    internal ScenariosAuthoredIamUsers(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonIdentityManagementServiceClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonIdentityManagementServiceClient(credentials, (AmazonIdentityManagementServiceConfig)configuration),
            new AmazonIdentityManagementServiceConfig()));
    }

    public string SourceName => "ScenariosAuthoredIamUsers";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["iam-users:CreateUser"] = TestIamUsersCreateUser,
        ["iam-users:GetUser"] = TestIamUsersGetUser,
        ["iam-users:ListUsers"] = TestIamUsersListUsers,
        ["iam-users:CreateAccessKey"] = TestIamUsersCreateAccessKey,
        ["iam-users:DeleteAccessKey"] = TestIamUsersDeleteAccessKey,
        ["iam-users:PutUserPolicy"] = TestIamUsersPutUserPolicy,
        ["iam-users:GetUserPolicy"] = TestIamUsersGetUserPolicy,
        ["iam-users:DeleteUserPolicy"] = TestIamUsersDeleteUserPolicy,
        ["iam-users:UpdateUser"] = TestIamUsersUpdateUser,
        ["iam-users:ListAccessKeys"] = TestIamUsersListAccessKeys,
        ["iam-users:DeleteUser"] = TestIamUsersDeleteUser,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["iam-users"] = SetupIamUsers,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["iam-users"] = TeardownIamUsers,
    };

    private AmazonIdentityManagementServiceClient Cl() => _client.Value;

    private Task SetupIamUsers(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupIamUsers.RunSetupAsync(t);

    private Task TeardownIamUsers(TestContext t) =>
        GroupIamUsers.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "UpdateUser",
                Params = "{\"NewUserName\":{\"$name\":\"user\"},\"UserName\":{\"$name\":\"user-upd\"}}",
                Build = b =>
                {
                    var request = new UpdateUserRequest();
                    request.NewUserName = b.Bind<string>("NewUserName", Val.Name("user"));
                    request.UserName = b.Bind<string>("UserName", Val.Name("user-upd"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().UpdateUserAsync((UpdateUserRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteUserPolicy",
                Params = "{\"PolicyName\":\"inline-policy\",\"UserName\":{\"$name\":\"user\"}}",
                Build = b =>
                {
                    var request = new DeleteUserPolicyRequest();
                    request.PolicyName = "inline-policy";
                    request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteUserPolicyAsync((DeleteUserPolicyRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteAccessKey",
                Params = "{\"AccessKeyId\":{\"$ref\":\"key.id\"},\"UserName\":{\"$name\":\"user\"}}",
                Build = b =>
                {
                    var request = new DeleteAccessKeyRequest();
                    request.AccessKeyId = b.Bind<string>("AccessKeyId", Val.Ref("key.id"));
                    request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteAccessKeyAsync((DeleteAccessKeyRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteUser",
                Params = "{\"UserName\":{\"$name\":\"user\"}}",
                Build = b =>
                {
                    var request = new DeleteUserRequest();
                    request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteUserAsync((DeleteUserRequest)request),
            }
        );

    private Task TestIamUsersCreateUser(TestContext t) => GroupIamUsers.RunTestAsync(t, "CreateUser", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateUser",
            Params = "{\"UserName\":{\"$name\":\"user\"}}",
            Build = b =>
            {
                var request = new CreateUserRequest();
                request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateUserAsync((CreateUserRequest)request),
            Export = new()
            {
                ["user.id"] = "$.User.UserId",
                ["user.name"] = "$.User.UserName",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.User.Arn"),
                Check.NonEmpty("$.User.UserId"),
                Check.EqualTo("$.User.UserName", Val.Name("user"))
            ),
            Clause.Eventually(10, 500,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListUsers",
                        Params = "{\"MaxItems\":1000}",
                        Build = b =>
                        {
                            var request = new ListUsersRequest();
                            request.MaxItems = 1000;
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListUsersAsync((ListUsersRequest)request),
                    },
                    "$.Users",
                    new WhereEntry("$.UserName", Val.Name("user"))
                )
            )
        ],
    });

    private Task TestIamUsersGetUser(TestContext t) => GroupIamUsers.RunTestAsync(t, "GetUser", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetUser",
            Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new GetUserRequest();
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetUserAsync((GetUserRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.User.UserId", Val.Ref("user.id")),
                Check.EqualTo("$.User.UserName", Val.Ref("user.name"))
            )
        ],
    });

    private Task TestIamUsersListUsers(TestContext t) => GroupIamUsers.RunTestAsync(t, "ListUsers", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListUsers",
            Params = "{\"MaxItems\":1000}",
            Build = b =>
            {
                var request = new ListUsersRequest();
                request.MaxItems = 1000;
                return request;
            },
            SendAsync = async request =>
                await Cl().ListUsersAsync((ListUsersRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Users",
                new WhereEntry("$.UserId", Val.Ref("user.id")),
                new WhereEntry("$.UserName", Val.Ref("user.name"))
            )
        ],
    });

    private Task TestIamUsersCreateAccessKey(TestContext t) => GroupIamUsers.RunTestAsync(t, "CreateAccessKey", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateAccessKey",
            Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new CreateAccessKeyRequest();
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateAccessKeyAsync((CreateAccessKeyRequest)request),
            Export = new()
            {
                ["key.id"] = "$.AccessKey.AccessKeyId",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.AccessKey.AccessKeyId"),
                Check.NonEmpty("$.AccessKey.SecretAccessKey"),
                Check.EqualTo("$.AccessKey.Status", "Active"),
                Check.EqualTo("$.AccessKey.UserName", Val.Ref("user.name"))
            ),
            Clause.Eventually(10, 500,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListAccessKeys",
                        Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
                        Build = b =>
                        {
                            var request = new ListAccessKeysRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListAccessKeysAsync((ListAccessKeysRequest)request),
                    },
                    "$.AccessKeyMetadata",
                    new WhereEntry("$.AccessKeyId", Val.Ref("key.id")),
                    new WhereEntry("$.Status", "Active")
                )
            )
        ],
    });

    private Task TestIamUsersDeleteAccessKey(TestContext t) => GroupIamUsers.RunTestAsync(t, "DeleteAccessKey", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteAccessKey",
            Params = "{\"AccessKeyId\":{\"$ref\":\"key.id\"},\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new DeleteAccessKeyRequest();
                request.AccessKeyId = b.Bind<string>("AccessKeyId", Val.Ref("key.id"));
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteAccessKeyAsync((DeleteAccessKeyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 500,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "ListAccessKeys",
                        Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
                        Build = b =>
                        {
                            var request = new ListAccessKeysRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListAccessKeysAsync((ListAccessKeysRequest)request),
                    },
                    "$.AccessKeyMetadata",
                    new WhereEntry("$.AccessKeyId", Val.Ref("key.id"))
                )
            )
        ],
    });

    private Task TestIamUsersPutUserPolicy(TestContext t) => GroupIamUsers.RunTestAsync(t, "PutUserPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "PutUserPolicy",
            Params = "{\"PolicyDocument\":\"{\\\"Version\\\":\\\"2012-10-17\\\",\\\"Statement\\\":[{\\\"Effect\\\":\\\"Allow\\\",\\\"Action\\\":\\\"s3:GetObject\\\",\\\"Resource\\\":\\\"*\\\"}]}\",\"PolicyName\":\"inline-policy\",\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new PutUserPolicyRequest();
                request.PolicyDocument = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"s3:GetObject\",\"Resource\":\"*\"}]}";
                request.PolicyName = "inline-policy";
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().PutUserPolicyAsync((PutUserPolicyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 500,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "ListUserPolicies",
                        Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
                        Build = b =>
                        {
                            var request = new ListUserPoliciesRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListUserPoliciesAsync((ListUserPoliciesRequest)request),
                    },
                    "$.PolicyNames",
                    new WhereEntry("$", "inline-policy")
                )
            )
        ],
    });

    private Task TestIamUsersGetUserPolicy(TestContext t) => GroupIamUsers.RunTestAsync(t, "GetUserPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetUserPolicy",
            Params = "{\"PolicyName\":\"inline-policy\",\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new GetUserPolicyRequest();
                request.PolicyName = "inline-policy";
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetUserPolicyAsync((GetUserPolicyRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualsJson("$.PolicyDocument", "{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Resource\":\"*\"}],\"Version\":\"2012-10-17\"}"),
                Check.EqualTo("$.PolicyName", "inline-policy"),
                Check.EqualTo("$.UserName", Val.Ref("user.name"))
            )
        ],
    });

    private Task TestIamUsersDeleteUserPolicy(TestContext t) => GroupIamUsers.RunTestAsync(t, "DeleteUserPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteUserPolicy",
            Params = "{\"PolicyName\":\"inline-policy\",\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new DeleteUserPolicyRequest();
                request.PolicyName = "inline-policy";
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteUserPolicyAsync((DeleteUserPolicyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 500,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "ListUserPolicies",
                        Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
                        Build = b =>
                        {
                            var request = new ListUserPoliciesRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListUserPoliciesAsync((ListUserPoliciesRequest)request),
                    },
                    "$.PolicyNames",
                    new WhereEntry("$", "inline-policy")
                )
            ),
            Clause.Eventually(10, 500,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetUserPolicy",
                        Params = "{\"PolicyName\":\"inline-policy\",\"UserName\":{\"$ref\":\"user.name\"}}",
                        Build = b =>
                        {
                            var request = new GetUserPolicyRequest();
                            request.PolicyName = "inline-policy";
                            request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetUserPolicyAsync((GetUserPolicyRequest)request),
                    },
                    new ErrorSpec("NoSuchEntityException", "NoSuchEntity"))
            )
        ],
    });

    private Task TestIamUsersUpdateUser(TestContext t) => GroupIamUsers.RunTestAsync(t, "UpdateUser", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateUser",
            Params = "{\"NewPath\":\"/newpath/\",\"NewUserName\":{\"$name\":\"user-upd\"},\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new UpdateUserRequest();
                request.NewPath = "/newpath/";
                request.NewUserName = b.Bind<string>("NewUserName", Val.Name("user-upd"));
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateUserAsync((UpdateUserRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 500,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetUser",
                        Params = "{\"UserName\":{\"$name\":\"user-upd\"}}",
                        Build = b =>
                        {
                            var request = new GetUserRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Name("user-upd"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetUserAsync((GetUserRequest)request),
                        Export = new()
                        {
                            ["user.name"] = "$.User.UserName",
                        },
                    },
                    Check.EqualTo("$.User.Path", "/newpath/"),
                    Check.EqualTo("$.User.UserId", Val.Ref("user.id")),
                    Check.EqualTo("$.User.UserName", Val.Name("user-upd"))
                )
            ),
            Clause.Eventually(10, 500,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetUser",
                        Params = "{\"UserName\":{\"$name\":\"user\"}}",
                        Build = b =>
                        {
                            var request = new GetUserRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetUserAsync((GetUserRequest)request),
                    },
                    new ErrorSpec("NoSuchEntityException", "NoSuchEntity"))
            )
        ],
    });

    private Task TestIamUsersListAccessKeys(TestContext t) => GroupIamUsers.RunTestAsync(t, "ListAccessKeys", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListAccessKeys",
            Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new ListAccessKeysRequest();
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListAccessKeysAsync((ListAccessKeysRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.AccessKeyMetadata")
            ),
            Clause.AbsentFromList(
                null,
                "$.AccessKeyMetadata",
                new WhereEntry("$.AccessKeyId", Val.Ref("key.id"))
            )
        ],
    });

    private Task TestIamUsersDeleteUser(TestContext t) => GroupIamUsers.RunTestAsync(t, "DeleteUser", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteUser",
            Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
            Build = b =>
            {
                var request = new DeleteUserRequest();
                request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteUserAsync((DeleteUserRequest)request),
        },
        Assert =
        [
            Clause.Eventually(10, 500,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "ListUsers",
                        Params = "{\"MaxItems\":1000}",
                        Build = b =>
                        {
                            var request = new ListUsersRequest();
                            request.MaxItems = 1000;
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListUsersAsync((ListUsersRequest)request),
                    },
                    "$.Users",
                    new WhereEntry("$.UserId", Val.Ref("user.id"))
                )
            ),
            Clause.Eventually(10, 500,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetUser",
                        Params = "{\"UserName\":{\"$ref\":\"user.name\"}}",
                        Build = b =>
                        {
                            var request = new GetUserRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Ref("user.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetUserAsync((GetUserRequest)request),
                    },
                    new ErrorSpec("NoSuchEntityException", "NoSuchEntity"))
            )
        ],
    });
}
