// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.ElasticLoadBalancing;
using Amazon.ElasticLoadBalancing.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The generated elastic-load-balancing groups.</summary>
/// <remarks>
/// Generated from compat/model/scenarios/elastic-load-balancing.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosElasticLoadBalancing : IServiceGroup
{
    private static readonly ScenarioGroup GroupElasticLoadBalancingGenLoadbalancer = new("elastic-load-balancing-gen-loadbalancer", "compat/model/scenarios/elastic-load-balancing.json");
    private static readonly ScenarioGroup GroupElasticLoadBalancingGenLoadbalancerpolicy = new("elastic-load-balancing-gen-loadbalancerpolicy", "compat/model/scenarios/elastic-load-balancing.json");
    private static readonly ScenarioGroup GroupElasticLoadBalancingGenProbe = new("elastic-load-balancing-gen-probe", "compat/model/scenarios/elastic-load-balancing.json");

    private readonly Lazy<AmazonElasticLoadBalancingClient> _client;

    internal ScenariosElasticLoadBalancing(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonElasticLoadBalancingClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonElasticLoadBalancingClient(credentials, (AmazonElasticLoadBalancingConfig)configuration),
            new AmazonElasticLoadBalancingConfig()));
    }

    public string SourceName => "ScenariosElasticLoadBalancing";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["elastic-load-balancing-gen-loadbalancer:CreateLoadBalancer"] = TestElasticLoadBalancingGenLoadbalancerCreateLoadBalancer,
        ["elastic-load-balancing-gen-loadbalancer:DescribeLoadBalancers"] = TestElasticLoadBalancingGenLoadbalancerDescribeLoadBalancers,
        ["elastic-load-balancing-gen-loadbalancer:ConfigureHealthCheck"] = TestElasticLoadBalancingGenLoadbalancerConfigureHealthCheck,
        ["elastic-load-balancing-gen-loadbalancer:CreateLoadBalancerListeners"] = TestElasticLoadBalancingGenLoadbalancerCreateLoadBalancerListeners,
        ["elastic-load-balancing-gen-loadbalancer:DeleteLoadBalancerListeners"] = TestElasticLoadBalancingGenLoadbalancerDeleteLoadBalancerListeners,
        ["elastic-load-balancing-gen-loadbalancer:ModifyLoadBalancerAttributes"] = TestElasticLoadBalancingGenLoadbalancerModifyLoadBalancerAttributes,
        ["elastic-load-balancing-gen-loadbalancer:DescribeInstanceHealth"] = TestElasticLoadBalancingGenLoadbalancerDescribeInstanceHealth,
        ["elastic-load-balancing-gen-loadbalancer:CreateLBCookieStickinessPolicy"] = TestElasticLoadBalancingGenLoadbalancerCreateLBCookieStickinessPolicy,
        ["elastic-load-balancing-gen-loadbalancer:CreateAppCookieStickinessPolicy"] = TestElasticLoadBalancingGenLoadbalancerCreateAppCookieStickinessPolicy,
        ["elastic-load-balancing-gen-loadbalancer:DeleteLoadBalancer"] = TestElasticLoadBalancingGenLoadbalancerDeleteLoadBalancer,
        ["elastic-load-balancing-gen-loadbalancerpolicy:CreateLoadBalancerPolicy"] = TestElasticLoadBalancingGenLoadbalancerpolicyCreateLoadBalancerPolicy,
        ["elastic-load-balancing-gen-loadbalancerpolicy:DescribeLoadBalancerPolicies"] = TestElasticLoadBalancingGenLoadbalancerpolicyDescribeLoadBalancerPolicies,
        ["elastic-load-balancing-gen-loadbalancerpolicy:DeleteLoadBalancerPolicy"] = TestElasticLoadBalancingGenLoadbalancerpolicyDeleteLoadBalancerPolicy,
        ["elastic-load-balancing-gen-probe:DescribeAccountLimits"] = TestElasticLoadBalancingGenProbeDescribeAccountLimits,
        ["elastic-load-balancing-gen-probe:DescribeLoadBalancerAttributes"] = TestElasticLoadBalancingGenProbeDescribeLoadBalancerAttributes,
        ["elastic-load-balancing-gen-probe:DescribeLoadBalancerPolicyTypes"] = TestElasticLoadBalancingGenProbeDescribeLoadBalancerPolicyTypes,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["elastic-load-balancing-gen-loadbalancer"] = SetupElasticLoadBalancingGenLoadbalancer,
        ["elastic-load-balancing-gen-loadbalancerpolicy"] = SetupElasticLoadBalancingGenLoadbalancerpolicy,
        ["elastic-load-balancing-gen-probe"] = SetupElasticLoadBalancingGenProbe,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["elastic-load-balancing-gen-loadbalancer"] = TeardownElasticLoadBalancingGenLoadbalancer,
        ["elastic-load-balancing-gen-loadbalancerpolicy"] = TeardownElasticLoadBalancingGenLoadbalancerpolicy,
        ["elastic-load-balancing-gen-probe"] = TeardownElasticLoadBalancingGenProbe,
    };

    private AmazonElasticLoadBalancingClient Cl() => _client.Value;

    private Task SetupElasticLoadBalancingGenLoadbalancer(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupElasticLoadBalancingGenLoadbalancer.RunSetupAsync(t);

    private Task TeardownElasticLoadBalancingGenLoadbalancer(TestContext t) =>
        GroupElasticLoadBalancingGenLoadbalancer.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteLoadBalancer",
                Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
                Build = b =>
                {
                    var request = new DeleteLoadBalancerRequest();
                    request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteLoadBalancerAsync((DeleteLoadBalancerRequest)request),
            }
        );

    private Task TestElasticLoadBalancingGenLoadbalancerCreateLoadBalancer(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "CreateLoadBalancer", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateLoadBalancer",
            Params = "{\"AvailabilityZones\":[\"us-east-1a\"],\"Listeners\":[{\"InstancePort\":80,\"InstanceProtocol\":\"HTTP\",\"LoadBalancerPort\":80,\"Protocol\":\"HTTP\"}],\"LoadBalancerName\":{\"$name\":\"lb\"}}",
            Build = b =>
            {
                var request = new CreateLoadBalancerRequest();
                request.AvailabilityZones = ["us-east-1a"];
                request.Listeners = [
                    new()
                    {
                        InstancePort = 80,
                        InstanceProtocol = "HTTP",
                        LoadBalancerPort = 80,
                        Protocol = "HTTP",
                    },
                ];
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Name("lb"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateLoadBalancerAsync((CreateLoadBalancerRequest)request),
            Export = new()
            {
                ["loadbalancer.dns"] = "$.DNSName",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.DNSName")
            ),
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{\"LoadBalancerNames\":[{\"$name\":\"lb\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            request.LoadBalancerNames = [
                                b.Bind<string>("LoadBalancerNames", Val.Name("lb")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                        Export = new()
                        {
                            ["loadbalancer.name"] = "$.LoadBalancerDescriptions[0].LoadBalancerName",
                        },
                    },
                    Check.NonEmpty("$.LoadBalancerDescriptions[0].LoadBalancerName")
                )
            ),
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{\"LoadBalancerNames\":[{\"$ref\":\"loadbalancer.name\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            request.LoadBalancerNames = [
                                b.Bind<string>("LoadBalancerNames", Val.Ref("loadbalancer.name")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                    },
                    Check.EqualTo("$.LoadBalancerDescriptions[0].DNSName", Val.Ref("loadbalancer.dns"))
                )
            ),
            Clause.Eventually(30, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                    },
                    "$.LoadBalancerDescriptions",
                    new WhereEntry("$.DNSName", Val.Ref("loadbalancer.dns"))
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerDescribeLoadBalancers(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "DescribeLoadBalancers", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeLoadBalancers",
            Params = "{\"LoadBalancerNames\":[{\"$ref\":\"loadbalancer.name\"}]}",
            Build = b =>
            {
                var request = new DescribeLoadBalancersRequest();
                request.LoadBalancerNames = [
                    b.Bind<string>("LoadBalancerNames", Val.Ref("loadbalancer.name")),
                ];
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.LoadBalancerDescriptions[0].DNSName", Val.Ref("loadbalancer.dns"))
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerConfigureHealthCheck(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "ConfigureHealthCheck", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ConfigureHealthCheck",
            Params = "{\"HealthCheck\":{\"HealthyThreshold\":2,\"Interval\":30,\"Target\":\"TCP:80\",\"Timeout\":5,\"UnhealthyThreshold\":2},\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
            Build = b =>
            {
                var request = new ConfigureHealthCheckRequest();
                request.HealthCheck = new()
                {
                    HealthyThreshold = 2,
                    Interval = 30,
                    Target = "TCP:80",
                    Timeout = 5,
                    UnhealthyThreshold = 2,
                };
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ConfigureHealthCheckAsync((ConfigureHealthCheckRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{\"LoadBalancerNames\":[{\"$ref\":\"loadbalancer.name\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            request.LoadBalancerNames = [
                                b.Bind<string>("LoadBalancerNames", Val.Ref("loadbalancer.name")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                    },
                    Check.EqualTo("$.LoadBalancerDescriptions[0].HealthCheck.Interval", 30)
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerCreateLoadBalancerListeners(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "CreateLoadBalancerListeners", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateLoadBalancerListeners",
            Params = "{\"Listeners\":[{\"InstancePort\":8080,\"InstanceProtocol\":\"TCP\",\"LoadBalancerPort\":8080,\"Protocol\":\"TCP\"}],\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
            Build = b =>
            {
                var request = new CreateLoadBalancerListenersRequest();
                request.Listeners = [
                    new()
                    {
                        InstancePort = 8080,
                        InstanceProtocol = "TCP",
                        LoadBalancerPort = 8080,
                        Protocol = "TCP",
                    },
                ];
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateLoadBalancerListenersAsync((CreateLoadBalancerListenersRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{\"LoadBalancerNames\":[{\"$ref\":\"loadbalancer.name\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            request.LoadBalancerNames = [
                                b.Bind<string>("LoadBalancerNames", Val.Ref("loadbalancer.name")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                    },
                    "$.LoadBalancerDescriptions[0].ListenerDescriptions",
                    new WhereEntry("$.Listener.LoadBalancerPort", 8080)
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerDeleteLoadBalancerListeners(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "DeleteLoadBalancerListeners", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteLoadBalancerListeners",
            Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"LoadBalancerPorts\":[8080]}",
            Build = b =>
            {
                var request = new DeleteLoadBalancerListenersRequest();
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                request.LoadBalancerPorts = [8080];
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteLoadBalancerListenersAsync((DeleteLoadBalancerListenersRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{\"LoadBalancerNames\":[{\"$ref\":\"loadbalancer.name\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            request.LoadBalancerNames = [
                                b.Bind<string>("LoadBalancerNames", Val.Ref("loadbalancer.name")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                    },
                    "$.LoadBalancerDescriptions[0].ListenerDescriptions",
                    new WhereEntry("$.Listener.LoadBalancerPort", 8080)
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerModifyLoadBalancerAttributes(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "ModifyLoadBalancerAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ModifyLoadBalancerAttributes",
            Params = "{\"LoadBalancerAttributes\":{\"CrossZoneLoadBalancing\":{\"Enabled\":true}},\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
            Build = b =>
            {
                var request = new ModifyLoadBalancerAttributesRequest();
                request.LoadBalancerAttributes = new() { CrossZoneLoadBalancing = new() { Enabled = true } };
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ModifyLoadBalancerAttributesAsync((ModifyLoadBalancerAttributesRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancerAttributes",
                        Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancerAttributesRequest();
                            request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancerAttributesAsync((DescribeLoadBalancerAttributesRequest)request),
                    },
                    Check.EqualTo("$.LoadBalancerAttributes.CrossZoneLoadBalancing.Enabled", true)
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerDescribeInstanceHealth(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "DescribeInstanceHealth", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeInstanceHealth",
            Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
            Build = b =>
            {
                var request = new DescribeInstanceHealthRequest();
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeInstanceHealthAsync((DescribeInstanceHealthRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.InstanceStates")
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerCreateLBCookieStickinessPolicy(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "CreateLBCookieStickinessPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateLBCookieStickinessPolicy",
            Params = "{\"CookieExpirationPeriod\":300,\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyName\":{\"$name\":\"lbcookie\"}}",
            Build = b =>
            {
                var request = new CreateLBCookieStickinessPolicyRequest();
                request.CookieExpirationPeriod = 300L;
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                request.PolicyName = b.Bind<string>("PolicyName", Val.Name("lbcookie"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateLBCookieStickinessPolicyAsync((CreateLBCookieStickinessPolicyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancerPolicies",
                        Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyNames\":[{\"$name\":\"lbcookie\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancerPoliciesRequest();
                            request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                            request.PolicyNames = [
                                b.Bind<string>("PolicyNames", Val.Name("lbcookie")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancerPoliciesAsync((DescribeLoadBalancerPoliciesRequest)request),
                    },
                    Check.NonEmpty("$.PolicyDescriptions[0].PolicyName")
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerCreateAppCookieStickinessPolicy(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "CreateAppCookieStickinessPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateAppCookieStickinessPolicy",
            Params = "{\"CookieName\":\"compat-scenario\",\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyName\":{\"$name\":\"appcookie\"}}",
            Build = b =>
            {
                var request = new CreateAppCookieStickinessPolicyRequest();
                request.CookieName = "compat-scenario";
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                request.PolicyName = b.Bind<string>("PolicyName", Val.Name("appcookie"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateAppCookieStickinessPolicyAsync((CreateAppCookieStickinessPolicyRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancerPolicies",
                        Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyNames\":[{\"$name\":\"appcookie\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancerPoliciesRequest();
                            request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                            request.PolicyNames = [
                                b.Bind<string>("PolicyNames", Val.Name("appcookie")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancerPoliciesAsync((DescribeLoadBalancerPoliciesRequest)request),
                    },
                    Check.NonEmpty("$.PolicyDescriptions[0].PolicyName")
                )
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerDeleteLoadBalancer(TestContext t) => GroupElasticLoadBalancingGenLoadbalancer.RunTestAsync(t, "DeleteLoadBalancer", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteLoadBalancer",
            Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
            Build = b =>
            {
                var request = new DeleteLoadBalancerRequest();
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteLoadBalancerAsync((DeleteLoadBalancerRequest)request),
        },
        Assert =
        [
            Clause.Eventually(30, 2000,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "DescribeLoadBalancers",
                        Params = "{\"LoadBalancerNames\":[{\"$ref\":\"loadbalancer.name\"}]}",
                        Build = b =>
                        {
                            var request = new DescribeLoadBalancersRequest();
                            request.LoadBalancerNames = [
                                b.Bind<string>("LoadBalancerNames", Val.Ref("loadbalancer.name")),
                            ];
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                    },
                    new ErrorSpec("AccessPointNotFoundException", "LoadBalancerNotFound"))
            )
        ],
    });

    private Task SetupElasticLoadBalancingGenLoadbalancerpolicy(TestContext t) =>
        GroupElasticLoadBalancingGenLoadbalancerpolicy.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateLoadBalancer",
                Params = "{\"AvailabilityZones\":[\"us-east-1a\"],\"Listeners\":[{\"InstancePort\":80,\"InstanceProtocol\":\"HTTP\",\"LoadBalancerPort\":80,\"Protocol\":\"HTTP\"}],\"LoadBalancerName\":{\"$name\":\"lb\"}}",
                Build = b =>
                {
                    var request = new CreateLoadBalancerRequest();
                    request.AvailabilityZones = ["us-east-1a"];
                    request.Listeners = [
                        new()
                        {
                            InstancePort = 80,
                            InstanceProtocol = "HTTP",
                            LoadBalancerPort = 80,
                            Protocol = "HTTP",
                        },
                    ];
                    request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Name("lb"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateLoadBalancerAsync((CreateLoadBalancerRequest)request),
                Export = new()
                {
                    ["loadbalancer.dns"] = "$.DNSName",
                },
            },
            new ScenarioCall
            {
                Op = "DescribeLoadBalancers",
                Params = "{\"LoadBalancerNames\":[{\"$name\":\"lb\"}]}",
                Build = b =>
                {
                    var request = new DescribeLoadBalancersRequest();
                    request.LoadBalancerNames = [b.Bind<string>("LoadBalancerNames", Val.Name("lb"))];
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DescribeLoadBalancersAsync((DescribeLoadBalancersRequest)request),
                Export = new()
                {
                    ["loadbalancer.name"] = "$.LoadBalancerDescriptions[0].LoadBalancerName",
                },
            }
        );

    private Task TeardownElasticLoadBalancingGenLoadbalancerpolicy(TestContext t) =>
        GroupElasticLoadBalancingGenLoadbalancerpolicy.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteLoadBalancerPolicy",
                Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyName\":{\"$name\":\"policy\"}}",
                Build = b =>
                {
                    var request = new DeleteLoadBalancerPolicyRequest();
                    request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                    request.PolicyName = b.Bind<string>("PolicyName", Val.Name("policy"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteLoadBalancerPolicyAsync((DeleteLoadBalancerPolicyRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteLoadBalancer",
                Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"}}",
                Build = b =>
                {
                    var request = new DeleteLoadBalancerRequest();
                    request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteLoadBalancerAsync((DeleteLoadBalancerRequest)request),
            }
        );

    private Task TestElasticLoadBalancingGenLoadbalancerpolicyCreateLoadBalancerPolicy(TestContext t) => GroupElasticLoadBalancingGenLoadbalancerpolicy.RunTestAsync(t, "CreateLoadBalancerPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateLoadBalancerPolicy",
            Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyAttributes\":[{\"AttributeName\":\"ProxyProtocol\",\"AttributeValue\":\"true\"}],\"PolicyName\":{\"$name\":\"policy\"},\"PolicyTypeName\":\"ProxyProtocolPolicyType\"}",
            Build = b =>
            {
                var request = new CreateLoadBalancerPolicyRequest();
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                request.PolicyAttributes = [
                    new()
                    {
                        AttributeName = "ProxyProtocol",
                        AttributeValue = "true",
                    },
                ];
                request.PolicyName = b.Bind<string>("PolicyName", Val.Name("policy"));
                request.PolicyTypeName = "ProxyProtocolPolicyType";
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateLoadBalancerPolicyAsync((CreateLoadBalancerPolicyRequest)request),
        },
        Assert =
        [
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "DescribeLoadBalancerPolicies",
                    Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyNames\":[{\"$name\":\"policy\"}]}",
                    Build = b =>
                    {
                        var request = new DescribeLoadBalancerPoliciesRequest();
                        request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                        request.PolicyNames = [b.Bind<string>("PolicyNames", Val.Name("policy"))];
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().DescribeLoadBalancerPoliciesAsync((DescribeLoadBalancerPoliciesRequest)request),
                },
                Check.NonEmpty("$.PolicyDescriptions[0].PolicyName")
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerpolicyDescribeLoadBalancerPolicies(TestContext t) => GroupElasticLoadBalancingGenLoadbalancerpolicy.RunTestAsync(t, "DescribeLoadBalancerPolicies", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeLoadBalancerPolicies",
            Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyNames\":[{\"$name\":\"policy\"}]}",
            Build = b =>
            {
                var request = new DescribeLoadBalancerPoliciesRequest();
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                request.PolicyNames = [b.Bind<string>("PolicyNames", Val.Name("policy"))];
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeLoadBalancerPoliciesAsync((DescribeLoadBalancerPoliciesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.PolicyDescriptions[0].PolicyName")
            )
        ],
    });

    private Task TestElasticLoadBalancingGenLoadbalancerpolicyDeleteLoadBalancerPolicy(TestContext t) => GroupElasticLoadBalancingGenLoadbalancerpolicy.RunTestAsync(t, "DeleteLoadBalancerPolicy", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteLoadBalancerPolicy",
            Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyName\":{\"$name\":\"policy\"}}",
            Build = b =>
            {
                var request = new DeleteLoadBalancerPolicyRequest();
                request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                request.PolicyName = b.Bind<string>("PolicyName", Val.Name("policy"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteLoadBalancerPolicyAsync((DeleteLoadBalancerPolicyRequest)request),
        },
        Assert =
        [
            Clause.AbsentByError(
                new ScenarioCall
                {
                    Op = "DescribeLoadBalancerPolicies",
                    Params = "{\"LoadBalancerName\":{\"$ref\":\"loadbalancer.name\"},\"PolicyNames\":[{\"$name\":\"policy\"}]}",
                    Build = b =>
                    {
                        var request = new DescribeLoadBalancerPoliciesRequest();
                        request.LoadBalancerName = b.Bind<string>("LoadBalancerName", Val.Ref("loadbalancer.name"));
                        request.PolicyNames = [b.Bind<string>("PolicyNames", Val.Name("policy"))];
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().DescribeLoadBalancerPoliciesAsync((DescribeLoadBalancerPoliciesRequest)request),
                },
                new ErrorSpec("PolicyNotFoundException", "PolicyNotFound"))
        ],
    });

    private Task SetupElasticLoadBalancingGenProbe(TestContext t) =>
        // No setup steps: an empty phase is a no-op, not a missing one.
        GroupElasticLoadBalancingGenProbe.RunSetupAsync(t);

    private Task TeardownElasticLoadBalancingGenProbe(TestContext t) =>
        // No teardown steps: an empty phase is a no-op, not a missing one.
        GroupElasticLoadBalancingGenProbe.RunTeardownAsync(t);

    private Task TestElasticLoadBalancingGenProbeDescribeAccountLimits(TestContext t) => GroupElasticLoadBalancingGenProbe.RunTestAsync(t, "DescribeAccountLimits", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeAccountLimits",
            Params = "{}",
            Build = b =>
            {
                var request = new DescribeAccountLimitsRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeAccountLimitsAsync((DescribeAccountLimitsRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.Limits")
            )
        ],
    });

    private Task TestElasticLoadBalancingGenProbeDescribeLoadBalancerAttributes(TestContext t) => GroupElasticLoadBalancingGenProbe.RunTestAsync(t, "DescribeLoadBalancerAttributes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeLoadBalancerAttributes",
            Params = "{\"LoadBalancerName\":\"compat-scenario-nonexistent\"}",
            Build = b =>
            {
                var request = new DescribeLoadBalancerAttributesRequest();
                request.LoadBalancerName = "compat-scenario-nonexistent";
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeLoadBalancerAttributesAsync((DescribeLoadBalancerAttributesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.LoadBalancerAttributes")
            )
        ],
    });

    private Task TestElasticLoadBalancingGenProbeDescribeLoadBalancerPolicyTypes(TestContext t) => GroupElasticLoadBalancingGenProbe.RunTestAsync(t, "DescribeLoadBalancerPolicyTypes", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DescribeLoadBalancerPolicyTypes",
            Params = "{}",
            Build = b =>
            {
                var request = new DescribeLoadBalancerPolicyTypesRequest();
                return request;
            },
            SendAsync = async request =>
                await Cl().DescribeLoadBalancerPolicyTypesAsync((DescribeLoadBalancerPolicyTypesRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.IsList("$.PolicyTypeDescriptions")
            )
        ],
    });
}
