// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.AppConfig;
using Amazon.AppConfig.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The authored appconfig-environments groups.</summary>
/// <remarks>
/// Generated from compat/model/authored/appconfig-environments.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosAuthoredAppconfigEnvironments : IServiceGroup
{
    private static readonly ScenarioGroup GroupAppconfigEnvironments = new("appconfig-environments", "compat/model/authored/appconfig-environments.json");

    private readonly Lazy<AmazonAppConfigClient> _client;

    internal ScenariosAuthoredAppconfigEnvironments(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonAppConfigClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonAppConfigClient(credentials, (AmazonAppConfigConfig)configuration),
            new AmazonAppConfigConfig()));
    }

    public string SourceName => "ScenariosAuthoredAppconfigEnvironments";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["appconfig-environments:CreateEnvironment"] = TestAppconfigEnvironmentsCreateEnvironment,
        ["appconfig-environments:GetEnvironment"] = TestAppconfigEnvironmentsGetEnvironment,
        ["appconfig-environments:ListEnvironments"] = TestAppconfigEnvironmentsListEnvironments,
        ["appconfig-environments:UpdateEnvironment"] = TestAppconfigEnvironmentsUpdateEnvironment,
        ["appconfig-environments:DeleteEnvironment"] = TestAppconfigEnvironmentsDeleteEnvironment,
        ["appconfig-environments:GetEnvironmentNotFound"] = TestAppconfigEnvironmentsGetEnvironmentNotFound,
        ["appconfig-environments:ListEnvironmentsApplicationNotFound"] = TestAppconfigEnvironmentsListEnvironmentsApplicationNotFound,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["appconfig-environments"] = SetupAppconfigEnvironments,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["appconfig-environments"] = TeardownAppconfigEnvironments,
    };

    private AmazonAppConfigClient Cl() => _client.Value;

    private Task SetupAppconfigEnvironments(TestContext t) =>
        GroupAppconfigEnvironments.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateApplication",
                Params = "{\"Name\":{\"$name\":\"app\"}}",
                Build = b =>
                {
                    var request = new CreateApplicationRequest();
                    request.Name = b.Bind<string>("Name", Val.Name("app"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateApplicationAsync((CreateApplicationRequest)request),
                Export = new()
                {
                    ["app.id"] = "$.Id",
                },
            }
        );

    private Task TeardownAppconfigEnvironments(TestContext t) =>
        GroupAppconfigEnvironments.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteEnvironment",
                Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                Build = b =>
                {
                    var request = new DeleteEnvironmentRequest();
                    request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                    request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteEnvironmentAsync((DeleteEnvironmentRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteApplication",
                Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                Build = b =>
                {
                    var request = new DeleteApplicationRequest();
                    request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteApplicationAsync((DeleteApplicationRequest)request),
            }
        );

    private Task TestAppconfigEnvironmentsCreateEnvironment(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "CreateEnvironment", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateEnvironment",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"Description\":\"compat environments group\",\"Name\":{\"$name\":\"env\"}}",
            Build = b =>
            {
                var request = new CreateEnvironmentRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.Description = "compat environments group";
                request.Name = b.Bind<string>("Name", Val.Name("env"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateEnvironmentAsync((CreateEnvironmentRequest)request),
            Export = new()
            {
                ["env.id"] = "$.Id",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.ApplicationId", Val.Ref("app.id")),
                Check.NonEmpty("$.Id"),
                Check.EqualTo("$.Name", Val.Name("env")),
                Check.EqualTo("$.State", "READY_FOR_DEPLOYMENT")
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetEnvironment",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                    Build = b =>
                    {
                        var request = new GetEnvironmentRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetEnvironmentAsync((GetEnvironmentRequest)request),
                },
                Check.EqualTo("$.Name", Val.Name("env"))
            )
        ],
    });

    private Task TestAppconfigEnvironmentsGetEnvironment(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "GetEnvironment", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetEnvironment",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
            Build = b =>
            {
                var request = new GetEnvironmentRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetEnvironmentAsync((GetEnvironmentRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Id", Val.Ref("env.id")),
                Check.EqualTo("$.Name", Val.Name("env"))
            )
        ],
    });

    private Task TestAppconfigEnvironmentsListEnvironments(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "ListEnvironments", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListEnvironments",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
            Build = b =>
            {
                var request = new ListEnvironmentsRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListEnvironmentsAsync((ListEnvironmentsRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Items",
                new WhereEntry("$.Id", Val.Ref("env.id")),
                new WhereEntry("$.Name", Val.Name("env"))
            )
        ],
    });

    private Task TestAppconfigEnvironmentsUpdateEnvironment(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "UpdateEnvironment", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateEnvironment",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"Description\":\"updated by compat\",\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
            Build = b =>
            {
                var request = new UpdateEnvironmentRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.Description = "updated by compat";
                request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateEnvironmentAsync((UpdateEnvironmentRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Description", "updated by compat")
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetEnvironment",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                    Build = b =>
                    {
                        var request = new GetEnvironmentRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetEnvironmentAsync((GetEnvironmentRequest)request),
                },
                Check.EqualTo("$.Description", "updated by compat"),
                Check.EqualTo("$.Name", Val.Name("env"))
            )
        ],
    });

    private Task TestAppconfigEnvironmentsDeleteEnvironment(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "DeleteEnvironment", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteEnvironment",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
            Build = b =>
            {
                var request = new DeleteEnvironmentRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteEnvironmentAsync((DeleteEnvironmentRequest)request),
        },
        Assert =
        [
            Clause.AbsentByError(
                new ScenarioCall
                {
                    Op = "GetEnvironment",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                    Build = b =>
                    {
                        var request = new GetEnvironmentRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        request.EnvironmentId = b.Bind<string>("EnvironmentId", Val.Ref("env.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetEnvironmentAsync((GetEnvironmentRequest)request),
                },
                new ErrorSpec("ResourceNotFoundException", "ResourceNotFoundException")),
            Clause.AbsentFromList(
                new ScenarioCall
                {
                    Op = "ListEnvironments",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                    Build = b =>
                    {
                        var request = new ListEnvironmentsRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().ListEnvironmentsAsync((ListEnvironmentsRequest)request),
                },
                "$.Items",
                new WhereEntry("$.Id", Val.Ref("env.id"))
            )
        ],
    });

    private Task TestAppconfigEnvironmentsGetEnvironmentNotFound(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "GetEnvironmentNotFound", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetEnvironment",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":\"zzzzzzz\"}",
            Build = b =>
            {
                var request = new GetEnvironmentRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.EnvironmentId = "zzzzzzz";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetEnvironmentAsync((GetEnvironmentRequest)request),
        },
        Assert =
        [
            Clause.ErrorCode(new ErrorSpec("ResourceNotFoundException", "ResourceNotFoundException"))
        ],
    });

    private Task TestAppconfigEnvironmentsListEnvironmentsApplicationNotFound(TestContext t) => GroupAppconfigEnvironments.RunTestAsync(t, "ListEnvironmentsApplicationNotFound", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListEnvironments",
            Params = "{\"ApplicationId\":\"zzzzzzz\"}",
            Build = b =>
            {
                var request = new ListEnvironmentsRequest();
                request.ApplicationId = "zzzzzzz";
                return request;
            },
            SendAsync = async request =>
                await Cl().ListEnvironmentsAsync((ListEnvironmentsRequest)request),
        },
        Assert =
        [
            Clause.ErrorCode(new ErrorSpec("ResourceNotFoundException", "ResourceNotFoundException"))
        ],
    });
}
