// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.AppConfig;
using Amazon.AppConfig.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The authored appconfig-configuration-profiles groups.</summary>
/// <remarks>
/// Generated from compat/model/authored/appconfig-configuration-profiles.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosAuthoredAppconfigConfigurationProfiles : IServiceGroup
{
    private static readonly ScenarioGroup GroupAppconfigConfigurationProfilesShadow = new("appconfig-configuration-profiles-shadow", "compat/model/authored/appconfig-configuration-profiles.json");

    private readonly Lazy<AmazonAppConfigClient> _client;

    internal ScenariosAuthoredAppconfigConfigurationProfiles(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonAppConfigClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonAppConfigClient(credentials, (AmazonAppConfigConfig)configuration),
            new AmazonAppConfigConfig()));
    }

    public string SourceName => "ScenariosAuthoredAppconfigConfigurationProfiles";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["appconfig-configuration-profiles-shadow:CreateConfigurationProfile"] = TestAppconfigConfigurationProfilesShadowCreateConfigurationProfile,
        ["appconfig-configuration-profiles-shadow:GetConfigurationProfile"] = TestAppconfigConfigurationProfilesShadowGetConfigurationProfile,
        ["appconfig-configuration-profiles-shadow:ListConfigurationProfiles"] = TestAppconfigConfigurationProfilesShadowListConfigurationProfiles,
        ["appconfig-configuration-profiles-shadow:ListConfigurationProfilesByType"] = TestAppconfigConfigurationProfilesShadowListConfigurationProfilesByType,
        ["appconfig-configuration-profiles-shadow:UpdateConfigurationProfile"] = TestAppconfigConfigurationProfilesShadowUpdateConfigurationProfile,
        ["appconfig-configuration-profiles-shadow:DeleteConfigurationProfile"] = TestAppconfigConfigurationProfilesShadowDeleteConfigurationProfile,
        ["appconfig-configuration-profiles-shadow:GetConfigurationProfileNotFound"] = TestAppconfigConfigurationProfilesShadowGetConfigurationProfileNotFound,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["appconfig-configuration-profiles-shadow"] = SetupAppconfigConfigurationProfilesShadow,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["appconfig-configuration-profiles-shadow"] = TeardownAppconfigConfigurationProfilesShadow,
    };

    private AmazonAppConfigClient Cl() => _client.Value;

    private Task SetupAppconfigConfigurationProfilesShadow(TestContext t) =>
        GroupAppconfigConfigurationProfilesShadow.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateApplication",
                Params = "{\"Name\":{\"$name\":\"app\"}}",
                Build = b =>
                {
                    var request = new CreateApplicationRequest();
                    request.Name = b.Bind<string>("Name", Val.Name("app"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateApplicationAsync((CreateApplicationRequest)request),
                Export = new()
                {
                    ["app.id"] = "$.Id",
                },
            },
            new ScenarioCall
            {
                Op = "CreateConfigurationProfile",
                Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"LocationUri\":\"hosted\",\"Name\":{\"$name\":\"flags\"},\"Type\":\"AWS.AppConfig.FeatureFlags\"}",
                Build = b =>
                {
                    var request = new CreateConfigurationProfileRequest();
                    request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                    request.LocationUri = "hosted";
                    request.Name = b.Bind<string>("Name", Val.Name("flags"));
                    request.Type = "AWS.AppConfig.FeatureFlags";
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateConfigurationProfileAsync((CreateConfigurationProfileRequest)request),
                Export = new()
                {
                    ["flags.id"] = "$.Id",
                },
            }
        );

    private Task TeardownAppconfigConfigurationProfilesShadow(TestContext t) =>
        GroupAppconfigConfigurationProfilesShadow.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "DeleteConfigurationProfile",
                Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
                Build = b =>
                {
                    var request = new DeleteConfigurationProfileRequest();
                    request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                    request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteConfigurationProfileAsync((DeleteConfigurationProfileRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteConfigurationProfile",
                Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"flags.id\"}}",
                Build = b =>
                {
                    var request = new DeleteConfigurationProfileRequest();
                    request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                    request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("flags.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteConfigurationProfileAsync((DeleteConfigurationProfileRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteApplication",
                Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                Build = b =>
                {
                    var request = new DeleteApplicationRequest();
                    request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteApplicationAsync((DeleteApplicationRequest)request),
            }
        );

    private Task TestAppconfigConfigurationProfilesShadowCreateConfigurationProfile(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "CreateConfigurationProfile", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateConfigurationProfile",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"Description\":\"compat configuration profiles group\",\"LocationUri\":\"hosted\",\"Name\":{\"$name\":\"prof\"},\"Type\":\"AWS.Freeform\"}",
            Build = b =>
            {
                var request = new CreateConfigurationProfileRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.Description = "compat configuration profiles group";
                request.LocationUri = "hosted";
                request.Name = b.Bind<string>("Name", Val.Name("prof"));
                request.Type = "AWS.Freeform";
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateConfigurationProfileAsync((CreateConfigurationProfileRequest)request),
            Export = new()
            {
                ["prof.id"] = "$.Id",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Id"),
                Check.EqualTo("$.LocationUri", "hosted"),
                Check.EqualTo("$.Name", Val.Name("prof"))
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetConfigurationProfile",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
                    Build = b =>
                    {
                        var request = new GetConfigurationProfileRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetConfigurationProfileAsync((GetConfigurationProfileRequest)request),
                },
                Check.EqualTo("$.Name", Val.Name("prof")),
                Check.EqualTo("$.Type", "AWS.Freeform")
            )
        ],
    });

    private Task TestAppconfigConfigurationProfilesShadowGetConfigurationProfile(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "GetConfigurationProfile", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetConfigurationProfile",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
            Build = b =>
            {
                var request = new GetConfigurationProfileRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetConfigurationProfileAsync((GetConfigurationProfileRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Id", Val.Ref("prof.id")),
                Check.EqualTo("$.Name", Val.Name("prof"))
            )
        ],
    });

    private Task TestAppconfigConfigurationProfilesShadowListConfigurationProfiles(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "ListConfigurationProfiles", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListConfigurationProfiles",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
            Build = b =>
            {
                var request = new ListConfigurationProfilesRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListConfigurationProfilesAsync((ListConfigurationProfilesRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Items",
                new WhereEntry("$.Id", Val.Ref("prof.id")),
                new WhereEntry("$.Name", Val.Name("prof"))
            )
        ],
    });

    private Task TestAppconfigConfigurationProfilesShadowListConfigurationProfilesByType(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "ListConfigurationProfilesByType", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListConfigurationProfiles",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"Type\":\"AWS.AppConfig.FeatureFlags\"}",
            Build = b =>
            {
                var request = new ListConfigurationProfilesRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.Type = "AWS.AppConfig.FeatureFlags";
                return request;
            },
            SendAsync = async request =>
                await Cl().ListConfigurationProfilesAsync((ListConfigurationProfilesRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Items",
                new WhereEntry("$.Id", Val.Ref("flags.id"))
            ),
            Clause.AbsentFromList(
                null,
                "$.Items",
                new WhereEntry("$.Id", Val.Ref("prof.id"))
            )
        ],
    });

    private Task TestAppconfigConfigurationProfilesShadowUpdateConfigurationProfile(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "UpdateConfigurationProfile", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "UpdateConfigurationProfile",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"},\"Description\":\"updated by compat\"}",
            Build = b =>
            {
                var request = new UpdateConfigurationProfileRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                request.Description = "updated by compat";
                return request;
            },
            SendAsync = async request =>
                await Cl().UpdateConfigurationProfileAsync((UpdateConfigurationProfileRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Description", "updated by compat")
            ),
            Clause.Readback(
                new ScenarioCall
                {
                    Op = "GetConfigurationProfile",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
                    Build = b =>
                    {
                        var request = new GetConfigurationProfileRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetConfigurationProfileAsync((GetConfigurationProfileRequest)request),
                },
                Check.EqualTo("$.Description", "updated by compat"),
                Check.EqualTo("$.Name", Val.Name("prof"))
            )
        ],
    });

    private Task TestAppconfigConfigurationProfilesShadowDeleteConfigurationProfile(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "DeleteConfigurationProfile", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteConfigurationProfile",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
            Build = b =>
            {
                var request = new DeleteConfigurationProfileRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteConfigurationProfileAsync((DeleteConfigurationProfileRequest)request),
        },
        Assert =
        [
            Clause.AbsentByError(
                new ScenarioCall
                {
                    Op = "GetConfigurationProfile",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
                    Build = b =>
                    {
                        var request = new GetConfigurationProfileRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        request.ConfigurationProfileId = b.Bind<string>("ConfigurationProfileId", Val.Ref("prof.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().GetConfigurationProfileAsync((GetConfigurationProfileRequest)request),
                },
                new ErrorSpec("ResourceNotFoundException", "ResourceNotFoundException")),
            Clause.AbsentFromList(
                new ScenarioCall
                {
                    Op = "ListConfigurationProfiles",
                    Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                    Build = b =>
                    {
                        var request = new ListConfigurationProfilesRequest();
                        request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                        return request;
                    },
                    SendAsync = async request =>
                        await Cl().ListConfigurationProfilesAsync((ListConfigurationProfilesRequest)request),
                },
                "$.Items",
                new WhereEntry("$.Id", Val.Ref("prof.id"))
            )
        ],
    });

    private Task TestAppconfigConfigurationProfilesShadowGetConfigurationProfileNotFound(TestContext t) => GroupAppconfigConfigurationProfilesShadow.RunTestAsync(t, "GetConfigurationProfileNotFound", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetConfigurationProfile",
            Params = "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":\"zzzzzzz\"}",
            Build = b =>
            {
                var request = new GetConfigurationProfileRequest();
                request.ApplicationId = b.Bind<string>("ApplicationId", Val.Ref("app.id"));
                request.ConfigurationProfileId = "zzzzzzz";
                return request;
            },
            SendAsync = async request =>
                await Cl().GetConfigurationProfileAsync((GetConfigurationProfileRequest)request),
        },
        Assert =
        [
            Clause.ErrorCode(new ErrorSpec("ResourceNotFoundException", "ResourceNotFoundException"))
        ],
    });
}
