// Code generated by cmd/compatgen; DO NOT EDIT.

using Amazon.IdentityManagement;
using Amazon.IdentityManagement.Model;
using OvercastCompat.Clients;
using OvercastCompat.Harness;
using OvercastCompat.Scenario;

namespace OvercastCompat.Groups;

/// <summary>The authored iam-groups groups.</summary>
/// <remarks>
/// Generated from compat/model/authored/iam-groups.json by cmd/compatgen. The semantics live in
/// OvercastCompat.Scenario; this file is the data and the typed SDK calls.
/// </remarks>
internal sealed class ScenariosAuthoredIamGroups : IServiceGroup
{
    private static readonly ScenarioGroup GroupIamGroupsShadow = new("iam-groups-shadow", "compat/model/authored/iam-groups.json");

    private readonly Lazy<AmazonIdentityManagementServiceClient> _client;

    internal ScenariosAuthoredIamGroups(AwsClients clients)
    {
        // A generated group builds its own client from the configuration the
        // suite's hand-written groups share, rather than adding an accessor to
        // AwsClients for every service the generator learns to cover. Nothing
        // else about the client differs, and Lazy<T> builds it once however
        // many of the group's tests run concurrently.
        _client = new Lazy<AmazonIdentityManagementServiceClient>(() => clients.CreateClient(
            (credentials, configuration) => new AmazonIdentityManagementServiceClient(credentials, (AmazonIdentityManagementServiceConfig)configuration),
            new AmazonIdentityManagementServiceConfig()));
    }

    public string SourceName => "ScenariosAuthoredIamGroups";

    public IReadOnlyDictionary<string, TestFn> Impls() => new Dictionary<string, TestFn>(StringComparer.Ordinal)
    {
        ["iam-groups-shadow:CreateGroup"] = TestIamGroupsShadowCreateGroup,
        ["iam-groups-shadow:AddUserToGroup"] = TestIamGroupsShadowAddUserToGroup,
        ["iam-groups-shadow:ListGroupsForUser"] = TestIamGroupsShadowListGroupsForUser,
        ["iam-groups-shadow:RemoveUserFromGroup"] = TestIamGroupsShadowRemoveUserFromGroup,
        ["iam-groups-shadow:GetGroup"] = TestIamGroupsShadowGetGroup,
        ["iam-groups-shadow:DeleteGroup"] = TestIamGroupsShadowDeleteGroup,
    };

    public IReadOnlyDictionary<string, SetupFn> Setups() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["iam-groups-shadow"] = SetupIamGroupsShadow,
    };

    public IReadOnlyDictionary<string, SetupFn> Teardowns() => new Dictionary<string, SetupFn>(StringComparer.Ordinal)
    {
        ["iam-groups-shadow"] = TeardownIamGroupsShadow,
    };

    private AmazonIdentityManagementServiceClient Cl() => _client.Value;

    private Task SetupIamGroupsShadow(TestContext t) =>
        GroupIamGroupsShadow.RunSetupAsync(t,
            new ScenarioCall
            {
                Op = "CreateUser",
                Params = "{\"UserName\":{\"$name\":\"user\"}}",
                Build = b =>
                {
                    var request = new CreateUserRequest();
                    request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().CreateUserAsync((CreateUserRequest)request),
            }
        );

    private Task TeardownIamGroupsShadow(TestContext t) =>
        GroupIamGroupsShadow.RunTeardownAsync(t,
            new ScenarioCall
            {
                Op = "RemoveUserFromGroup",
                Params = "{\"GroupName\":{\"$name\":\"group\"},\"UserName\":{\"$name\":\"user\"}}",
                Build = b =>
                {
                    var request = new RemoveUserFromGroupRequest();
                    request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                    request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().RemoveUserFromGroupAsync((RemoveUserFromGroupRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteGroup",
                Params = "{\"GroupName\":{\"$name\":\"group\"}}",
                Build = b =>
                {
                    var request = new DeleteGroupRequest();
                    request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteGroupAsync((DeleteGroupRequest)request),
            },
            new ScenarioCall
            {
                Op = "DeleteUser",
                Params = "{\"UserName\":{\"$name\":\"user\"}}",
                Build = b =>
                {
                    var request = new DeleteUserRequest();
                    request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                    return request;
                },
                SendAsync = async request =>
                    await Cl().DeleteUserAsync((DeleteUserRequest)request),
            }
        );

    private Task TestIamGroupsShadowCreateGroup(TestContext t) => GroupIamGroupsShadow.RunTestAsync(t, "CreateGroup", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "CreateGroup",
            Params = "{\"GroupName\":{\"$name\":\"group\"}}",
            Build = b =>
            {
                var request = new CreateGroupRequest();
                request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                return request;
            },
            SendAsync = async request =>
                await Cl().CreateGroupAsync((CreateGroupRequest)request),
            Export = new()
            {
                ["group.id"] = "$.Group.GroupId",
            },
        },
        Assert =
        [
            Clause.ResponseField(
                Check.NonEmpty("$.Group.Arn"),
                Check.NonEmpty("$.Group.GroupId"),
                Check.EqualTo("$.Group.GroupName", Val.Name("group"))
            ),
            Clause.Eventually(6, 500,
                Clause.Readback(
                    new ScenarioCall
                    {
                        Op = "GetGroup",
                        Params = "{\"GroupName\":{\"$name\":\"group\"}}",
                        Build = b =>
                        {
                            var request = new GetGroupRequest();
                            request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetGroupAsync((GetGroupRequest)request),
                    },
                    Check.EqualTo("$.Group.GroupId", Val.Ref("group.id")),
                    Check.EqualTo("$.Group.GroupName", Val.Name("group"))
                )
            )
        ],
    });

    private Task TestIamGroupsShadowAddUserToGroup(TestContext t) => GroupIamGroupsShadow.RunTestAsync(t, "AddUserToGroup", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "AddUserToGroup",
            Params = "{\"GroupName\":{\"$name\":\"group\"},\"UserName\":{\"$name\":\"user\"}}",
            Build = b =>
            {
                var request = new AddUserToGroupRequest();
                request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                return request;
            },
            SendAsync = async request =>
                await Cl().AddUserToGroupAsync((AddUserToGroupRequest)request),
        },
        Assert =
        [
            Clause.Eventually(6, 500,
                Clause.ListContains(
                    new ScenarioCall
                    {
                        Op = "GetGroup",
                        Params = "{\"GroupName\":{\"$name\":\"group\"}}",
                        Build = b =>
                        {
                            var request = new GetGroupRequest();
                            request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetGroupAsync((GetGroupRequest)request),
                    },
                    "$.Users",
                    new WhereEntry("$.UserName", Val.Name("user"))
                )
            )
        ],
    });

    private Task TestIamGroupsShadowListGroupsForUser(TestContext t) => GroupIamGroupsShadow.RunTestAsync(t, "ListGroupsForUser", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "ListGroupsForUser",
            Params = "{\"UserName\":{\"$name\":\"user\"}}",
            Build = b =>
            {
                var request = new ListGroupsForUserRequest();
                request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                return request;
            },
            SendAsync = async request =>
                await Cl().ListGroupsForUserAsync((ListGroupsForUserRequest)request),
        },
        Assert =
        [
            Clause.ListContains(
                null,
                "$.Groups",
                new WhereEntry("$.GroupId", Val.Ref("group.id")),
                new WhereEntry("$.GroupName", Val.Name("group"))
            )
        ],
    });

    private Task TestIamGroupsShadowRemoveUserFromGroup(TestContext t) => GroupIamGroupsShadow.RunTestAsync(t, "RemoveUserFromGroup", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "RemoveUserFromGroup",
            Params = "{\"GroupName\":{\"$name\":\"group\"},\"UserName\":{\"$name\":\"user\"}}",
            Build = b =>
            {
                var request = new RemoveUserFromGroupRequest();
                request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                return request;
            },
            SendAsync = async request =>
                await Cl().RemoveUserFromGroupAsync((RemoveUserFromGroupRequest)request),
        },
        Assert =
        [
            Clause.Eventually(6, 500,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "ListGroupsForUser",
                        Params = "{\"UserName\":{\"$name\":\"user\"}}",
                        Build = b =>
                        {
                            var request = new ListGroupsForUserRequest();
                            request.UserName = b.Bind<string>("UserName", Val.Name("user"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().ListGroupsForUserAsync((ListGroupsForUserRequest)request),
                    },
                    "$.Groups",
                    new WhereEntry("$.GroupName", Val.Name("group"))
                )
            ),
            Clause.Eventually(6, 500,
                Clause.AbsentFromList(
                    new ScenarioCall
                    {
                        Op = "GetGroup",
                        Params = "{\"GroupName\":{\"$name\":\"group\"}}",
                        Build = b =>
                        {
                            var request = new GetGroupRequest();
                            request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetGroupAsync((GetGroupRequest)request),
                    },
                    "$.Users",
                    new WhereEntry("$.UserName", Val.Name("user"))
                )
            )
        ],
    });

    private Task TestIamGroupsShadowGetGroup(TestContext t) => GroupIamGroupsShadow.RunTestAsync(t, "GetGroup", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "GetGroup",
            Params = "{\"GroupName\":{\"$name\":\"group\"}}",
            Build = b =>
            {
                var request = new GetGroupRequest();
                request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                return request;
            },
            SendAsync = async request =>
                await Cl().GetGroupAsync((GetGroupRequest)request),
        },
        Assert =
        [
            Clause.ResponseField(
                Check.EqualTo("$.Group.GroupId", Val.Ref("group.id")),
                Check.EqualTo("$.Group.GroupName", Val.Name("group")),
                Check.IsList("$.Users")
            )
        ],
    });

    private Task TestIamGroupsShadowDeleteGroup(TestContext t) => GroupIamGroupsShadow.RunTestAsync(t, "DeleteGroup", new ScenarioTest
    {
        Call = new ScenarioCall
        {
            Op = "DeleteGroup",
            Params = "{\"GroupName\":{\"$name\":\"group\"}}",
            Build = b =>
            {
                var request = new DeleteGroupRequest();
                request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                return request;
            },
            SendAsync = async request =>
                await Cl().DeleteGroupAsync((DeleteGroupRequest)request),
        },
        Assert =
        [
            Clause.Eventually(6, 500,
                Clause.AbsentByError(
                    new ScenarioCall
                    {
                        Op = "GetGroup",
                        Params = "{\"GroupName\":{\"$name\":\"group\"}}",
                        Build = b =>
                        {
                            var request = new GetGroupRequest();
                            request.GroupName = b.Bind<string>("GroupName", Val.Name("group"));
                            return request;
                        },
                        SendAsync = async request =>
                            await Cl().GetGroupAsync((GetGroupRequest)request),
                    },
                    new ErrorSpec("NoSuchEntityException", "NoSuchEntity"))
            )
        ],
    });
}
