// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.appconfig.AppConfigClient;
import software.amazon.awssdk.services.appconfig.model.CreateApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.CreateConfigurationProfileRequest;
import software.amazon.awssdk.services.appconfig.model.CreateEnvironmentRequest;
import software.amazon.awssdk.services.appconfig.model.DeleteApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.DeleteConfigurationProfileRequest;
import software.amazon.awssdk.services.appconfig.model.DeleteEnvironmentRequest;
import software.amazon.awssdk.services.appconfig.model.GetDeploymentRequest;
import software.amazon.awssdk.services.appconfig.model.ListDeploymentsRequest;
import software.amazon.awssdk.services.appconfig.model.StartDeploymentRequest;
import software.amazon.awssdk.services.appconfig.model.StopDeploymentRequest;

/**
 * The authored appconfig-deployments groups.
 *
 * <p>Generated from compat/model/authored/appconfig-deployments.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosAuthoredAppconfigDeploymentsGen implements ServiceGroup {

    private static final Group GROUP_APPCONFIG_DEPLOYMENTS_SHADOW =
            new Group("appconfig-deployments-shadow", "compat/model/authored/appconfig-deployments.json");

    private final AwsClients clients;
    private volatile AppConfigClient client;

    public ScenariosAuthoredAppconfigDeploymentsGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/authored-appconfig-deployments";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("appconfig-deployments-shadow:StartDeployment", this::testAppconfigDeploymentsShadowStartDeployment),
                Map.entry("appconfig-deployments-shadow:GetDeployment", this::testAppconfigDeploymentsShadowGetDeployment),
                Map.entry("appconfig-deployments-shadow:ListDeployments", this::testAppconfigDeploymentsShadowListDeployments),
                Map.entry("appconfig-deployments-shadow:StopDeployment", this::testAppconfigDeploymentsShadowStopDeployment));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("appconfig-deployments-shadow", this::setupAppconfigDeploymentsShadow));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("appconfig-deployments-shadow", this::teardownAppconfigDeploymentsShadow));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private AppConfigClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(AppConfigClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupAppconfigDeploymentsShadow(TestContext t) {
        GROUP_APPCONFIG_DEPLOYMENTS_SHADOW.runSetup(t,
                new Call("CreateApplication", "{\"Name\":{\"$name\":\"app\"}}",
                        b -> CreateApplicationRequest.builder()
                                .name(b.string("Name", Values.name("app")))
                                .build(),
                        r -> cl().createApplication((CreateApplicationRequest) r))
                        .export("app.id", "$.Id"),
                new Call("CreateEnvironment", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"Name\":{\"$name\":\"env\"}}",
                        b -> CreateEnvironmentRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .name(b.string("Name", Values.name("env")))
                                .build(),
                        r -> cl().createEnvironment((CreateEnvironmentRequest) r))
                        .export("env.id", "$.Id"),
                new Call("CreateConfigurationProfile", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"LocationUri\":\"hosted\",\"Name\":{\"$name\":\"prof\"}}",
                        b -> CreateConfigurationProfileRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .locationUri("hosted")
                                .name(b.string("Name", Values.name("prof")))
                                .build(),
                        r -> cl().createConfigurationProfile((CreateConfigurationProfileRequest) r))
                        .export("prof.id", "$.Id"));
    }

    private void teardownAppconfigDeploymentsShadow(TestContext t) {
        GROUP_APPCONFIG_DEPLOYMENTS_SHADOW.runTeardown(t,
                new Call("DeleteConfigurationProfile", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"}}",
                        b -> DeleteConfigurationProfileRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .configurationProfileId(b.string("ConfigurationProfileId", Values.ref("prof.id")))
                                .build(),
                        r -> cl().deleteConfigurationProfile((DeleteConfigurationProfileRequest) r)),
                new Call("DeleteEnvironment", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                        b -> DeleteEnvironmentRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .environmentId(b.string("EnvironmentId", Values.ref("env.id")))
                                .build(),
                        r -> cl().deleteEnvironment((DeleteEnvironmentRequest) r)),
                new Call("DeleteApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                        b -> DeleteApplicationRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .build(),
                        r -> cl().deleteApplication((DeleteApplicationRequest) r)));
    }

    private void testAppconfigDeploymentsShadowStartDeployment(TestContext t) {
        GROUP_APPCONFIG_DEPLOYMENTS_SHADOW.runTest(t, "StartDeployment",
                new Call("StartDeployment", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"ConfigurationProfileId\":{\"$ref\":\"prof.id\"},\"ConfigurationVersion\":\"1\",\"DeploymentStrategyId\":\"AppConfig.AllAtOnce\",\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                        b -> StartDeploymentRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .configurationProfileId(b.string("ConfigurationProfileId", Values.ref("prof.id")))
                                .configurationVersion("1")
                                .deploymentStrategyId("AppConfig.AllAtOnce")
                                .environmentId(b.string("EnvironmentId", Values.ref("env.id")))
                                .build(),
                        r -> cl().startDeployment((StartDeploymentRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.DeploymentNumber")
                        )
                ));
    }

    private void testAppconfigDeploymentsShadowGetDeployment(TestContext t) {
        GROUP_APPCONFIG_DEPLOYMENTS_SHADOW.runTest(t, "GetDeployment",
                new Call("GetDeployment", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"DeploymentNumber\":1,\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                        b -> GetDeploymentRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .deploymentNumber(1)
                                .environmentId(b.string("EnvironmentId", Values.ref("env.id")))
                                .build(),
                        r -> cl().getDeployment((GetDeploymentRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.DeploymentNumber", 1.0)
                        )
                ));
    }

    private void testAppconfigDeploymentsShadowListDeployments(TestContext t) {
        GROUP_APPCONFIG_DEPLOYMENTS_SHADOW.runTest(t, "ListDeployments",
                new Call("ListDeployments", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                        b -> ListDeploymentsRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .environmentId(b.string("EnvironmentId", Values.ref("env.id")))
                                .build(),
                        r -> cl().listDeployments((ListDeploymentsRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.isList("$.Items")
                        )
                ));
    }

    private void testAppconfigDeploymentsShadowStopDeployment(TestContext t) {
        GROUP_APPCONFIG_DEPLOYMENTS_SHADOW.runTest(t, "StopDeployment",
                new Call("StopDeployment", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"DeploymentNumber\":1,\"EnvironmentId\":{\"$ref\":\"env.id\"}}",
                        b -> StopDeploymentRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .deploymentNumber(1)
                                .environmentId(b.string("EnvironmentId", Values.ref("env.id")))
                                .build(),
                        r -> cl().stopDeployment((StopDeploymentRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.State")
                        )
                ));
    }
}
