// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.ErrorSpec;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.appconfig.AppConfigClient;
import software.amazon.awssdk.services.appconfig.model.CreateApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.DeleteApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.ListTagsForResourceRequest;
import software.amazon.awssdk.services.appconfig.model.TagResourceRequest;
import software.amazon.awssdk.services.appconfig.model.UntagResourceRequest;

/**
 * The authored appconfig-tags groups.
 *
 * <p>Generated from compat/model/authored/appconfig-tags.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosAuthoredAppconfigTagsGen implements ServiceGroup {

    private static final Group GROUP_APPCONFIG_TAGS_SHADOW =
            new Group("appconfig-tags-shadow", "compat/model/authored/appconfig-tags.json");

    private final AwsClients clients;
    private volatile AppConfigClient client;

    public ScenariosAuthoredAppconfigTagsGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/authored-appconfig-tags";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("appconfig-tags-shadow:CreateApplicationWithTags", this::testAppconfigTagsShadowCreateApplicationWithTags),
                Map.entry("appconfig-tags-shadow:TagResource", this::testAppconfigTagsShadowTagResource),
                Map.entry("appconfig-tags-shadow:ListTagsForResource", this::testAppconfigTagsShadowListTagsForResource),
                Map.entry("appconfig-tags-shadow:UntagResource", this::testAppconfigTagsShadowUntagResource),
                Map.entry("appconfig-tags-shadow:ListTagsForResourceNotFound", this::testAppconfigTagsShadowListTagsForResourceNotFound));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("appconfig-tags-shadow", this::setupAppconfigTagsShadow));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("appconfig-tags-shadow", this::teardownAppconfigTagsShadow));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private AppConfigClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(AppConfigClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupAppconfigTagsShadow(TestContext t) {
        // No setup steps: an empty phase is a no-op, not a missing one.
        GROUP_APPCONFIG_TAGS_SHADOW.runSetup(t);
    }

    private void teardownAppconfigTagsShadow(TestContext t) {
        GROUP_APPCONFIG_TAGS_SHADOW.runTeardown(t,
                new Call("DeleteApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                        b -> DeleteApplicationRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .build(),
                        r -> cl().deleteApplication((DeleteApplicationRequest) r)));
    }

    private void testAppconfigTagsShadowCreateApplicationWithTags(TestContext t) {
        GROUP_APPCONFIG_TAGS_SHADOW.runTest(t, "CreateApplicationWithTags",
                new Call("CreateApplication", "{\"Name\":{\"$name\":\"app\"},\"Tags\":{\"Owner\":\"compat\",\"Team\":\"platform\"}}",
                        b -> CreateApplicationRequest.builder()
                                .name(b.string("Name", Values.name("app")))
                                .tags(Map.of("Owner", "compat", "Team", "platform"))
                                .build(),
                        r -> cl().createApplication((CreateApplicationRequest) r))
                        .export("app.id", "$.Id"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.Id")
                        ),
                        Clause.readback(
                                new Call("ListTagsForResource", "{\"ResourceArn\":{\"$concat\":[\"arn:aws:appconfig:us-east-1:000000000000:application/\",{\"$ref\":\"app.id\"}]}}",
                                        b -> ListTagsForResourceRequest.builder()
                                                .resourceArn(b.string("ResourceArn", Values.concat("arn:aws:appconfig:us-east-1:000000000000:application/", Values.ref("app.id"))))
                                                .build(),
                                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                Check.equalTo("$.Tags.Owner", "compat"),
                                Check.equalTo("$.Tags.Team", "platform")
                        )
                ));
    }

    private void testAppconfigTagsShadowTagResource(TestContext t) {
        GROUP_APPCONFIG_TAGS_SHADOW.runTest(t, "TagResource",
                new Call("TagResource", "{\"ResourceArn\":{\"$concat\":[\"arn:aws:appconfig:us-east-1:000000000000:application/\",{\"$ref\":\"app.id\"}]},\"Tags\":{\"Owner\":\"compat-updated\",\"Stage\":\"beta\"}}",
                        b -> TagResourceRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.concat("arn:aws:appconfig:us-east-1:000000000000:application/", Values.ref("app.id"))))
                                .tags(Map.of("Owner", "compat-updated", "Stage", "beta"))
                                .build(),
                        r -> cl().tagResource((TagResourceRequest) r)),
                List.of(
                        Clause.readback(
                                new Call("ListTagsForResource", "{\"ResourceArn\":{\"$concat\":[\"arn:aws:appconfig:us-east-1:000000000000:application/\",{\"$ref\":\"app.id\"}]}}",
                                        b -> ListTagsForResourceRequest.builder()
                                                .resourceArn(b.string("ResourceArn", Values.concat("arn:aws:appconfig:us-east-1:000000000000:application/", Values.ref("app.id"))))
                                                .build(),
                                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                Check.equalTo("$.Tags.Owner", "compat-updated"),
                                Check.equalTo("$.Tags.Stage", "beta"),
                                Check.equalTo("$.Tags.Team", "platform")
                        )
                ));
    }

    private void testAppconfigTagsShadowListTagsForResource(TestContext t) {
        GROUP_APPCONFIG_TAGS_SHADOW.runTest(t, "ListTagsForResource",
                new Call("ListTagsForResource", "{\"ResourceArn\":{\"$concat\":[\"arn:aws:appconfig:us-east-1:000000000000:application/\",{\"$ref\":\"app.id\"}]}}",
                        b -> ListTagsForResourceRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.concat("arn:aws:appconfig:us-east-1:000000000000:application/", Values.ref("app.id"))))
                                .build(),
                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Tags.Owner", "compat-updated"),
                                Check.equalTo("$.Tags.Stage", "beta"),
                                Check.equalTo("$.Tags.Team", "platform")
                        )
                ));
    }

    private void testAppconfigTagsShadowUntagResource(TestContext t) {
        GROUP_APPCONFIG_TAGS_SHADOW.runTest(t, "UntagResource",
                new Call("UntagResource", "{\"ResourceArn\":{\"$concat\":[\"arn:aws:appconfig:us-east-1:000000000000:application/\",{\"$ref\":\"app.id\"}]},\"TagKeys\":[\"Team\"]}",
                        b -> UntagResourceRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.concat("arn:aws:appconfig:us-east-1:000000000000:application/", Values.ref("app.id"))))
                                .tagKeys(List.of("Team"))
                                .build(),
                        r -> cl().untagResource((UntagResourceRequest) r)),
                List.of(
                        Clause.readback(
                                new Call("ListTagsForResource", "{\"ResourceArn\":{\"$concat\":[\"arn:aws:appconfig:us-east-1:000000000000:application/\",{\"$ref\":\"app.id\"}]}}",
                                        b -> ListTagsForResourceRequest.builder()
                                                .resourceArn(b.string("ResourceArn", Values.concat("arn:aws:appconfig:us-east-1:000000000000:application/", Values.ref("app.id"))))
                                                .build(),
                                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                                Check.equalTo("$.Tags.Owner", "compat-updated"),
                                Check.missing("$.Tags.Team")
                        )
                ));
    }

    private void testAppconfigTagsShadowListTagsForResourceNotFound(TestContext t) {
        GROUP_APPCONFIG_TAGS_SHADOW.runTest(t, "ListTagsForResourceNotFound",
                new Call("ListTagsForResource", "{\"ResourceArn\":\"arn:aws:appconfig:us-east-1:000000000000:application/zzzzzzz\"}",
                        b -> ListTagsForResourceRequest.builder()
                                .resourceArn("arn:aws:appconfig:us-east-1:000000000000:application/zzzzzzz")
                                .build(),
                        r -> cl().listTagsForResource((ListTagsForResourceRequest) r)),
                List.of(
                        Clause.errorCode(ErrorSpec.of("ResourceNotFoundException", "ResourceNotFoundException"))
                ));
    }
}
