// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.ErrorSpec;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import io.overcast.compat.scenario.Where;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.cognitoidentityprovider.CognitoIdentityProviderClient;
import software.amazon.awssdk.services.cognitoidentityprovider.model.AdminCreateUserRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.AdminDeleteUserRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.CreateUserPoolClientRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.CreateUserPoolRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.DeleteUserPoolClientRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.DeleteUserPoolRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.DescribeUserPoolRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.ListUserPoolClientsRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.ListUserPoolsRequest;
import software.amazon.awssdk.services.cognitoidentityprovider.model.ListUsersRequest;

/**
 * The authored cognito-userpools groups.
 *
 * <p>Generated from compat/model/authored/cognito-userpools.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosAuthoredCognitoUserpoolsGen implements ServiceGroup {

    private static final Group GROUP_COGNITO_USERPOOLS =
            new Group("cognito-userpools", "compat/model/authored/cognito-userpools.json");

    private final AwsClients clients;
    private volatile CognitoIdentityProviderClient client;

    public ScenariosAuthoredCognitoUserpoolsGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/authored-cognito-userpools";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("cognito-userpools:CreateUserPool", this::testCognitoUserpoolsCreateUserPool),
                Map.entry("cognito-userpools:DescribeUserPool", this::testCognitoUserpoolsDescribeUserPool),
                Map.entry("cognito-userpools:ListUserPools", this::testCognitoUserpoolsListUserPools),
                Map.entry("cognito-userpools:CreateUserPoolClient", this::testCognitoUserpoolsCreateUserPoolClient),
                Map.entry("cognito-userpools:ListUserPoolClients", this::testCognitoUserpoolsListUserPoolClients),
                Map.entry("cognito-userpools:AdminCreateUser", this::testCognitoUserpoolsAdminCreateUser),
                Map.entry("cognito-userpools:ListUsers", this::testCognitoUserpoolsListUsers),
                Map.entry("cognito-userpools:AdminDeleteUser", this::testCognitoUserpoolsAdminDeleteUser),
                Map.entry("cognito-userpools:DeleteUserPool", this::testCognitoUserpoolsDeleteUserPool));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("cognito-userpools", this::setupCognitoUserpools));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("cognito-userpools", this::teardownCognitoUserpools));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private CognitoIdentityProviderClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(CognitoIdentityProviderClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupCognitoUserpools(TestContext t) {
        // No setup steps: an empty phase is a no-op, not a missing one.
        GROUP_COGNITO_USERPOOLS.runSetup(t);
    }

    private void teardownCognitoUserpools(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTeardown(t,
                new Call("AdminDeleteUser", "{\"UserPoolId\":{\"$ref\":\"pool.id\"},\"Username\":{\"$name\":\"user\"}}",
                        b -> AdminDeleteUserRequest.builder()
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .username(b.string("Username", Values.name("user")))
                                .build(),
                        r -> cl().adminDeleteUser((AdminDeleteUserRequest) r)),
                new Call("DeleteUserPoolClient", "{\"ClientId\":{\"$ref\":\"client.id\"},\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> DeleteUserPoolClientRequest.builder()
                                .clientId(b.string("ClientId", Values.ref("client.id")))
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().deleteUserPoolClient((DeleteUserPoolClientRequest) r)),
                new Call("DeleteUserPool", "{\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> DeleteUserPoolRequest.builder()
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().deleteUserPool((DeleteUserPoolRequest) r)));
    }

    private void testCognitoUserpoolsCreateUserPool(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "CreateUserPool",
                new Call("CreateUserPool", "{\"PoolName\":{\"$name\":\"pool\"}}",
                        b -> CreateUserPoolRequest.builder()
                                .poolName(b.string("PoolName", Values.name("pool")))
                                .build(),
                        r -> cl().createUserPool((CreateUserPoolRequest) r))
                        .export("pool.id", "$.UserPool.Id"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.UserPool.Id"),
                                Check.equalTo("$.UserPool.Name", Values.name("pool"))
                        )
                ));
    }

    private void testCognitoUserpoolsDescribeUserPool(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "DescribeUserPool",
                new Call("DescribeUserPool", "{\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> DescribeUserPoolRequest.builder()
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().describeUserPool((DescribeUserPoolRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.UserPool.Id", Values.ref("pool.id")),
                                Check.equalTo("$.UserPool.Name", Values.name("pool"))
                        )
                ));
    }

    private void testCognitoUserpoolsListUserPools(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "ListUserPools",
                new Call("ListUserPools", "{\"MaxResults\":60}",
                        b -> ListUserPoolsRequest.builder()
                                .maxResults(60)
                                .build(),
                        r -> cl().listUserPools((ListUserPoolsRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.UserPools",
                                Where.of("$.Id", Values.ref("pool.id"))
                        )
                ));
    }

    private void testCognitoUserpoolsCreateUserPoolClient(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "CreateUserPoolClient",
                new Call("CreateUserPoolClient", "{\"ClientName\":{\"$name\":\"client\"},\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> CreateUserPoolClientRequest.builder()
                                .clientName(b.string("ClientName", Values.name("client")))
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().createUserPoolClient((CreateUserPoolClientRequest) r))
                        .export("client.id", "$.UserPoolClient.ClientId"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.UserPoolClient.ClientId")
                        )
                ));
    }

    private void testCognitoUserpoolsListUserPoolClients(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "ListUserPoolClients",
                new Call("ListUserPoolClients", "{\"MaxResults\":60,\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> ListUserPoolClientsRequest.builder()
                                .maxResults(60)
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().listUserPoolClients((ListUserPoolClientsRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.UserPoolClients",
                                Where.of("$.ClientId", Values.ref("client.id"))
                        )
                ));
    }

    private void testCognitoUserpoolsAdminCreateUser(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "AdminCreateUser",
                new Call("AdminCreateUser", "{\"TemporaryPassword\":\"Passw0rd!#\",\"UserPoolId\":{\"$ref\":\"pool.id\"},\"Username\":{\"$name\":\"user\"}}",
                        b -> AdminCreateUserRequest.builder()
                                .temporaryPassword("Passw0rd!#")
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .username(b.string("Username", Values.name("user")))
                                .build(),
                        r -> cl().adminCreateUser((AdminCreateUserRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.User.Username", Values.name("user"))
                        )
                ));
    }

    private void testCognitoUserpoolsListUsers(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "ListUsers",
                new Call("ListUsers", "{\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> ListUsersRequest.builder()
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().listUsers((ListUsersRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Users",
                                Where.of("$.Username", Values.name("user"))
                        )
                ));
    }

    private void testCognitoUserpoolsAdminDeleteUser(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "AdminDeleteUser",
                new Call("AdminDeleteUser", "{\"UserPoolId\":{\"$ref\":\"pool.id\"},\"Username\":{\"$name\":\"user\"}}",
                        b -> AdminDeleteUserRequest.builder()
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .username(b.string("Username", Values.name("user")))
                                .build(),
                        r -> cl().adminDeleteUser((AdminDeleteUserRequest) r)),
                List.of(
                        Clause.eventually(10, 500,
                                Clause.absentFromList(
                                        new Call("ListUsers", "{\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                                                b -> ListUsersRequest.builder()
                                                        .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                                        .build(),
                                                r -> cl().listUsers((ListUsersRequest) r)),
                                        "$.Users",
                                        Where.of("$.Username", Values.name("user"))
                                ))
                ));
    }

    private void testCognitoUserpoolsDeleteUserPool(TestContext t) {
        GROUP_COGNITO_USERPOOLS.runTest(t, "DeleteUserPool",
                new Call("DeleteUserPool", "{\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                        b -> DeleteUserPoolRequest.builder()
                                .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                .build(),
                        r -> cl().deleteUserPool((DeleteUserPoolRequest) r)),
                List.of(
                        Clause.eventually(10, 500,
                                Clause.absentByError(
                                        new Call("DescribeUserPool", "{\"UserPoolId\":{\"$ref\":\"pool.id\"}}",
                                                b -> DescribeUserPoolRequest.builder()
                                                        .userPoolId(b.string("UserPoolId", Values.ref("pool.id")))
                                                        .build(),
                                                r -> cl().describeUserPool((DescribeUserPoolRequest) r)),
                                        ErrorSpec.of("ResourceNotFoundException", "ResourceNotFoundException"))),
                        Clause.eventually(10, 500,
                                Clause.absentFromList(
                                        new Call("ListUserPools", "{\"MaxResults\":60}",
                                                b -> ListUserPoolsRequest.builder()
                                                        .maxResults(60)
                                                        .build(),
                                                r -> cl().listUserPools((ListUserPoolsRequest) r)),
                                        "$.UserPools",
                                        Where.of("$.Id", Values.ref("pool.id"))
                                ))
                ));
    }
}
