// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.ErrorSpec;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import io.overcast.compat.scenario.Where;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.appconfig.AppConfigClient;
import software.amazon.awssdk.services.appconfig.model.CreateApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.DeleteApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.GetApplicationRequest;
import software.amazon.awssdk.services.appconfig.model.ListApplicationsRequest;
import software.amazon.awssdk.services.appconfig.model.UpdateApplicationRequest;

/**
 * The authored appconfig-applications groups.
 *
 * <p>Generated from compat/model/authored/appconfig-applications.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosAuthoredAppconfigApplicationsGen implements ServiceGroup {

    private static final Group GROUP_APPCONFIG_APPLICATIONS_SHADOW =
            new Group("appconfig-applications-shadow", "compat/model/authored/appconfig-applications.json");

    private final AwsClients clients;
    private volatile AppConfigClient client;

    public ScenariosAuthoredAppconfigApplicationsGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/authored-appconfig-applications";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("appconfig-applications-shadow:CreateApplication", this::testAppconfigApplicationsShadowCreateApplication),
                Map.entry("appconfig-applications-shadow:GetApplication", this::testAppconfigApplicationsShadowGetApplication),
                Map.entry("appconfig-applications-shadow:ListApplications", this::testAppconfigApplicationsShadowListApplications),
                Map.entry("appconfig-applications-shadow:UpdateApplication", this::testAppconfigApplicationsShadowUpdateApplication),
                Map.entry("appconfig-applications-shadow:DeleteApplication", this::testAppconfigApplicationsShadowDeleteApplication),
                Map.entry("appconfig-applications-shadow:GetApplicationNotFound", this::testAppconfigApplicationsShadowGetApplicationNotFound),
                Map.entry("appconfig-applications-shadow:ListApplicationsInvalidToken", this::testAppconfigApplicationsShadowListApplicationsInvalidToken));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("appconfig-applications-shadow", this::setupAppconfigApplicationsShadow));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("appconfig-applications-shadow", this::teardownAppconfigApplicationsShadow));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private AppConfigClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(AppConfigClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupAppconfigApplicationsShadow(TestContext t) {
        // No setup steps: an empty phase is a no-op, not a missing one.
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runSetup(t);
    }

    private void teardownAppconfigApplicationsShadow(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTeardown(t,
                new Call("DeleteApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                        b -> DeleteApplicationRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .build(),
                        r -> cl().deleteApplication((DeleteApplicationRequest) r)));
    }

    private void testAppconfigApplicationsShadowCreateApplication(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "CreateApplication",
                new Call("CreateApplication", "{\"Description\":\"compat applications group\",\"Name\":{\"$name\":\"app\"}}",
                        b -> CreateApplicationRequest.builder()
                                .description("compat applications group")
                                .name(b.string("Name", Values.name("app")))
                                .build(),
                        r -> cl().createApplication((CreateApplicationRequest) r))
                        .export("app.id", "$.Id"),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.Id"),
                                Check.equalTo("$.Name", Values.name("app"))
                        ),
                        Clause.readback(
                                new Call("GetApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                                        b -> GetApplicationRequest.builder()
                                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                                .build(),
                                        r -> cl().getApplication((GetApplicationRequest) r)),
                                Check.equalTo("$.Description", "compat applications group"),
                                Check.equalTo("$.Name", Values.name("app"))
                        )
                ));
    }

    private void testAppconfigApplicationsShadowGetApplication(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "GetApplication",
                new Call("GetApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                        b -> GetApplicationRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .build(),
                        r -> cl().getApplication((GetApplicationRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Id", Values.ref("app.id")),
                                Check.equalTo("$.Name", Values.name("app"))
                        )
                ));
    }

    private void testAppconfigApplicationsShadowListApplications(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "ListApplications",
                new Call("ListApplications", "{}",
                        b -> ListApplicationsRequest.builder()
                                .build(),
                        r -> cl().listApplications((ListApplicationsRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Items",
                                Where.of("$.Id", Values.ref("app.id")),
                                Where.of("$.Name", Values.name("app"))
                        )
                ));
    }

    private void testAppconfigApplicationsShadowUpdateApplication(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "UpdateApplication",
                new Call("UpdateApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"},\"Description\":\"updated by compat\"}",
                        b -> UpdateApplicationRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .description("updated by compat")
                                .build(),
                        r -> cl().updateApplication((UpdateApplicationRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Description", "updated by compat")
                        ),
                        Clause.readback(
                                new Call("GetApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                                        b -> GetApplicationRequest.builder()
                                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                                .build(),
                                        r -> cl().getApplication((GetApplicationRequest) r)),
                                Check.equalTo("$.Description", "updated by compat"),
                                Check.equalTo("$.Name", Values.name("app"))
                        )
                ));
    }

    private void testAppconfigApplicationsShadowDeleteApplication(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "DeleteApplication",
                new Call("DeleteApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                        b -> DeleteApplicationRequest.builder()
                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                .build(),
                        r -> cl().deleteApplication((DeleteApplicationRequest) r)),
                List.of(
                        Clause.absentByError(
                                new Call("GetApplication", "{\"ApplicationId\":{\"$ref\":\"app.id\"}}",
                                        b -> GetApplicationRequest.builder()
                                                .applicationId(b.string("ApplicationId", Values.ref("app.id")))
                                                .build(),
                                        r -> cl().getApplication((GetApplicationRequest) r)),
                                ErrorSpec.of("ResourceNotFoundException", "ResourceNotFoundException")),
                        Clause.absentFromList(
                                new Call("ListApplications", "{}",
                                        b -> ListApplicationsRequest.builder()
                                                .build(),
                                        r -> cl().listApplications((ListApplicationsRequest) r)),
                                "$.Items",
                                Where.of("$.Id", Values.ref("app.id"))
                        )
                ));
    }

    private void testAppconfigApplicationsShadowGetApplicationNotFound(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "GetApplicationNotFound",
                new Call("GetApplication", "{\"ApplicationId\":\"zzzzzzz\"}",
                        b -> GetApplicationRequest.builder()
                                .applicationId("zzzzzzz")
                                .build(),
                        r -> cl().getApplication((GetApplicationRequest) r)),
                List.of(
                        Clause.errorCode(ErrorSpec.of("ResourceNotFoundException", "ResourceNotFoundException"))
                ));
    }

    private void testAppconfigApplicationsShadowListApplicationsInvalidToken(TestContext t) {
        GROUP_APPCONFIG_APPLICATIONS_SHADOW.runTest(t, "ListApplicationsInvalidToken",
                new Call("ListApplications", "{\"MaxResults\":1,\"NextToken\":\"compat-not-a-real-token\"}",
                        b -> ListApplicationsRequest.builder()
                                .maxResults(1)
                                .nextToken("compat-not-a-real-token")
                                .build(),
                        r -> cl().listApplications((ListApplicationsRequest) r)),
                List.of(
                        Clause.errorCode(ErrorSpec.of("BadRequestException", "BadRequestException"))
                ));
    }
}
