// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import io.overcast.compat.scenario.Where;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.kinesis.KinesisClient;
import software.amazon.awssdk.services.kinesis.model.AddTagsToStreamRequest;
import software.amazon.awssdk.services.kinesis.model.CreateStreamRequest;
import software.amazon.awssdk.services.kinesis.model.DeleteStreamRequest;
import software.amazon.awssdk.services.kinesis.model.DescribeStreamRequest;
import software.amazon.awssdk.services.kinesis.model.DescribeStreamSummaryRequest;
import software.amazon.awssdk.services.kinesis.model.ListStreamsRequest;
import software.amazon.awssdk.services.kinesis.model.ListTagsForStreamRequest;

/**
 * The authored kinesis-streams groups.
 *
 * <p>Generated from compat/model/authored/kinesis-streams.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosAuthoredKinesisStreamsGen implements ServiceGroup {

    private static final Group GROUP_KINESIS_STREAMS =
            new Group("kinesis-streams", "compat/model/authored/kinesis-streams.json");

    private final AwsClients clients;
    private volatile KinesisClient client;

    public ScenariosAuthoredKinesisStreamsGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/authored-kinesis-streams";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("kinesis-streams:CreateStream", this::testKinesisStreamsCreateStream),
                Map.entry("kinesis-streams:DescribeStream", this::testKinesisStreamsDescribeStream),
                Map.entry("kinesis-streams:DescribeStreamSummary", this::testKinesisStreamsDescribeStreamSummary),
                Map.entry("kinesis-streams:ListStreams", this::testKinesisStreamsListStreams),
                Map.entry("kinesis-streams:AddTagsToStream", this::testKinesisStreamsAddTagsToStream),
                Map.entry("kinesis-streams:ListTagsForStream", this::testKinesisStreamsListTagsForStream),
                Map.entry("kinesis-streams:DeleteStream", this::testKinesisStreamsDeleteStream));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("kinesis-streams", this::setupKinesisStreams));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("kinesis-streams", this::teardownKinesisStreams));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private KinesisClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(KinesisClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupKinesisStreams(TestContext t) {
        GROUP_KINESIS_STREAMS.runSetup(t,
                new Call("CreateStream", "{\"ShardCount\":1,\"StreamName\":{\"$name\":\"s\"}}",
                        b -> CreateStreamRequest.builder()
                                .shardCount(1)
                                .streamName(b.string("StreamName", Values.name("s")))
                                .build(),
                        r -> cl().createStream((CreateStreamRequest) r)));
    }

    private void teardownKinesisStreams(TestContext t) {
        GROUP_KINESIS_STREAMS.runTeardown(t,
                new Call("DeleteStream", "{\"StreamName\":{\"$name\":\"created\"}}",
                        b -> DeleteStreamRequest.builder()
                                .streamName(b.string("StreamName", Values.name("created")))
                                .build(),
                        r -> cl().deleteStream((DeleteStreamRequest) r)),
                new Call("DeleteStream", "{\"StreamName\":{\"$name\":\"s\"}}",
                        b -> DeleteStreamRequest.builder()
                                .streamName(b.string("StreamName", Values.name("s")))
                                .build(),
                        r -> cl().deleteStream((DeleteStreamRequest) r)));
    }

    private void testKinesisStreamsCreateStream(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "CreateStream",
                new Call("CreateStream", "{\"ShardCount\":1,\"StreamName\":{\"$name\":\"created\"}}",
                        b -> CreateStreamRequest.builder()
                                .shardCount(1)
                                .streamName(b.string("StreamName", Values.name("created")))
                                .build(),
                        r -> cl().createStream((CreateStreamRequest) r)),
                List.of(
                        Clause.eventually(30, 500,
                                Clause.readback(
                                        new Call("DescribeStreamSummary", "{\"StreamName\":{\"$name\":\"created\"}}",
                                                b -> DescribeStreamSummaryRequest.builder()
                                                        .streamName(b.string("StreamName", Values.name("created")))
                                                        .build(),
                                                r -> cl().describeStreamSummary((DescribeStreamSummaryRequest) r)),
                                        Check.nonEmpty("$.StreamDescriptionSummary.StreamARN"),
                                        Check.equalTo("$.StreamDescriptionSummary.StreamName", Values.name("created")),
                                        Check.equalTo("$.StreamDescriptionSummary.StreamStatus", "ACTIVE")
                                )),
                        Clause.listContains(
                                new Call("ListStreams", "{}",
                                        b -> ListStreamsRequest.builder()
                                                .build(),
                                        r -> cl().listStreams((ListStreamsRequest) r)),
                                "$.StreamNames",
                                Where.of("$", Values.name("created"))
                        )
                ));
    }

    private void testKinesisStreamsDescribeStream(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "DescribeStream",
                new Call("DescribeStream", "{\"StreamName\":{\"$name\":\"s\"}}",
                        b -> DescribeStreamRequest.builder()
                                .streamName(b.string("StreamName", Values.name("s")))
                                .build(),
                        r -> cl().describeStream((DescribeStreamRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.StreamDescription.StreamARN"),
                                Check.equalTo("$.StreamDescription.StreamName", Values.name("s"))
                        ),
                        Clause.eventually(30, 500,
                                Clause.readback(
                                        new Call("DescribeStream", "{\"StreamName\":{\"$name\":\"s\"}}",
                                                b -> DescribeStreamRequest.builder()
                                                        .streamName(b.string("StreamName", Values.name("s")))
                                                        .build(),
                                                r -> cl().describeStream((DescribeStreamRequest) r)),
                                        Check.nonEmpty("$.StreamDescription.Shards[0].ShardId"),
                                        Check.equalTo("$.StreamDescription.StreamStatus", "ACTIVE")
                                ))
                ));
    }

    private void testKinesisStreamsDescribeStreamSummary(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "DescribeStreamSummary",
                new Call("DescribeStreamSummary", "{\"StreamName\":{\"$name\":\"s\"}}",
                        b -> DescribeStreamSummaryRequest.builder()
                                .streamName(b.string("StreamName", Values.name("s")))
                                .build(),
                        r -> cl().describeStreamSummary((DescribeStreamSummaryRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.nonEmpty("$.StreamDescriptionSummary.StreamARN"),
                                Check.equalTo("$.StreamDescriptionSummary.StreamName", Values.name("s"))
                        ),
                        Clause.eventually(30, 500,
                                Clause.readback(
                                        new Call("DescribeStreamSummary", "{\"StreamName\":{\"$name\":\"s\"}}",
                                                b -> DescribeStreamSummaryRequest.builder()
                                                        .streamName(b.string("StreamName", Values.name("s")))
                                                        .build(),
                                                r -> cl().describeStreamSummary((DescribeStreamSummaryRequest) r)),
                                        Check.equalTo("$.StreamDescriptionSummary.OpenShardCount", 1.0),
                                        Check.equalTo("$.StreamDescriptionSummary.StreamStatus", "ACTIVE")
                                ))
                ));
    }

    private void testKinesisStreamsListStreams(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "ListStreams",
                new Call("ListStreams", "{}",
                        b -> ListStreamsRequest.builder()
                                .build(),
                        r -> cl().listStreams((ListStreamsRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.StreamNames",
                                Where.of("$", Values.name("s"))
                        )
                ));
    }

    private void testKinesisStreamsAddTagsToStream(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "AddTagsToStream",
                new Call("AddTagsToStream", "{\"StreamName\":{\"$name\":\"s\"},\"Tags\":{\"env\":\"compat\",\"project\":\"overcast\"}}",
                        b -> AddTagsToStreamRequest.builder()
                                .streamName(b.string("StreamName", Values.name("s")))
                                .tags(Map.of("env", "compat", "project", "overcast"))
                                .build(),
                        r -> cl().addTagsToStream((AddTagsToStreamRequest) r)),
                List.of(
                        Clause.listContains(
                                new Call("ListTagsForStream", "{\"StreamName\":{\"$name\":\"s\"}}",
                                        b -> ListTagsForStreamRequest.builder()
                                                .streamName(b.string("StreamName", Values.name("s")))
                                                .build(),
                                        r -> cl().listTagsForStream((ListTagsForStreamRequest) r)),
                                "$.Tags",
                                Where.of("$.Key", "env"),
                                Where.of("$.Value", "compat")
                        ),
                        Clause.listContains(
                                new Call("ListTagsForStream", "{\"StreamName\":{\"$name\":\"s\"}}",
                                        b -> ListTagsForStreamRequest.builder()
                                                .streamName(b.string("StreamName", Values.name("s")))
                                                .build(),
                                        r -> cl().listTagsForStream((ListTagsForStreamRequest) r)),
                                "$.Tags",
                                Where.of("$.Key", "project"),
                                Where.of("$.Value", "overcast")
                        )
                ));
    }

    private void testKinesisStreamsListTagsForStream(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "ListTagsForStream",
                new Call("ListTagsForStream", "{\"StreamName\":{\"$name\":\"s\"}}",
                        b -> ListTagsForStreamRequest.builder()
                                .streamName(b.string("StreamName", Values.name("s")))
                                .build(),
                        r -> cl().listTagsForStream((ListTagsForStreamRequest) r)),
                List.of(
                        Clause.listContains(
                                null,
                                "$.Tags",
                                Where.of("$.Key", "env"),
                                Where.of("$.Value", "compat")
                        ),
                        Clause.listContains(
                                null,
                                "$.Tags",
                                Where.of("$.Key", "project"),
                                Where.of("$.Value", "overcast")
                        )
                ));
    }

    private void testKinesisStreamsDeleteStream(TestContext t) {
        GROUP_KINESIS_STREAMS.runTest(t, "DeleteStream",
                new Call("DeleteStream", "{\"StreamName\":{\"$name\":\"created\"}}",
                        b -> DeleteStreamRequest.builder()
                                .streamName(b.string("StreamName", Values.name("created")))
                                .build(),
                        r -> cl().deleteStream((DeleteStreamRequest) r)),
                List.of(
                        Clause.eventually(20, 500,
                                Clause.absentFromList(
                                        new Call("ListStreams", "{}",
                                                b -> ListStreamsRequest.builder()
                                                        .build(),
                                                r -> cl().listStreams((ListStreamsRequest) r)),
                                        "$.StreamNames",
                                        Where.of("$", Values.name("created"))
                                ))
                ));
    }
}
