// Code generated by cmd/compatgen; DO NOT EDIT.

package io.overcast.compat.groups;

import io.overcast.compat.clients.AwsClients;
import io.overcast.compat.harness.TestContext;
import io.overcast.compat.harness.TestFn;
import io.overcast.compat.scenario.Call;
import io.overcast.compat.scenario.Check;
import io.overcast.compat.scenario.Clause;
import io.overcast.compat.scenario.Group;
import io.overcast.compat.scenario.Values;
import java.util.List;
import java.util.Map;
import software.amazon.awssdk.services.backup.BackupClient;
import software.amazon.awssdk.services.backup.model.CreateBackupVaultRequest;
import software.amazon.awssdk.services.backup.model.DeleteBackupVaultRequest;
import software.amazon.awssdk.services.backup.model.ListTagsRequest;
import software.amazon.awssdk.services.backup.model.TagResourceRequest;
import software.amazon.awssdk.services.backup.model.UntagResourceRequest;

/**
 * The authored backup-tags groups.
 *
 * <p>Generated from compat/model/authored/backup-tags.json by cmd/compatgen. The semantics live in
 * {@code io.overcast.compat.scenario}; this file is the data and the typed SDK
 * calls.
 */
public final class ScenariosAuthoredBackupTagsGen implements ServiceGroup {

    private static final Group GROUP_BACKUP_TAGS =
            new Group("backup-tags", "compat/model/authored/backup-tags.json");

    private final AwsClients clients;
    private volatile BackupClient client;

    public ScenariosAuthoredBackupTagsGen(AwsClients clients) {
        this.clients = clients;
    }

    @Override
    public String sourceName() {
        return "scenarios/authored-backup-tags";
    }

    @Override
    public Map<String, TestFn> impls() {
        return Map.ofEntries(
                Map.entry("backup-tags:TagResource", this::testBackupTagsTagResource),
                Map.entry("backup-tags:ListTags", this::testBackupTagsListTags),
                Map.entry("backup-tags:UntagResource", this::testBackupTagsUntagResource));
    }

    @Override
    public Map<String, TestFn> setups() {
        return Map.ofEntries(
                Map.entry("backup-tags", this::setupBackupTags));
    }

    @Override
    public Map<String, TestFn> teardowns() {
        return Map.ofEntries(
                Map.entry("backup-tags", this::teardownBackupTags));
    }

    /**
     * This service's client, built once from the endpoint, region and credentials
     * the suite's hand-written groups share. A generated group configures its own
     * rather than adding an accessor to AwsClients for every service the generator
     * learns to cover; nothing else about the client differs.
     */
    private BackupClient cl() {
        if (client == null) {
            synchronized (this) {
                if (client == null) {
                    client = clients.configure(BackupClient.builder()).build();
                }
            }
        }
        return client;
    }

    private void setupBackupTags(TestContext t) {
        GROUP_BACKUP_TAGS.runSetup(t,
                new Call("CreateBackupVault", "{\"BackupVaultName\":{\"$name\":\"vault\"}}",
                        b -> CreateBackupVaultRequest.builder()
                                .backupVaultName(b.string("BackupVaultName", Values.name("vault")))
                                .build(),
                        r -> cl().createBackupVault((CreateBackupVaultRequest) r))
                        .export("vault.arn", "$.BackupVaultArn"));
    }

    private void teardownBackupTags(TestContext t) {
        GROUP_BACKUP_TAGS.runTeardown(t,
                new Call("UntagResource", "{\"ResourceArn\":{\"$ref\":\"vault.arn\"},\"TagKeyList\":[\"oc-compat\"]}",
                        b -> UntagResourceRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.ref("vault.arn")))
                                .tagKeyList(List.of("oc-compat"))
                                .build(),
                        r -> cl().untagResource((UntagResourceRequest) r)),
                new Call("DeleteBackupVault", "{\"BackupVaultName\":{\"$name\":\"vault\"}}",
                        b -> DeleteBackupVaultRequest.builder()
                                .backupVaultName(b.string("BackupVaultName", Values.name("vault")))
                                .build(),
                        r -> cl().deleteBackupVault((DeleteBackupVaultRequest) r)));
    }

    private void testBackupTagsTagResource(TestContext t) {
        GROUP_BACKUP_TAGS.runTest(t, "TagResource",
                new Call("TagResource", "{\"ResourceArn\":{\"$ref\":\"vault.arn\"},\"Tags\":{\"oc-compat\":{\"$name\":\"vault\"}}}",
                        b -> TagResourceRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.ref("vault.arn")))
                                .tags(Map.of("oc-compat", b.string("Tags", Values.name("vault"))))
                                .build(),
                        r -> cl().tagResource((TagResourceRequest) r)),
                List.of(
                        Clause.readback(
                                new Call("ListTags", "{\"ResourceArn\":{\"$ref\":\"vault.arn\"}}",
                                        b -> ListTagsRequest.builder()
                                                .resourceArn(b.string("ResourceArn", Values.ref("vault.arn")))
                                                .build(),
                                        r -> cl().listTags((ListTagsRequest) r)),
                                Check.equalTo("$.Tags.oc-compat", Values.name("vault"))
                        )
                ));
    }

    private void testBackupTagsListTags(TestContext t) {
        GROUP_BACKUP_TAGS.runTest(t, "ListTags",
                new Call("ListTags", "{\"ResourceArn\":{\"$ref\":\"vault.arn\"}}",
                        b -> ListTagsRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.ref("vault.arn")))
                                .build(),
                        r -> cl().listTags((ListTagsRequest) r)),
                List.of(
                        Clause.responseField(
                                Check.equalTo("$.Tags.oc-compat", Values.name("vault"))
                        )
                ));
    }

    private void testBackupTagsUntagResource(TestContext t) {
        GROUP_BACKUP_TAGS.runTest(t, "UntagResource",
                new Call("UntagResource", "{\"ResourceArn\":{\"$ref\":\"vault.arn\"},\"TagKeyList\":[\"oc-compat\"]}",
                        b -> UntagResourceRequest.builder()
                                .resourceArn(b.string("ResourceArn", Values.ref("vault.arn")))
                                .tagKeyList(List.of("oc-compat"))
                                .build(),
                        r -> cl().untagResource((UntagResourceRequest) r)),
                List.of(
                        Clause.readback(
                                new Call("ListTags", "{\"ResourceArn\":{\"$ref\":\"vault.arn\"}}",
                                        b -> ListTagsRequest.builder()
                                                .resourceArn(b.string("ResourceArn", Values.ref("vault.arn")))
                                                .build(),
                                        r -> cl().listTags((ListTagsRequest) r)),
                                Check.missing("$.Tags.oc-compat")
                        )
                ));
    }
}
