// Code generated by cmd/compatgen; DO NOT EDIT.

package groups

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/appconfig"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/clients"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/harness"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/scenario"
)

// ScenariosAuthoredAppconfigEnvironments returns the authored appconfig-environments groups.
//
// Generated from compat/model/authored/appconfig-environments.json by cmd/compatgen.
// The semantics live in internal/scenario; this file is the data and the
// typed SDK calls.
func ScenariosAuthoredAppconfigEnvironments(c *clients.Clients) ServiceGroup {
	g := &authoredAppconfigEnvironmentsScenarios{c: c}
	return ServiceGroup{
		Name: "scenarios/authored-appconfig-environments",
		Impls: map[string]harness.TestFn{
			"appconfig-environments:CreateEnvironment":                   g.testAppconfigEnvironmentsCreateEnvironment,
			"appconfig-environments:GetEnvironment":                      g.testAppconfigEnvironmentsGetEnvironment,
			"appconfig-environments:ListEnvironments":                    g.testAppconfigEnvironmentsListEnvironments,
			"appconfig-environments:UpdateEnvironment":                   g.testAppconfigEnvironmentsUpdateEnvironment,
			"appconfig-environments:DeleteEnvironment":                   g.testAppconfigEnvironmentsDeleteEnvironment,
			"appconfig-environments:GetEnvironmentNotFound":              g.testAppconfigEnvironmentsGetEnvironmentNotFound,
			"appconfig-environments:ListEnvironmentsApplicationNotFound": g.testAppconfigEnvironmentsListEnvironmentsApplicationNotFound,
		},
		Setup: map[string]func(context.Context, *harness.TestContext) error{
			"appconfig-environments": g.setupAppconfigEnvironments,
		},
		Teardown: map[string]func(context.Context, *harness.TestContext) error{
			"appconfig-environments": g.teardownAppconfigEnvironments,
		},
	}
}

type authoredAppconfigEnvironmentsScenarios struct {
	c      *clients.Clients
	once   sync.Once
	client *appconfig.Client
}

// cl builds this service's client once, from the config the suite's
// hand-written groups share. A generated group builds its own rather than
// adding an accessor to internal/clients for every service the generator
// learns to cover; nothing else about the client differs.
func (g *authoredAppconfigEnvironmentsScenarios) cl() *appconfig.Client {
	g.once.Do(func() { g.client = appconfig.NewFromConfig(g.c.Config()) })
	return g.client
}

var groupAppconfigEnvironments = scenario.Group{Name: "appconfig-environments", File: "compat/model/authored/appconfig-environments.json"}

func (g *authoredAppconfigEnvironmentsScenarios) setupAppconfigEnvironments(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunSetup(ctx, t,
		scenario.Call{
			Op:     "CreateApplication",
			Params: `{"Name":{"$name":"app"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.CreateApplicationInput{}
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("app")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateApplication(ctx, in.(*appconfig.CreateApplicationInput))
			},
			Export: map[string]string{
				"app.id": "$.Id",
			},
		},
	)
}

func (g *authoredAppconfigEnvironmentsScenarios) teardownAppconfigEnvironments(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTeardown(ctx, t,
		scenario.Call{
			Op:     "DeleteEnvironment",
			Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":{"$ref":"env.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.DeleteEnvironmentInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteEnvironment(ctx, in.(*appconfig.DeleteEnvironmentInput))
			},
		},
		scenario.Call{
			Op:     "DeleteApplication",
			Params: `{"ApplicationId":{"$ref":"app.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.DeleteApplicationInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteApplication(ctx, in.(*appconfig.DeleteApplicationInput))
			},
		},
	)
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsCreateEnvironment(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "CreateEnvironment", scenario.Test{
		Call: scenario.Call{
			Op:     "CreateEnvironment",
			Params: `{"ApplicationId":{"$ref":"app.id"},"Description":"compat environments group","Name":{"$name":"env"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.CreateEnvironmentInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				in.Description = aws.String("compat environments group")
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("env")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateEnvironment(ctx, in.(*appconfig.CreateEnvironmentInput))
			},
			Export: map[string]string{
				"env.id": "$.Id",
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.ApplicationId", scenario.Ref("app.id")),
				scenario.NonEmpty("$.Id"),
				scenario.Equals("$.Name", scenario.Name("env")),
				scenario.Equals("$.State", "READY_FOR_DEPLOYMENT"),
			),
			scenario.Readback(
				scenario.Call{
					Op:     "GetEnvironment",
					Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":{"$ref":"env.id"}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.GetEnvironmentInput{}
						in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
						in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().GetEnvironment(ctx, in.(*appconfig.GetEnvironmentInput))
					},
				},
				scenario.Equals("$.Name", scenario.Name("env")),
			),
		},
	})
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsGetEnvironment(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "GetEnvironment", scenario.Test{
		Call: scenario.Call{
			Op:     "GetEnvironment",
			Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":{"$ref":"env.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.GetEnvironmentInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetEnvironment(ctx, in.(*appconfig.GetEnvironmentInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Id", scenario.Ref("env.id")),
				scenario.Equals("$.Name", scenario.Name("env")),
			),
		},
	})
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsListEnvironments(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "ListEnvironments", scenario.Test{
		Call: scenario.Call{
			Op:     "ListEnvironments",
			Params: `{"ApplicationId":{"$ref":"app.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.ListEnvironmentsInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListEnvironments(ctx, in.(*appconfig.ListEnvironmentsInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ListContains(
				nil,
				"$.Items",
				scenario.Where("$.Id", scenario.Ref("env.id")),
				scenario.Where("$.Name", scenario.Name("env")),
			),
		},
	})
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsUpdateEnvironment(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "UpdateEnvironment", scenario.Test{
		Call: scenario.Call{
			Op:     "UpdateEnvironment",
			Params: `{"ApplicationId":{"$ref":"app.id"},"Description":"updated by compat","EnvironmentId":{"$ref":"env.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.UpdateEnvironmentInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				in.Description = aws.String("updated by compat")
				in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UpdateEnvironment(ctx, in.(*appconfig.UpdateEnvironmentInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Description", "updated by compat"),
			),
			scenario.Readback(
				scenario.Call{
					Op:     "GetEnvironment",
					Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":{"$ref":"env.id"}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.GetEnvironmentInput{}
						in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
						in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().GetEnvironment(ctx, in.(*appconfig.GetEnvironmentInput))
					},
				},
				scenario.Equals("$.Description", "updated by compat"),
				scenario.Equals("$.Name", scenario.Name("env")),
			),
		},
	})
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsDeleteEnvironment(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "DeleteEnvironment", scenario.Test{
		Call: scenario.Call{
			Op:     "DeleteEnvironment",
			Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":{"$ref":"env.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.DeleteEnvironmentInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteEnvironment(ctx, in.(*appconfig.DeleteEnvironmentInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.AbsentByError(
				scenario.Call{
					Op:     "GetEnvironment",
					Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":{"$ref":"env.id"}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.GetEnvironmentInput{}
						in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
						in.EnvironmentId = aws.String(scenario.Bind[string](b, "EnvironmentId", scenario.Ref("env.id")))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().GetEnvironment(ctx, in.(*appconfig.GetEnvironmentInput))
					},
				},
				scenario.Error("ResourceNotFoundException", "ResourceNotFoundException"),
			),
			scenario.AbsentFromList(
				&scenario.Call{
					Op:     "ListEnvironments",
					Params: `{"ApplicationId":{"$ref":"app.id"}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.ListEnvironmentsInput{}
						in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().ListEnvironments(ctx, in.(*appconfig.ListEnvironmentsInput))
					},
				},
				"$.Items",
				scenario.Where("$.Id", scenario.Ref("env.id")),
			),
		},
	})
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsGetEnvironmentNotFound(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "GetEnvironmentNotFound", scenario.Test{
		Call: scenario.Call{
			Op:     "GetEnvironment",
			Params: `{"ApplicationId":{"$ref":"app.id"},"EnvironmentId":"zzzzzzz"}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.GetEnvironmentInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				in.EnvironmentId = aws.String("zzzzzzz")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().GetEnvironment(ctx, in.(*appconfig.GetEnvironmentInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ErrorCode(scenario.Error("ResourceNotFoundException", "ResourceNotFoundException")),
		},
	})
}

func (g *authoredAppconfigEnvironmentsScenarios) testAppconfigEnvironmentsListEnvironmentsApplicationNotFound(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigEnvironments.RunTest(ctx, t, "ListEnvironmentsApplicationNotFound", scenario.Test{
		Call: scenario.Call{
			Op:     "ListEnvironments",
			Params: `{"ApplicationId":"zzzzzzz"}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.ListEnvironmentsInput{}
				in.ApplicationId = aws.String("zzzzzzz")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListEnvironments(ctx, in.(*appconfig.ListEnvironmentsInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ErrorCode(scenario.Error("ResourceNotFoundException", "ResourceNotFoundException")),
		},
	})
}
