// Code generated by cmd/compatgen; DO NOT EDIT.

package groups

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/backup"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/clients"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/harness"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/scenario"
)

// ScenariosAuthoredBackupTags returns the authored backup-tags groups.
//
// Generated from compat/model/authored/backup-tags.json by cmd/compatgen.
// The semantics live in internal/scenario; this file is the data and the
// typed SDK calls.
func ScenariosAuthoredBackupTags(c *clients.Clients) ServiceGroup {
	g := &authoredBackupTagsScenarios{c: c}
	return ServiceGroup{
		Name: "scenarios/authored-backup-tags",
		Impls: map[string]harness.TestFn{
			"backup-tags:TagResource":   g.testBackupTagsTagResource,
			"backup-tags:ListTags":      g.testBackupTagsListTags,
			"backup-tags:UntagResource": g.testBackupTagsUntagResource,
		},
		Setup: map[string]func(context.Context, *harness.TestContext) error{
			"backup-tags": g.setupBackupTags,
		},
		Teardown: map[string]func(context.Context, *harness.TestContext) error{
			"backup-tags": g.teardownBackupTags,
		},
	}
}

type authoredBackupTagsScenarios struct {
	c      *clients.Clients
	once   sync.Once
	client *backup.Client
}

// cl builds this service's client once, from the config the suite's
// hand-written groups share. A generated group builds its own rather than
// adding an accessor to internal/clients for every service the generator
// learns to cover; nothing else about the client differs.
func (g *authoredBackupTagsScenarios) cl() *backup.Client {
	g.once.Do(func() { g.client = backup.NewFromConfig(g.c.Config()) })
	return g.client
}

var groupBackupTags = scenario.Group{Name: "backup-tags", File: "compat/model/authored/backup-tags.json"}

func (g *authoredBackupTagsScenarios) setupBackupTags(ctx context.Context, t *harness.TestContext) error {
	return groupBackupTags.RunSetup(ctx, t,
		scenario.Call{
			Op:     "CreateBackupVault",
			Params: `{"BackupVaultName":{"$name":"vault"}}`,
			Build: func(b *scenario.Binder) any {
				in := &backup.CreateBackupVaultInput{}
				in.BackupVaultName = aws.String(scenario.Bind[string](b, "BackupVaultName", scenario.Name("vault")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateBackupVault(ctx, in.(*backup.CreateBackupVaultInput))
			},
			Export: map[string]string{
				"vault.arn": "$.BackupVaultArn",
			},
		},
	)
}

func (g *authoredBackupTagsScenarios) teardownBackupTags(ctx context.Context, t *harness.TestContext) error {
	return groupBackupTags.RunTeardown(ctx, t,
		scenario.Call{
			Op:     "UntagResource",
			Params: `{"ResourceArn":{"$ref":"vault.arn"},"TagKeyList":["oc-compat"]}`,
			Build: func(b *scenario.Binder) any {
				in := &backup.UntagResourceInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Ref("vault.arn")))
				in.TagKeyList = []string{"oc-compat"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UntagResource(ctx, in.(*backup.UntagResourceInput))
			},
		},
		scenario.Call{
			Op:     "DeleteBackupVault",
			Params: `{"BackupVaultName":{"$name":"vault"}}`,
			Build: func(b *scenario.Binder) any {
				in := &backup.DeleteBackupVaultInput{}
				in.BackupVaultName = aws.String(scenario.Bind[string](b, "BackupVaultName", scenario.Name("vault")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteBackupVault(ctx, in.(*backup.DeleteBackupVaultInput))
			},
		},
	)
}

func (g *authoredBackupTagsScenarios) testBackupTagsTagResource(ctx context.Context, t *harness.TestContext) error {
	return groupBackupTags.RunTest(ctx, t, "TagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "TagResource",
			Params: `{"ResourceArn":{"$ref":"vault.arn"},"Tags":{"oc-compat":{"$name":"vault"}}}`,
			Build: func(b *scenario.Binder) any {
				in := &backup.TagResourceInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Ref("vault.arn")))
				in.Tags = map[string]string{
					"oc-compat": scenario.Bind[string](b, "Tags", scenario.Name("vault")),
				}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().TagResource(ctx, in.(*backup.TagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Readback(
				scenario.Call{
					Op:     "ListTags",
					Params: `{"ResourceArn":{"$ref":"vault.arn"}}`,
					Build: func(b *scenario.Binder) any {
						in := &backup.ListTagsInput{}
						in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Ref("vault.arn")))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().ListTags(ctx, in.(*backup.ListTagsInput))
					},
				},
				scenario.Equals("$.Tags.oc-compat", scenario.Name("vault")),
			),
		},
	})
}

func (g *authoredBackupTagsScenarios) testBackupTagsListTags(ctx context.Context, t *harness.TestContext) error {
	return groupBackupTags.RunTest(ctx, t, "ListTags", scenario.Test{
		Call: scenario.Call{
			Op:     "ListTags",
			Params: `{"ResourceArn":{"$ref":"vault.arn"}}`,
			Build: func(b *scenario.Binder) any {
				in := &backup.ListTagsInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Ref("vault.arn")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListTags(ctx, in.(*backup.ListTagsInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Tags.oc-compat", scenario.Name("vault")),
			),
		},
	})
}

func (g *authoredBackupTagsScenarios) testBackupTagsUntagResource(ctx context.Context, t *harness.TestContext) error {
	return groupBackupTags.RunTest(ctx, t, "UntagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "UntagResource",
			Params: `{"ResourceArn":{"$ref":"vault.arn"},"TagKeyList":["oc-compat"]}`,
			Build: func(b *scenario.Binder) any {
				in := &backup.UntagResourceInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Ref("vault.arn")))
				in.TagKeyList = []string{"oc-compat"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UntagResource(ctx, in.(*backup.UntagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Readback(
				scenario.Call{
					Op:     "ListTags",
					Params: `{"ResourceArn":{"$ref":"vault.arn"}}`,
					Build: func(b *scenario.Binder) any {
						in := &backup.ListTagsInput{}
						in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Ref("vault.arn")))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().ListTags(ctx, in.(*backup.ListTagsInput))
					},
				},
				scenario.Missing("$.Tags.oc-compat"),
			),
		},
	})
}
