// Code generated by cmd/compatgen; DO NOT EDIT.

package groups

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/appconfig"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/clients"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/harness"
	"github.com/overcast-sh/overcast-compat-go-sdk/internal/scenario"
)

// ScenariosAuthoredAppconfigTags returns the authored appconfig-tags groups.
//
// Generated from compat/model/authored/appconfig-tags.json by cmd/compatgen.
// The semantics live in internal/scenario; this file is the data and the
// typed SDK calls.
func ScenariosAuthoredAppconfigTags(c *clients.Clients) ServiceGroup {
	g := &authoredAppconfigTagsScenarios{c: c}
	return ServiceGroup{
		Name: "scenarios/authored-appconfig-tags",
		Impls: map[string]harness.TestFn{
			"appconfig-tags:CreateApplicationWithTags":   g.testAppconfigTagsCreateApplicationWithTags,
			"appconfig-tags:TagResource":                 g.testAppconfigTagsTagResource,
			"appconfig-tags:ListTagsForResource":         g.testAppconfigTagsListTagsForResource,
			"appconfig-tags:UntagResource":               g.testAppconfigTagsUntagResource,
			"appconfig-tags:ListTagsForResourceNotFound": g.testAppconfigTagsListTagsForResourceNotFound,
		},
		Setup: map[string]func(context.Context, *harness.TestContext) error{
			"appconfig-tags": g.setupAppconfigTags,
		},
		Teardown: map[string]func(context.Context, *harness.TestContext) error{
			"appconfig-tags": g.teardownAppconfigTags,
		},
	}
}

type authoredAppconfigTagsScenarios struct {
	c      *clients.Clients
	once   sync.Once
	client *appconfig.Client
}

// cl builds this service's client once, from the config the suite's
// hand-written groups share. A generated group builds its own rather than
// adding an accessor to internal/clients for every service the generator
// learns to cover; nothing else about the client differs.
func (g *authoredAppconfigTagsScenarios) cl() *appconfig.Client {
	g.once.Do(func() { g.client = appconfig.NewFromConfig(g.c.Config()) })
	return g.client
}

var groupAppconfigTags = scenario.Group{Name: "appconfig-tags", File: "compat/model/authored/appconfig-tags.json"}

func (g *authoredAppconfigTagsScenarios) setupAppconfigTags(ctx context.Context, t *harness.TestContext) error {
	// No setup steps: an empty phase is a no-op, not a missing one.
	return groupAppconfigTags.RunSetup(ctx, t)
}

func (g *authoredAppconfigTagsScenarios) teardownAppconfigTags(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigTags.RunTeardown(ctx, t,
		scenario.Call{
			Op:     "DeleteApplication",
			Params: `{"ApplicationId":{"$ref":"app.id"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.DeleteApplicationInput{}
				in.ApplicationId = aws.String(scenario.Bind[string](b, "ApplicationId", scenario.Ref("app.id")))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().DeleteApplication(ctx, in.(*appconfig.DeleteApplicationInput))
			},
		},
	)
}

func (g *authoredAppconfigTagsScenarios) testAppconfigTagsCreateApplicationWithTags(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigTags.RunTest(ctx, t, "CreateApplicationWithTags", scenario.Test{
		Call: scenario.Call{
			Op:     "CreateApplication",
			Params: `{"Name":{"$name":"app"},"Tags":{"Owner":"compat","Team":"platform"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.CreateApplicationInput{}
				in.Name = aws.String(scenario.Bind[string](b, "Name", scenario.Name("app")))
				in.Tags = map[string]string{"Owner": "compat", "Team": "platform"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().CreateApplication(ctx, in.(*appconfig.CreateApplicationInput))
			},
			Export: map[string]string{
				"app.id": "$.Id",
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.NonEmpty("$.Id"),
			),
			scenario.Readback(
				scenario.Call{
					Op:     "ListTagsForResource",
					Params: `{"ResourceArn":{"$concat":["arn:aws:appconfig:us-east-1:000000000000:application/",{"$ref":"app.id"}]}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.ListTagsForResourceInput{}
						in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Concat("arn:aws:appconfig:us-east-1:000000000000:application/", scenario.Ref("app.id"))))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().ListTagsForResource(ctx, in.(*appconfig.ListTagsForResourceInput))
					},
				},
				scenario.Equals("$.Tags.Owner", "compat"),
				scenario.Equals("$.Tags.Team", "platform"),
			),
		},
	})
}

func (g *authoredAppconfigTagsScenarios) testAppconfigTagsTagResource(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigTags.RunTest(ctx, t, "TagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "TagResource",
			Params: `{"ResourceArn":{"$concat":["arn:aws:appconfig:us-east-1:000000000000:application/",{"$ref":"app.id"}]},"Tags":{"Owner":"compat-updated","Stage":"beta"}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.TagResourceInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Concat("arn:aws:appconfig:us-east-1:000000000000:application/", scenario.Ref("app.id"))))
				in.Tags = map[string]string{"Owner": "compat-updated", "Stage": "beta"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().TagResource(ctx, in.(*appconfig.TagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Readback(
				scenario.Call{
					Op:     "ListTagsForResource",
					Params: `{"ResourceArn":{"$concat":["arn:aws:appconfig:us-east-1:000000000000:application/",{"$ref":"app.id"}]}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.ListTagsForResourceInput{}
						in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Concat("arn:aws:appconfig:us-east-1:000000000000:application/", scenario.Ref("app.id"))))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().ListTagsForResource(ctx, in.(*appconfig.ListTagsForResourceInput))
					},
				},
				scenario.Equals("$.Tags.Owner", "compat-updated"),
				scenario.Equals("$.Tags.Stage", "beta"),
				scenario.Equals("$.Tags.Team", "platform"),
			),
		},
	})
}

func (g *authoredAppconfigTagsScenarios) testAppconfigTagsListTagsForResource(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigTags.RunTest(ctx, t, "ListTagsForResource", scenario.Test{
		Call: scenario.Call{
			Op:     "ListTagsForResource",
			Params: `{"ResourceArn":{"$concat":["arn:aws:appconfig:us-east-1:000000000000:application/",{"$ref":"app.id"}]}}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.ListTagsForResourceInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Concat("arn:aws:appconfig:us-east-1:000000000000:application/", scenario.Ref("app.id"))))
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListTagsForResource(ctx, in.(*appconfig.ListTagsForResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ResponseField(
				scenario.Equals("$.Tags.Owner", "compat-updated"),
				scenario.Equals("$.Tags.Stage", "beta"),
				scenario.Equals("$.Tags.Team", "platform"),
			),
		},
	})
}

func (g *authoredAppconfigTagsScenarios) testAppconfigTagsUntagResource(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigTags.RunTest(ctx, t, "UntagResource", scenario.Test{
		Call: scenario.Call{
			Op:     "UntagResource",
			Params: `{"ResourceArn":{"$concat":["arn:aws:appconfig:us-east-1:000000000000:application/",{"$ref":"app.id"}]},"TagKeys":["Team"]}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.UntagResourceInput{}
				in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Concat("arn:aws:appconfig:us-east-1:000000000000:application/", scenario.Ref("app.id"))))
				in.TagKeys = []string{"Team"}
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().UntagResource(ctx, in.(*appconfig.UntagResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.Readback(
				scenario.Call{
					Op:     "ListTagsForResource",
					Params: `{"ResourceArn":{"$concat":["arn:aws:appconfig:us-east-1:000000000000:application/",{"$ref":"app.id"}]}}`,
					Build: func(b *scenario.Binder) any {
						in := &appconfig.ListTagsForResourceInput{}
						in.ResourceArn = aws.String(scenario.Bind[string](b, "ResourceArn", scenario.Concat("arn:aws:appconfig:us-east-1:000000000000:application/", scenario.Ref("app.id"))))
						return in
					},
					Send: func(ctx context.Context, in any) (any, error) {
						return g.cl().ListTagsForResource(ctx, in.(*appconfig.ListTagsForResourceInput))
					},
				},
				scenario.Equals("$.Tags.Owner", "compat-updated"),
				scenario.Missing("$.Tags.Team"),
			),
		},
	})
}

func (g *authoredAppconfigTagsScenarios) testAppconfigTagsListTagsForResourceNotFound(ctx context.Context, t *harness.TestContext) error {
	return groupAppconfigTags.RunTest(ctx, t, "ListTagsForResourceNotFound", scenario.Test{
		Call: scenario.Call{
			Op:     "ListTagsForResource",
			Params: `{"ResourceArn":"arn:aws:appconfig:us-east-1:000000000000:application/zzzzzzz"}`,
			Build: func(b *scenario.Binder) any {
				in := &appconfig.ListTagsForResourceInput{}
				in.ResourceArn = aws.String("arn:aws:appconfig:us-east-1:000000000000:application/zzzzzzz")
				return in
			},
			Send: func(ctx context.Context, in any) (any, error) {
				return g.cl().ListTagsForResource(ctx, in.(*appconfig.ListTagsForResourceInput))
			},
		},
		Assert: []scenario.Clause{
			scenario.ErrorCode(scenario.Error("ResourceNotFoundException", "ResourceNotFoundException")),
		},
	})
}
