//go:build dev

package cloudfront

import "github.com/overcast-sh/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		// Distributions
		capabilities.Capability{Service: "cloudfront", Operation: "CreateDistribution", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "CallerReference idempotency; Status always \"Deployed\""},
		capabilities.Capability{Service: "cloudfront", Operation: "GetDistribution", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "Returns ETag header"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetDistributionConfig", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "Returns DistributionConfig portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateDistribution", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteDistribution", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match + Enabled=false"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListDistributions", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination via serviceutil.Paginate"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreateDistributionWithTags", Category: "Distributions",
			Status: capabilities.StatusSupported, Notes: "Creates distribution + tags atomically; _custom_id_ tag support"},

		// Invalidations
		capabilities.Capability{Service: "cloudfront", Operation: "CreateInvalidation", Category: "Invalidations",
			Status: capabilities.StatusSupported, Notes: "Supports path and tag invalidations (#tag); Status instantly \"Completed\""},
		capabilities.Capability{Service: "cloudfront", Operation: "GetInvalidation", Category: "Invalidations",
			Status: capabilities.StatusSupported, Notes: "Returns invalidation by distribution + invalidation ID"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListInvalidations", Category: "Invalidations",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination"},

		// OAC / OAI
		capabilities.Capability{Service: "cloudfront", Operation: "CreateOriginAccessControl", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Generates ID, returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetOriginAccessControl", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Returns OAC by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateOriginAccessControl", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteOriginAccessControl", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListOriginAccessControls", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreateCloudFrontOriginAccessIdentity", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "CallerReference required; generates S3CanonicalUserId"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetCloudFrontOriginAccessIdentity", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Returns OAI by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetCloudFrontOriginAccessIdentityConfig", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateCloudFrontOriginAccessIdentity", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteCloudFrontOriginAccessIdentity", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListCloudFrontOriginAccessIdentities", Category: "OAC / OAI",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination"},

		// Tagging
		capabilities.Capability{Service: "cloudfront", Operation: "ListTagsForResource", Category: "Tagging",
			Status: capabilities.StatusSupported, Notes: "Returns tags by resource ARN"},
		capabilities.Capability{Service: "cloudfront", Operation: "TagResource", Category: "Tagging",
			Status: capabilities.StatusSupported, Notes: "Merges tags into existing set"},
		capabilities.Capability{Service: "cloudfront", Operation: "UntagResource", Category: "Tagging",
			Status: capabilities.StatusSupported, Notes: "Removes specified tag keys"},

		// Policies
		capabilities.Capability{Service: "cloudfront", Operation: "CreateCachePolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Generates ID, returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetCachePolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Returns policy by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetCachePolicyConfig", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateCachePolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteCachePolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListCachePolicies", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreateOriginRequestPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Generates ID, returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetOriginRequestPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Returns policy by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetOriginRequestPolicyConfig", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateOriginRequestPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteOriginRequestPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListOriginRequestPolicies", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreateResponseHeadersPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Generates ID, returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetResponseHeadersPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Returns policy by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetResponseHeadersPolicyConfig", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateResponseHeadersPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteResponseHeadersPolicy", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListResponseHeadersPolicies", Category: "Policies",
			Status: capabilities.StatusSupported, Notes: "Marker/MaxItems pagination"},

		// Proxy. EmulatorOnly: CloudFront's data plane is not an AWS API
		// operation at all, so this row is documented but never counted as one
		// of the AWS operations the service covers (#75).
		capabilities.Capability{Service: "cloudfront", Operation: "ProxyRequest", Category: "Proxy",
			EmulatorOnly: true,
			Status:       capabilities.StatusSupported, Notes: "Path-pattern matching, origin forwarding (dialled locally when Overcast answers for the origin), GET response caching, CloudFront Functions, origin-group failover, geo restriction and custom error responses"},

		// Functions
		capabilities.Capability{Service: "cloudfront", Operation: "CreateFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Stores code + config; Stage=DEVELOPMENT; returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "DescribeFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Returns FunctionSummary with metadata"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Returns raw function code (base64) with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListFunctions", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Filters by Stage query param; MaxItems pagination"},
		capabilities.Capability{Service: "cloudfront", Operation: "TestFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Returns a fixed success result without running the code; a function attached to a behaviour does execute on requests through the distribution"},
		capabilities.Capability{Service: "cloudfront", Operation: "PublishFunction", Category: "Functions",
			Status: capabilities.StatusSupported, Notes: "Promotes DEVELOPMENT → LIVE stage"},

		// Keys & Crypto
		capabilities.Capability{Service: "cloudfront", Operation: "CreateKeyGroup", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Generates ID, returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetKeyGroup", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Returns key group by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetKeyGroupConfig", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateKeyGroup", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteKeyGroup", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListKeyGroups", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "MaxItems pagination"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreatePublicKey", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "CallerReference dedup; generates ID + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetPublicKey", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Returns public key by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetPublicKeyConfig", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdatePublicKey", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeletePublicKey", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListPublicKeys", Category: "Keys & Crypto",
			Status: capabilities.StatusSupported, Notes: "MaxItems pagination"},

		// Monitoring
		capabilities.Capability{Service: "cloudfront", Operation: "CreateMonitoringSubscription", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Per-distribution; requires existing distribution"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetMonitoringSubscription", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Returns subscription by distribution ID"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteMonitoringSubscription", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Removes subscription for distribution"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreateRealtimeLogConfig", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Name-based; generates ARN; duplicate name check"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetRealtimeLogConfig", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Lookup by Name or ARN in request body"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateRealtimeLogConfig", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Updates by Name in request body"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteRealtimeLogConfig", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "Deletes by Name or ARN in request body"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListRealtimeLogConfigs", Category: "Monitoring",
			Status: capabilities.StatusSupported, Notes: "MaxItems pagination"},

		// FLE
		capabilities.Capability{Service: "cloudfront", Operation: "CreateFieldLevelEncryptionConfig", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "CallerReference required; generates ID"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetFieldLevelEncryption", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Returns FLE config by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetFieldLevelEncryptionConfig", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateFieldLevelEncryptionConfig", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteFieldLevelEncryption", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListFieldLevelEncryptionConfigs", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "MaxItems pagination"},
		capabilities.Capability{Service: "cloudfront", Operation: "CreateFieldLevelEncryptionProfile", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "CallerReference required; generates ID"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetFieldLevelEncryptionProfile", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Returns FLE profile by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetFieldLevelEncryptionProfileConfig", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateFieldLevelEncryptionProfile", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteFieldLevelEncryptionProfile", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListFieldLevelEncryptionProfiles", Category: "FLE",
			Status: capabilities.StatusSupported, Notes: "MaxItems pagination"},

		// Deployment
		capabilities.Capability{Service: "cloudfront", Operation: "CreateContinuousDeploymentPolicy", Category: "Deployment",
			Status: capabilities.StatusSupported, Notes: "Generates ID, returns ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetContinuousDeploymentPolicy", Category: "Deployment",
			Status: capabilities.StatusSupported, Notes: "Returns policy by ID with ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "GetContinuousDeploymentPolicyConfig", Category: "Deployment",
			Status: capabilities.StatusSupported, Notes: "Returns config portion + ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "UpdateContinuousDeploymentPolicy", Category: "Deployment",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag; bumps version"},
		capabilities.Capability{Service: "cloudfront", Operation: "DeleteContinuousDeploymentPolicy", Category: "Deployment",
			Status: capabilities.StatusSupported, Notes: "Requires If-Match ETag"},
		capabilities.Capability{Service: "cloudfront", Operation: "ListContinuousDeploymentPolicies", Category: "Deployment",
			Status: capabilities.StatusSupported, Notes: "MaxItems pagination"},
	)
}
