//go:build dev

package cognito

import "github.com/overcast-sh/overcast/internal/capabilities"

func init() {
	capabilities.Default.Register(
		// User Pool operations
		capabilities.Capability{Service: "cognito", Operation: "CreateUserPool", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "Returns Id and Arn; Id format {region}_{8-char-hex}; accepts SignInPolicy, email templates, UserAttributeUpdateSettings, DeviceConfiguration, AliasAttributes, AccountRecoverySetting, SmsConfiguration, SmsAuthenticationMessage, SmsVerificationMessage, EmailVerificationMessage, EmailVerificationSubject, and LambdaConfig; LambdaConfig's PreSignUp, PostConfirmation, PreTokenGeneration, PostAuthentication, and CustomMessage are invoked on the classic X-Amz-Target API (issue #1171); PreAuthentication, UserMigration, the CUSTOM_AUTH challenge triggers (#88/#94/#101), and the Smithy RPC v2 duplicate dispatch path are not; a LITE-tier UserPoolTier rejects a SignInPolicy with FeatureUnavailableInTierException, matching AWS's Essentials-tier gate on choice-based sign-in"},
		capabilities.Capability{Service: "cognito", Operation: "DescribeUserPool", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "Returns SignInPolicy, email templates, admin config, email configuration, UserAttributeUpdateSettings, AliasAttributes, AccountRecoverySetting, SmsConfiguration, SmsAuthenticationMessage, SmsVerificationMessage, EmailVerificationMessage, EmailVerificationSubject, and LambdaConfig"},
		capabilities.Capability{Service: "cognito", Operation: "DeleteUserPool", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "ResourceNotFoundException if not found"},
		capabilities.Capability{Service: "cognito", Operation: "UpdateUserPool", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "Updates SignInPolicy, VerificationMessageTemplate, AdminCreateUserConfig, EmailConfiguration, UserAttributeUpdateSettings, DeviceConfiguration, AccountRecoverySetting, SmsConfiguration, SmsAuthenticationMessage, SmsVerificationMessage, EmailVerificationMessage, EmailVerificationSubject, and LambdaConfig; the CloudFormation UserPool handler treats an AliasAttributes/UsernameAttributes change as requiring replacement, matching real Cognito's UpdateUserPoolRequest (neither is a member there); rejects an invalid UserPoolTier value, and rejects a LITE-tier pool's SignInPolicy update with FeatureUnavailableInTierException"},
		capabilities.Capability{Service: "cognito", Operation: "ListUserPools", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "Pagination via NextToken"},
		capabilities.Capability{Service: "cognito", Operation: "SetUserPoolMfaConfig", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "Stores and echoes MfaConfiguration, SmsMfaConfiguration, SoftwareTokenMfaConfiguration, EmailMfaConfiguration and WebAuthnConfiguration; replaces the MFA configuration as a unit, so a factor the request omits is cleared and an omitted MfaConfiguration means OFF; rejects ON/OPTIONAL with no factor enabled and OFF with a factor configured, and validates the {####} message templates and the Essentials tier for email MFA; the stored factors are not enforced at sign-in — no SMS_MFA or email MFA challenge is issued and the templates are never used to deliver a code; passkey cryptographic validation is intentionally partial"},
		capabilities.Capability{Service: "cognito", Operation: "GetUserPoolMfaConfig", Category: "User Pool operations", Status: capabilities.StatusSupported, Notes: "Returns the stored MfaConfiguration (OFF for a pool that has never been configured), SmsMfaConfiguration, SoftwareTokenMfaConfiguration, EmailMfaConfiguration and WebAuthnConfiguration"},
		// User Pool Client operations
		capabilities.Capability{Service: "cognito", Operation: "CreateUserPoolClient", Category: "User Pool Client operations", Status: capabilities.StatusSupported, Notes: "Returns ClientId (26-char hex); accepts and validates ExplicitAuthFlows, AccessTokenValidity, IdTokenValidity, RefreshTokenValidity, TokenValidityUnits, PreventUserExistenceErrors, ReadAttributes, WriteAttributes; ALLOW_USER_AUTH on a LITE-tier pool returns FeatureUnavailableInTierException, matching AWS's Essentials-tier gate on choice-based sign-in"},
		capabilities.Capability{Service: "cognito", Operation: "DescribeUserPoolClient", Category: "User Pool Client operations", Status: capabilities.StatusSupported, Notes: "ResourceNotFoundException if not found"},
		capabilities.Capability{Service: "cognito", Operation: "DeleteUserPoolClient", Category: "User Pool Client operations", Status: capabilities.StatusSupported, Notes: "ResourceNotFoundException if not found"},
		capabilities.Capability{Service: "cognito", Operation: "UpdateUserPoolClient", Category: "User Pool Client operations", Status: capabilities.StatusSupported, Notes: "Updates client name, validates ExplicitAuthFlows, token validity, PreventUserExistenceErrors, ReadAttributes, WriteAttributes; ALLOW_USER_AUTH on a LITE-tier pool returns FeatureUnavailableInTierException"},
		capabilities.Capability{Service: "cognito", Operation: "ListUserPoolClients", Category: "User Pool Client operations", Status: capabilities.StatusSupported, Notes: "Pagination via NextToken"},
		// User operations
		capabilities.Capability{Service: "cognito", Operation: "AdminCreateUser", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Bcrypt hashes password; sends email unless MessageAction=SUPPRESS; invokes PreSignUp_AdminCreateUser (its autoConfirm/autoVerify response fields are ignored, matching AWS) and CustomMessage_AdminCreateUser (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "AdminDeleteUser", Category: "User operations", Status: capabilities.StatusSupported, Notes: "UserNotFoundException if not found"},
		capabilities.Capability{Service: "cognito", Operation: "AdminGetUser", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Returns attributes + status"},
		capabilities.Capability{Service: "cognito", Operation: "AdminSetUserPassword", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Permanent=true sets status CONFIRMED"},
		capabilities.Capability{Service: "cognito", Operation: "AdminConfirmSignUp", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Confirms a UNCONFIRMED user; invokes PostConfirmation_ConfirmSignUp fire-and-forget — a trigger error is logged but does not fail the call or roll back the confirmation (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "AdminUpdateUserAttributes", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Merges attributes; honors verification-before-update settings unless *_verified=true is supplied"},
		capabilities.Capability{Service: "cognito", Operation: "AdminDeleteUserAttributes", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Removes named attributes from a user"},
		capabilities.Capability{Service: "cognito", Operation: "AdminDisableUser", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Sets Enabled=false; sign-in returns NotAuthorizedException"},
		capabilities.Capability{Service: "cognito", Operation: "AdminEnableUser", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Re-enables a disabled user"},
		capabilities.Capability{Service: "cognito", Operation: "ListUsers", Category: "User operations", Status: capabilities.StatusSupported, Notes: "Pagination via PaginationToken"},
		// Auth / Token operations
		capabilities.Capability{Service: "cognito", Operation: "SignUp", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Sends confirmation email; returns UserSub; invokes PreSignUp_SignUp (autoConfirmUser/autoVerifyEmail/autoVerifyPhone honored — an auto-confirmed user also fires PostConfirmation_ConfirmSignUp within the same call, and no confirmation message is sent) and CustomMessage_SignUp; either failing fails SignUp with UserLambdaValidationException (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "ConfirmSignUp", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "CodeMismatchException / ExpiredCodeException on failure; returns Session for USER_AUTH sign-in; invokes PostConfirmation_ConfirmSignUp fire-and-forget (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "ResendConfirmationCode", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Generates and emails a new confirmation code; invokes CustomMessage_ResendCode, failing the call on a trigger error (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "InitiateAuth", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "USER_PASSWORD_AUTH + USER_SRP_AUTH + REFRESH_TOKEN_AUTH + CUSTOM_AUTH; USER_AUTH with ConfirmSignUp Session, SELECT_CHALLENGE/PASSWORD/PASSWORD_SRP/WEB_AUTHN/EMAIL_OTP/SMS_OTP, or preferred PASSWORD/WEB_AUTHN/EMAIL_OTP/SMS_OTP; returns NEW_PASSWORD_REQUIRED, SOFTWARE_TOKEN_MFA, or DEVICE_SRP_AUTH; a completed authentication invokes PostAuthentication_Authentication then PreTokenGeneration (TokenGeneration_Authentication/_RefreshTokens/_NewPasswordChallenge/_AuthenticateDevice as appropriate), each able to fail the call (issue #1171); USER_SRP_AUTH/PASSWORD_SRP proofs are accepted once the SRP claim fields are present and are not cryptographically verified; WebAuthn assertion signature validation is intentionally partial"},
		capabilities.Capability{Service: "cognito", Operation: "AdminInitiateAuth", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "USER_PASSWORD_AUTH + USER_SRP_AUTH + REFRESH_TOKEN_AUTH + CUSTOM_AUTH with UserPoolId; USER_AUTH with ConfirmSignUp Session, SELECT_CHALLENGE/PASSWORD/PASSWORD_SRP/WEB_AUTHN/EMAIL_OTP/SMS_OTP, or preferred PASSWORD/WEB_AUTHN/EMAIL_OTP/SMS_OTP; same PostAuthentication/PreTokenGeneration trigger invocation as InitiateAuth (issue #1171); same SRP verification boundary as InitiateAuth — proofs are accepted once the claim fields are present, not cryptographically verified"},
		capabilities.Capability{Service: "cognito", Operation: "RespondToAuthChallenge", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "SELECT_CHALLENGE/PASSWORD/PASSWORD_SRP/WEB_AUTHN/EMAIL_OTP/SMS_OTP, PASSWORD, PASSWORD_VERIFIER, CUSTOM_CHALLENGE, DEVICE_SRP_AUTH, DEVICE_PASSWORD_VERIFIER, WEB_AUTHN, EMAIL_OTP, SMS_OTP, NEW_PASSWORD_REQUIRED, and SOFTWARE_TOKEN_MFA challenges; a challenge completion that issues tokens invokes PostAuthentication_Authentication (skipped for NEW_PASSWORD_REQUIRED) then PreTokenGeneration, each able to fail the call (issue #1171); PASSWORD_VERIFIER/DEVICE_PASSWORD_VERIFIER accept the SRP claim fields without cryptographic proof verification, and WEB_AUTHN accepts the credential response without cryptographic assertion signature verification"},
		capabilities.Capability{Service: "cognito", Operation: "AdminRespondToAuthChallenge", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Same as above with admin credentials, including the same trigger invocation (issue #1171); same SRP/WebAuthn verification boundary as RespondToAuthChallenge"},
		capabilities.Capability{Service: "cognito", Operation: "ConfirmDevice", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Confirms a NewDeviceMetadata device key and stores remembered-device metadata; SRP verifier validation is intentionally partial"},
		capabilities.Capability{Service: "cognito", Operation: "GetDevice", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Returns a confirmed device for the signed-in user"},
		capabilities.Capability{Service: "cognito", Operation: "ListDevices", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Lists confirmed devices for the signed-in user"},
		capabilities.Capability{Service: "cognito", Operation: "UpdateDeviceStatus", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Marks a signed-in user's confirmed device as remembered or not_remembered"},
		capabilities.Capability{Service: "cognito", Operation: "ForgetDevice", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Removes a confirmed device for the signed-in user"},
		capabilities.Capability{Service: "cognito", Operation: "AdminGetDevice", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Returns a user's confirmed device; IAM authorization on the requested user is stored but not enforced unless OVERCAST_ENFORCE_IAM is set, the same project-wide behavior as every other operation; DeviceAttributes names (device_status, device_name, dev:device_remembered_status) are emulator choices where AWS's list is unconstrained"},
		capabilities.Capability{Service: "cognito", Operation: "AdminListDevices", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Lists a user's confirmed devices with pagination; PaginationToken is an emulator-internal integer offset rather than AWS's opaque token, and Limit accepts 0-60 matching the model's QueryLimitType"},
		capabilities.Capability{Service: "cognito", Operation: "AdminUpdateDeviceStatus", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Marks a user's confirmed device as remembered or not_remembered"},
		capabilities.Capability{Service: "cognito", Operation: "AdminForgetDevice", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Removes a user's confirmed device"},
		capabilities.Capability{Service: "cognito", Operation: "ForgotPassword", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Sends password-reset code by email; invokes CustomMessage_ForgotPassword, failing the call on a trigger error (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "ConfirmForgotPassword", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Validates reset code; sets new bcrypt password; invokes PostConfirmation_ConfirmForgotPassword fire-and-forget (issue #1171)"},
		capabilities.Capability{Service: "cognito", Operation: "ChangePassword", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Validates AccessToken + old password before setting new one"},
		capabilities.Capability{Service: "cognito", Operation: "GetUser", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Validates AccessToken; returns full user profile"},
		capabilities.Capability{Service: "cognito", Operation: "UpdateUserAttributes", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Self-service; validates AccessToken; merges attributes or creates pending email/phone updates with CodeDeliveryDetailsList"},
		capabilities.Capability{Service: "cognito", Operation: "VerifyUserAttribute", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Verifies pending email/phone updates and sets *_verified=true"},
		capabilities.Capability{Service: "cognito", Operation: "GetUserAttributeVerificationCode", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Sends or resends email/phone verification codes for the signed-in user"},
		capabilities.Capability{Service: "cognito", Operation: "DeleteUserAttributes", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Self-service; validates AccessToken; removes named attributes"},
		capabilities.Capability{Service: "cognito", Operation: "GlobalSignOut", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Revokes access + id + refresh tokens for the user"},
		capabilities.Capability{Service: "cognito", Operation: "RevokeToken", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Revokes a specific refresh token"},
		capabilities.Capability{Service: "cognito", Operation: "AssociateSoftwareToken", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Issues a TOTP secret for the user; requires valid AccessToken"},
		capabilities.Capability{Service: "cognito", Operation: "VerifySoftwareToken", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Verifies a TOTP code and marks the secret verified"},
		capabilities.Capability{Service: "cognito", Operation: "StartWebAuthnRegistration", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Returns passkey CredentialCreationOptions for the signed-in user; the registration challenge expires after 5 minutes (WebAuthnChallengeNotFoundException from CompleteWebAuthnRegistration), but AWS's exact WebAuthn error taxonomy for expired, mismatched, or replayed challenges is not reproduced"},
		capabilities.Capability{Service: "cognito", Operation: "CompleteWebAuthnRegistration", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Registers passkey credential metadata; attestation validation is intentionally partial"},
		capabilities.Capability{Service: "cognito", Operation: "SetUserMFAPreference", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Enables/disables TOTP MFA for the calling user"},
		capabilities.Capability{Service: "cognito", Operation: "AdminSetUserMFAPreference", Category: "Auth / Token operations", Status: capabilities.StatusSupported, Notes: "Same as above, admin version"},
		// Group operations
		capabilities.Capability{Service: "cognito", Operation: "CreateGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "GroupExistsException if duplicate"},
		capabilities.Capability{Service: "cognito", Operation: "GetGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "ResourceNotFoundException if not found"},
		capabilities.Capability{Service: "cognito", Operation: "DeleteGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "ResourceNotFoundException if not found"},
		capabilities.Capability{Service: "cognito", Operation: "UpdateGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "Updates Description, Precedence, RoleArn"},
		capabilities.Capability{Service: "cognito", Operation: "ListGroups", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "Returns all groups for a pool"},
		capabilities.Capability{Service: "cognito", Operation: "AdminAddUserToGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "Idempotent"},
		capabilities.Capability{Service: "cognito", Operation: "AdminRemoveUserFromGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "No error if user is not in group"},
		capabilities.Capability{Service: "cognito", Operation: "AdminListGroupsForUser", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "Returns groups the user belongs to"},
		capabilities.Capability{Service: "cognito", Operation: "ListUsersInGroup", Category: "Group operations", Status: capabilities.StatusSupported, Notes: "Returns users belonging to the specified group"},
		// User Pool Domain operations
		capabilities.Capability{Service: "cognito", Operation: "CreateUserPoolDomain", Category: "User Pool Domain operations", Status: capabilities.StatusSupported, Notes: "Associates a domain with the user pool's hosted UI"},
		capabilities.Capability{Service: "cognito", Operation: "DescribeUserPoolDomain", Category: "User Pool Domain operations", Status: capabilities.StatusSupported, Notes: "Returns domain details; empty DomainDescription when domain not found"},
		capabilities.Capability{Service: "cognito", Operation: "DeleteUserPoolDomain", Category: "User Pool Domain operations", Status: capabilities.StatusSupported, Notes: "Removes the domain association from the pool"},
		capabilities.Capability{Service: "cognito", Operation: "UpdateUserPoolDomain", Category: "User Pool Domain operations", Status: capabilities.StatusSupported, Notes: "Accepted; SSL certificate updates are inert in the emulator"},
		// Tags
		capabilities.Capability{Service: "cognito", Operation: "TagResource", Category: "Tags", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "cognito", Operation: "UntagResource", Category: "Tags", Status: capabilities.StatusSupported},
		capabilities.Capability{Service: "cognito", Operation: "ListTagsForResource", Category: "Tags", Status: capabilities.StatusSupported},
	)
}
